### PR TITLE
fix: reconcile on namespace changes

### LINKED ISSUE #3847: serviceMonitorNamespaceSelector not working correctly
**What happened?**

I need to activate and deactivate metric recollection at the namespace level.
I am using (trying) a label on every namespace I want to monitor with a specific Prometheus instance. 
Also, I need to monitor just a subset of ServiceMonitor (those with the `example.com.app: app-1` label).

I am using the following Prometheus definition that is supposed to implement the usecase. 

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    example.com.app: app-1
    example.com.component: prometheus
  name: app-1
  namespace: monitoring-app-1
spec:
  podMetadata:
    labels:
      example.com.app: app-1
      example.com.component: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: "true"
  serviceMonitorSelector:
    matchLabels:
      example.com.app: app-1
  serviceAccountName: prometheus
```

So, I can have multiple namespaces, some of them with the `monitoring: "true"` label. 
On the other side, I can have multiple ServiceMonitors with the `example.com.app: app-1` label in multiple namespaces (with or without the `"monitoring: true"` label).

I want to monitor only the ServiceMonitors with the label `example.com.app: app-1` inside namespaces having the `monitoring: true` label. In addition, I can activate/deactivate the monitoring of the ServiceMonitor changing the namespace label from `true` to `false` and the other way round.

**What currently happens is that changing the `namespace` label does not trigger any reconfiguration on the Prometheus instance.** So I can not activate/deactivate the metrics.

**Did you expect to see something different?**

I expect to have the Prometheus reconfigured if a namespace label changed as it is part of the `serviceMonitorNamespaceSelector` Prometheus definition.

**How to reproduce it (as minimally and precisely as possible)**:

I tried to simplify the setup as much as possible:

```bash
$ kind create cluster --name prometheus-operator-issue
# Deploy the prometheus-operator
$ kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.45.0/bundle.yaml
# Deploy the usecase, review the code first, security matters 
$ kubectl apply -f https://gist.githubusercontent.com/angelbarrera92/9619ff72607920003fdc7153e8b30a4f/raw/16e06f9e4d1f57ebbd05126a6f23d5df4dfb0b01/prometheus-operator-namespace-issue.yaml
```

Then open a port-forward to the Prometheus UI:

```bash
$ kubectl port-forward -n monitoring-app-1 prometheus-app-1-0 9090:9090
```

And access it with a browser: http://localhost:9090/targets

Captura de pantalla 2021-02-18 a las 16 38 31

Then, try to deactivate the monitoring on the `monitoring-app-1` namespace by changing its label:

```bash
$ kubectl label ns monitoring-app-1 --overwrite monitoring=false
namespace/monitoring-app-1 labeled
```

Check the UI and wait a few minutes, nothing happens.

Captura de pantalla 2021-02-18 a las 16 40 37

**!!BUT!!** if you add a label (or any other change) to the ServiceMonitor, it will trigger a reconfiguration of the Prometheus server disabling the ServiceMonitor (as it was inside the namespace we changed the label above)

```bash
$ kubectl -n monitoring-app-1 label ServiceMonitor prometheus --overwrite update=1
servicemonitor.monitoring.coreos.com/prometheus labeled
```

After a few seconds/minutes, the ServiceMonitor disappear as it was inside the *deactivated* namespace:

Captura de pantalla 2021-02-18 a las 16 43 24

**Environment**

* Prometheus Operator version:

    `v0.45.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    `kind`

* Manifests:

- https://gist.githubusercontent.com/angelbarrera92/9619ff72607920003fdc7153e8b30a4f/raw/16e06f9e4d1f57ebbd05126a6f23d5df4dfb0b01/prometheus-operator-namespace-issue.yaml

* Prometheus Operator Logs:

Nothing really relevant happens.

**Anything else we need to know?**:

It smells like the operator does not listen for `namespace` events.

### PR DESCRIPTION
**Pull request by simonpasquier**
## Description
When the operator was configured to select only a limited number of
namespaces, it would not watch for namespace changes. It means that the
operator may not reconcile when a namespace label is added/removed
(affecting which objects should be selected or not).

This change enables the operator to use a privileged namespace
lister/watcher whenever the service account has the needed permissions.

**IMPORTANT:** it also requires Kubernetes >= 1.22 to be effective but the
operator will degrade to the less efficient implementation if this condition isn't met.

xref #3847 (one more PR required to fix it completely).

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [X] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Reconcile monitoring resources on namespace updates.
```

### CODE REVIEW

File: test/e2e/prometheus_instance_namespaces_test.go [hunk 1]
```diff
@@ -302,11 +331,11 @@ func testPrometheusInstanceNamespacesAllowList(t *testing.T) {
 		// Remove the selecting label on the "allowed" namespace and check that
 		// the target is removed.
 		// See https://github.com/prometheus-operator/prometheus-operator/issues/3847
-		//if err := testFramework.RemoveLabelsFromNamespace(framework.KubeClient, allowedNs, "monitored"); err != nil {
+		//if err := framework.RemoveLabelsFromNamespace(context.Background(), allowedNs, "monitored"); err != nil {
```
Comment (simonpasquier) [inline test/e2e/prometheus_instance_namespaces_test.go:334]: this part is still commented because the service account isn't configured with list/watch permissions on namespaces. I have another change in flight that would fix it by implementing a poller based watcher but to keep this PR reviewable, I'll send as a follow-up.

File: cmd/operator/main.go [hunk 2]
```diff
@@ -303,6 +303,15 @@ func run() int {
 		return 1
 	}
 
+	kubernetesVersion, err := kclient.Discovery().ServerVersion()
```
Comment (simonpasquier) [inline cmd/operator/main.go:306]: Instead of repeating the same check in each controller, let's do it once on startup.

File: test/e2e/prometheus_instance_namespaces_test.go (hunk 1 above)
Comment (simonpasquier) [reply test/e2e/prometheus_instance_namespaces_test.go:334]: https://github.com/prometheus-operator/prometheus-operator/pull/5925/commits/5ada40db1508fdb128fbd558c52bc10a1f92a33f

File: pkg/listwatch/listwatch.go [hunk 3]
```diff
@@ -44,56 +50,144 @@ import (
...
 		}
+		if metadataNameLabelSupported {
+			// Using a label selector is more efficient but requires Kubernetes 1.22 at least.
+			tweak = func(options *metav1.ListOptions) {
+				TweakByLabel(options, "kubernetes.io/metadata.name", ExcludeFilterType, deniedNamespaces)
+			}
+		}
 
-		return cache.NewFilteredListWatchFromClient(c, "namespaces", metav1.NamespaceAll, tweak)
+		level.Debug(l).Log("msg", "using privileged namespace lister/watcher")
```
Comment (ArthurSens) [inline pkg/listwatch/listwatch.go:108]: this debug log seems out of place 🤔

File: pkg/listwatch/listwatch.go [hunk 4]
```diff
@@ -44,56 +50,144 @@ import (
...
-				Resource("namespaces").
-				Name(name).
-				VersionedParams(&options, scheme.ParameterCodec).
-				Do(ctx).
-				Into(result)
-			if apierrors.IsNotFound(err) {
-				level.Info(l).Log("msg", "namespace not found", "namespace", name)
-				continue
-			}
+			result, err := corev1Client.Namespaces().Get(ctx, name, metav1.GetOptions{})
```
Comment (ArthurSens) [inline pkg/listwatch/listwatch.go:164]: Should we put this inside an if?

```go
if getAllowed {
  result, err := corev1Client.Namespaces().Get(ctx, name, metav1.GetOptions{})
  .
  .
  .
}
```

File: pkg/listwatch/listwatch.go [hunk 5]
```diff
@@ -44,56 +50,144 @@ import (
...
+	if !getAllowed {
+		err := fmt.Errorf("missing permissions")
+		for _, r := range reasons {
+			err = fmt.Errorf("%w: %w", err, r)
+		}
+
+		level.Warn(l).Log("msg", "the operator lacks required permissions which may result in degraded functionalities", "err", err)
 	}
 
 	listFunc := func(options metav1.ListOptions) (runtime.Object, error) {
```
Comment (ArthurSens) [inline pkg/listwatch/listwatch.go:161]:
```suggestion
	listFunc := func(_ metav1.ListOptions) (runtime.Object, error) {
```

Is it intended to not use the options provided here?

**Review by ArthurSens — COMMENTED** [review]
Sorry for taking this long to review, the subject here is a bit out of my comfort zone 😬 I'm still going through the codebase and trying to understand everything. 

A few doubts came up while reading the PR

File: pkg/listwatch/listwatch.go (hunk 3 above)
Comment (simonpasquier) [reply pkg/listwatch/listwatch.go:108]: hmm not sure to understand but I can remove all the "using (un)privileged namespace lister/watcher" debug logs as they were more for me to check the code path.

File: pkg/listwatch/listwatch.go (hunk 5 above)
Comment (simonpasquier) [reply pkg/listwatch/listwatch.go:161]: yes it's intended and the PR didn't change anything in that regard.

File: pkg/listwatch/listwatch.go (hunk 4 above)
Comment (simonpasquier) [reply pkg/listwatch/listwatch.go:164]: I kept the existing behavior to minimize the changes. The SA might have get permissions on a subset of the configured namespaces but getAllowed will be false.

**Review by simonpasquier — COMMENTED** [review]
Thanks for the review @ArthurSens. I understand that the change isn't easy to review, fortunately we have quite good e2e test coverage which helped me find bugs in the first iterations :)

**Comment by simonpasquier** [comment]
@ArthurSens in case you missed my earlier comment: https://github.com/prometheus-operator/prometheus-operator/commit/5ada40db1508fdb128fbd558c52bc10a1f92a33f is the next step but I didn't want to increase the scope of this PR even more.

File: pkg/listwatch/listwatch.go (hunk 3 above)
Comment (ArthurSens) [reply pkg/listwatch/listwatch.go:108]: It's fine to keep it! I missed the return literally in the next line and thought you left duplicated logs 😅

File: test/e2e/alertmanager_instance_namespaces_test.go [hunk 6]
```diff
@@ -45,18 +45,28 @@ func testAlertmanagerInstanceNamespacesAllNs(t *testing.T) {
...
 
-	am := framework.MakeBasicAlertmanager(nonInstanceNs, "non-instance", 3)
+	am := framework.MakeBasicAlertmanager(nonInstanceNs, "non-instance", 2)
 	_, err = framework.MonClientV1.Alertmanagers(nonInstanceNs).Create(context.Background(), am, metav1.CreateOptions{})
 	if err != nil {
 		t.Fatal(err)
 	}
 
-	am = framework.MakeBasicAlertmanager(instanceNs, "instance", 3)
+	am = framework.MakeBasicAlertmanager(instanceNs, "instance", 2)
```
Comment (ArthurSens) [inline test/e2e/alertmanager_instance_namespaces_test.go:69]: Any special reason to reduce the number of replicas?

I assume it is just because the test is valid for both 3 or 2 replicas and 2 replicas is just faster, but I wanted to ask anyway

**Review by ArthurSens — APPROVED** [review]
Alright, LGTM!

Thanks for working on this, reviewing it also helped me understand better what kubebuilder usually abstracts away from other projects I work with :P

**Comment by ArthurSens** [comment]
> @ArthurSens in case you missed my earlier comment: [5ada40d](https://github.com/prometheus-operator/prometheus-operator/commit/5ada40db1508fdb128fbd558c52bc10a1f92a33f) is the next step but I didn't want to increase the scope of this PR even more.

Just saw it and looks 👌 !

File: test/e2e/alertmanager_instance_namespaces_test.go (hunk 6 above)
Comment (simonpasquier) [reply test/e2e/alertmanager_instance_namespaces_test.go:69]: yes, the test doesn't care if it's 3, 2 or 1 replicas. But I'll revert it to avoid unrelated changes. We can have a look at all e2e tests globally and decide whether they really need multi replicas: in most cases, I think that the answer is no and switching to single replicas might save a few resources.
