### PR TITLE
fix: give an error message for invalid probe.spec.target

### LINKED ISSUE #4540: prometheus-operator crashed with an invalid Probe
**What happened?**

I submit an invalid `Probe` wihtout `target` onto the kubernetes:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    release: kube-prometheus-stack
  name: exporter-giu
  namespace: monitoring
spec:
  interval: "15s"
  jobName: "node-exporter-giu"
  prober:
    url: "http://giu:9100/metrics"
```

**Did you expect to see something different?**

Warning message printed on `opertaor` Pod. Or webhook could reject this object.

**How to reproduce it (as minimally and precisely as possible)**:

Apply pinned `Probe` resource.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

`quay.io/prometheus-operator/prometheus-operator:v0.52.1`

I think it could also occur with `master`.

* Kubernetes version information:

    `kubectl version`
    

```
$ kubectl version                                                         
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.
	On-premises Kubernetes cluster with kubeadm.

* Manifests:

	Has been pinned above.

* Prometheus Operator Logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x178acd7]

goroutine 209 [running]:
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Operator).selectProbes.func2(0xc0002b4fc0, {0x0, 0x0})
        /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/operator.go:1963 +0xb7
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Operator).selectProbes(0xc000600800, {0x1fba350, 0xc00005d5c0}, 0xc0005b2b00, 0x453000)
        /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/operator.go:1970 +0xbc6
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Operator).createOrUpdateConfigurationSecret(0xc000600800, {0x1fba350, 0xc00005d5c0}, 0xc0005b2b00, {0xc001b522b0, 0x1, 0x1}, 0x0)
        /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/operator.go:1525 +0x112
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Operator).sync(0xc000600800, {0x1fba350, 0xc00005d5c0}, {0xc000b5e120, 0x2b})
        /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/operator.go:1229 +0x69f
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Operator).processNextWorkItem(0xc000600800, {0x1fba350, 0xc00005d5c0})
        /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/operator.go:1038 +0x145
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Operator).worker(0x0, {0x1fba350, 0xc00005d5c0})
        /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/operator.go:1026 +0x39
created by github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Operator).Run
        /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/operator.go:435 +0x30f
```

**Anything else we need to know?**:

Related codes: 

https://github.com/prometheus-operator/prometheus-operator/blob/49c876c2aec26dd46246be0b3f6d003cbdaa0b80/pkg/prometheus/operator.go#L2036-L2039

I think I could make a PR to fix that.

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Fix #4540:

- give a valid error, avoid panic
- ~~appending validation webhook for `Probe`~~ (I found maybe this is unnecessary)

I am still confused that what do many `Validate()` in `pkg/apis/monitoring/v1/types.go` tends for, it seems nowhere (I use "find usage" with IDE) to use it.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
[BUGFIX]: Avoid panic when validating `Probe`
```

### CODE REVIEW

File: pkg/prometheus/operator.go [hunk 1]
```diff
@@ -2034,7 +2034,7 @@ func (c *Operator) selectProbes(ctx context.Context, p *monitoringv1.Prometheus,
 			)
 		}
 		if probe.Spec.Targets.StaticConfig == nil && probe.Spec.Targets.Ingress == nil {
```
Comment (fpetkovski) [inline pkg/prometheus/operator.go:2036]: I believe the panic is introduced when `probe.Spec.Targets` is nil. Can we make sure we handle that case as well?

Comment (STRRL) [reply pkg/prometheus/operator.go:2036]: It uses struct instead of a pointer, it would not be `nil`. :D

https://github.com/prometheus-operator/prometheus-operator/blob/dea9a44e53e41ae2ef92d72d7f44eaa6dbe31f32/pkg/apis/monitoring/v1/types.go#L1084

Comment (fpetkovski) [reply pkg/prometheus/operator.go:2036]: Ah, you're right. We return a nil error in this case! Would you mind just adding a unit test to go with the bugfix?

Comment (STRRL) [reply pkg/prometheus/operator.go:2036]: > Ah, you're right. We return a nil error in this case! Would you mind just adding a unit test to go with the bugfix?

It's hard to add unit tests for `selectProbes()` I think I would extract these lines as a function and make unit test for it.

Comment (STRRL) [reply pkg/prometheus/operator.go]: Updated! PTAL! :heart:

Comment (fpetkovski) [reply pkg/prometheus/operator.go]: Looks great :+1: I would just move the validation function to the probe itself, similar to how we do it for the other types: https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/apis/monitoring/v1/types.go#L1194

Wdyt?

Comment (STRRL) [reply pkg/prometheus/operator.go]: > Looks great +1 I would just move the validation function to the probe itself, similar to how we do it for the other types: [`main`/pkg/apis/monitoring/v1/types.go#L1194](https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/apis/monitoring/v1/types.go?rgh-link-date=2022-01-31T11%3A12%3A31Z#L1194)
> 
> Wdyt?

Updated! PTAL! :D

**Review by fpetkovski — APPROVED** [review]
Thanks!

File: pkg/apis/monitoring/v1/types.go [hunk 2]
```diff
@@ -1127,6 +1127,26 @@ type ProbeTargets struct {
...
+// Validate semantically validates the given ProbeTargets.
+func (it *ProbeTargets) Validate() error {
+	if it.StaticConfig == nil && it.Ingress == nil {
+		return &ProbeTargetsValidationError{"at least one of .spec.target.staticConfig and .spec.target.ingress is required"}
+	}
+
+	return nil
+}
+
+// ProbeTargetsValidationError is returned by SecretOrConfigMap.Validate()
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/types.go:1139]:
```suggestion
// ProbeTargetsValidationError is returned by ProbeTargets.Validate()
```

**Review by simonpasquier — APPROVED** [review]

**Comment by simonpasquier** [comment]
Thanks!
