### PR TITLE
ScrapeConfig CRD: refactor ProxyConfig struct embedding

### LINKED ISSUE #6400: embedded ProxyConfig in the API is not reflected by gen-crd-api-reference-docs.
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
ProxyConfig fields are not included in the ScrapeConfigSpec, HTTPSDConfig, KubernetesSDConfig, ConsulSDConfig and DigitalOceanSDConfig API definitions in the documentation.

This was already discussed in #6144. The approach suggested was to migrate to [elastic/crd-ref-docs](https://github.com/elastic/crd-ref-docs) for doc generation.

After trying [elastic/crd-ref-docs](https://github.com/elastic/crd-ref-docs), The issue was not solved. It turned out that both [gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs) and [elastic/crd-ref-docs](https://github.com/elastic/crd-ref-docs) support embedded structs but not embedded pointers to structs as in the case of ProxyConfig.

One way to solve this is to refactor the struct embedding of ProxyConfig from `*v1.ProxyConfig` to `v1.ProxyConfig` and the issue will be solved without any need to migrate to a new doc generation tool.
## Steps to Reproduce
see [HTTPSDConfig API documentation](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.HTTPSDConfig)
## Expected Result
ProxyConfig fields are expected to be listed under ScrapeConfigSpec, HTTPSDConfig, KubernetesSDConfig, ConsulSDConfig and DigitalOceanSDConfig API definitions in the documentation.
## Actual Result
ProxyConfig fields are not listed under ScrapeConfigSpec, HTTPSDConfig, KubernetesSDConfig, ConsulSDConfig and DigitalOceanSDConfig API definitions in the documentation.

### Prometheus Operator Version

```shell
0.72.0
```

### Kubernetes Version

```yaml
not needed
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

_No response_

### prometheus-operator log output

```shell
not needed
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mouad-eh**
## Description

fixes #6400 by refactoring struct embedding of ProxyConfig from *v1.ProxyConfig to v1.ProxyConfig without any migration of the documentation generation tool.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification
unit test only.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
ProxyConfig fields are now reflected in the ScrapeConfigSpec, HTTPSDConfig, KubernetesSDConfig, ConsulSDConfig and DigitalOceanSDConfig API definitions in the documentation.
```

### CODE REVIEW

File: pkg/prometheus/resource_selector.go [hunk 1]
```diff
@@ -850,8 +850,8 @@ func (rs *ResourceSelector) validateKubernetesSDConfigs(ctx context.Context, sc
 			return fmt.Errorf("[%d]: %w", i, err)
 		}
 
-		if config.ProxyConfig != nil {
-			if err := validateProxyConfig(ctx, config.ProxyConfig, rs.store, sc.GetNamespace()); err != nil {
+		if !monitoringv1.IsProxyConfigEqualToZero(config.ProxyConfig) {
```
Comment (nicolastakashi) [inline pkg/prometheus/resource_selector.go:853]: (nit) I'm not against this abstraction, i think it might improve redability, but I would prefer if we move the negative operation to inside the function and maybe call this as `IsProxyConfigNotEqualToZero`

**Comment by mouad-eh** [comment]
@nicolastakashi thanks for the feedback. I updated the code, you can check it now.

File: pkg/apis/monitoring/v1/types.go [hunk 2]
```diff
@@ -104,6 +105,10 @@ type ProxyConfig struct {
 	ProxyConnectHeader map[string]v1.SecretKeySelector `json:"proxyConnectHeader,omitempty"`
 }
 
+func IsProxyConfigNotEqualToZero(pc ProxyConfig) bool {
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/types.go:108]: I'm not a fan of including utility functions in the pkg/apis/monitoring module. I think that it could live in pkg/prometheus. But we could as well use reflect.ValueOf(proxyConfig).IsZero() directly (which would be more expressive IMHO).

File: pkg/prometheus/promcfg.go [hunk 3]
```diff
@@ -2503,7 +2503,7 @@ func (cg *ConfigGenerator) generateScrapeConfig(
 		cfg = append(cfg, yaml.MapItem{Key: "scheme", Value: strings.ToLower(*sc.Spec.Scheme)})
 	}
 
-	cfg = cg.addProxyConfigtoYaml(ctx, cfg, sc.GetNamespace(), store, sc.Spec.ProxyConfig)
+	cfg = cg.addProxyConfigtoYaml(ctx, cfg, sc.GetNamespace(), store, &sc.Spec.ProxyConfig)
```
Comment (simonpasquier) [inline pkg/prometheus/promcfg.go:2506]: (suggestion) let's pass the value directly instead of the pointer and  addProxyConfigtoYaml() can check if it's zero or not.
```suggestion
	cfg = cg.addProxyConfigtoYaml(ctx, cfg, sc.GetNamespace(), store, sc.Spec.ProxyConfig)
```

File: pkg/prometheus/resource_selector.go [hunk 4]
```diff
@@ -762,8 +762,8 @@ func (rs *ResourceSelector) SelectScrapeConfigs(ctx context.Context, listFn List
 			rejectFn(sc, err)
 			continue
 		}
-		if sc.Spec.ProxyConfig != nil {
-			if err = validateProxyConfig(ctx, sc.Spec.ProxyConfig, rs.store, sc.GetNamespace()); err != nil {
+		if monitoringv1.IsProxyConfigNotEqualToZero(sc.Spec.ProxyConfig) {
+			if err = validateProxyConfig(ctx, &sc.Spec.ProxyConfig, rs.store, sc.GetNamespace()); err != nil {
```
Comment (simonpasquier) [inline pkg/prometheus/resource_selector.go:766]: (suggestion) same remark: validateProxyConfig() can receive the value instead of the pointer and check the zero value directly.

**Review by simonpasquier — COMMENTED** [review]
Thanks for the investigation!

**Review by simonpasquier — APPROVED** [review]
Thanks! The CI failure was a glitch from GH actions I believe.
