### PR TITLE
config-reloader: add init-config-reloader to alertmanager

### LINKED ISSUE #5357: Add `init-config-reloader` to alertmanager
**What is missing?**

There is no `init-config-reloader` init container in alertmanager statefulset like in prometheus. So when an alertmanager pod is created, `alertmanager` container tries to load config when config is not yet rendered.

**Why do we need it?**

Alertmanager exits with exit code 1 in "expected situation" (it doesn't really fail anything). And it also may trigger monitoring alerts if container exits are monitored.

**Environment**

* Prometheus Operator version:

    `v0.62.0`
    
    

**Anything else we need to know?**:

Links to `init-config-reloader` for prometheus: #3061 #3955

Logs during first run of alertmanager container:

```
{"caller":"main.go:240","level":"info","msg":"Starting Alertmanager","ts":"2023-02-12T22:52:20.809Z","version":"(version=0.25.0, branch=HEAD, revision=258fab7cdd551f2cf251ed0348f0ad7289aee789)"}
{"build_context":"(go=go1.19.4, user=root@abe866dd5717, date=20221222-14:51:36)","caller":"main.go:241","level":"info","ts":"2023-02-12T22:52:20.809Z"}
{"caller":"cluster.go:681","component":"cluster","interval":"2s","level":"info","msg":"Waiting for gossip to settle...","ts":"2023-02-12T22:52:20.848Z"}
{"caller":"coordinator.go:113","component":"configuration","file":"/etc/alertmanager/config_out/alertmanager.env.yaml","level":"info","msg":"Loading configuration file","ts":"2023-02-12T22:52:20.939Z"}
{"caller":"coordinator.go:118","component":"configuration","err":"open /etc/alertmanager/config_out/alertmanager.env.yaml: no such file or directory","file":"/etc/alertmanager/config_out/alertmanager.env.yaml","level":"error","msg":"Loading configuration file failed","ts":"2023-02-12T22:52:20.939Z"}
{"caller":"cluster.go:690","component":"cluster","elapsed":"91.081547ms","level":"info","msg":"gossip not settled but continuing anyway","polls":0,"ts":"2023-02-12T22:52:20.939Z"}
```

### PR DESCRIPTION
**Pull request by r3nic1e**
## Description

This PR reuses the same approach used for prometheus statefulset that adds `init-config-reloader` initContainer to alertmanager statefulset - #3955.
Effectively `init-config-reloader` will pregenerate the alertmanager config so `alertmanager` won't fail due to missing config.

Fixes #5357

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
- Generate Alertmanager config before starting Alertmanager container
```

### CODE REVIEW

File: pkg/alertmanager/statefulset.go [hunk 1]
```diff
@@ -715,6 +717,27 @@ func makeStatefulSetSpec(a *monitoringv1.Alertmanager, config Config, tlsAssetSe
...
+	operatorInitContainers = append(operatorInitContainers,
+		operator.CreateConfigReloader(
+			"init-config-reloader",
+			operator.ReloaderConfig(config.ReloaderConfig),
+			operator.ReloaderRunOnce(),
+			operator.LogFormat(a.Spec.LogFormat),
+			operator.LogLevel(a.Spec.LogLevel),
+			operator.WatchedDirectories(watchedDirectories),
+			operator.VolumeMounts(configReloaderVolumeMounts),
+			operator.Shard(-1),
```
Comment (simonpasquier) [inline pkg/alertmanager/statefulset.go:729]: This isn't needed for Alertmanager but I see that you've copied it from the existing reloader config container so it can be cleaned up in a following PR as well.
```suggestion
```

**Review by simonpasquier — APPROVED** [review]
Thanks!

File: pkg/alertmanager/statefulset.go (hunk 1 above)
Comment (r3nic1e) [reply pkg/alertmanager/statefulset.go:729]: Yeah, thought about that. Just wanted to keep as close to the sidecar reloader config as possible
