### PR TITLE
fix: enable remote-write for Ruler only when set

### LINKED ISSUE #7492: ThanosRuler default remote-write config is causing recording rules to fail
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Description

After upgrade to kube-prometheus-stack 71.0.0 (prometheus-operator 0.82), our recording rules started failing. Thanos-ruler does not announce any replica label sets (according to thanos-query), and queries for the recorded metric return an empty value.

## Steps to Reproduce

Example recording rule:

```yaml
groups:
- name: hive.hpa.recording
  interval: 15s
  rules:
  - record: re_worker_ws_connections_total
    expr: sum(remote_peers_peers_sessions_connected) by (namespace,service)
```

kube-prometheus-stack 70.10.0 (prometheus-operator 0.81.0) works; upgrading to 71.0.0 (prometheus-operator 0.82.0) causes the recording rule (or querying the metric) to fail.

I narrowed this down to the `--remote-write.config-file=/etc/thanos/config/remote-write-config/remote-write.yaml` argument. The contents of `remote-write.yaml`:

```yaml
remote-write.yaml: |
  remote_write: []
```

If I disable prometheus-operator temporarily, and manually edit the thanos-ruler StatefulSet to remove the `--remote-write.config-file` argument, the recording rule metric starts working again.

## Expected Result

Queries for `re_worker_ws_connections_total` return a value.

## Actual Result

Queries for `re_worker_ws_connections_total` return an empty value.

### Prometheus Operator Version

```shell
Name:                   promstack-operator
Namespace:              monitoring
CreationTimestamp:      Thu, 12 Dec 2024 00:17:56 +0100
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/component=prometheus-operator
                        app.kubernetes.io/instance=monitoring
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=71.0.0
                        chart=kube-prometheus-stack-71.0.0
                        heritage=Helm
                        release=monitoring
Annotations:            deployment.kubernetes.io/revision: 16
                        meta.helm.sh/release-name: monitoring
                        meta.helm.sh/release-namespace: monitoring
Selector:               app=kube-prometheus-stack-operator,release=monitoring
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/component=prometheus-operator
                    app.kubernetes.io/instance=monitoring
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=71.0.0
                    chart=kube-prometheus-stack-71.0.0
                    heritage=Helm
                    release=monitoring
  Service Account:  promstack-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.82.0
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/promstack-kubelet
      --kubelet-endpoints=true
      --kubelet-endpointslice=false
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.82.0
      --config-reloader-cpu-request=0
      --config-reloader-cpu-limit=0
      --config-reloader-memory-request=0
      --config-reloader-memory-limit=0
      --thanos-default-base-image=quay.io/thanos/thanos:v0.38.0
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS13
    Limits:
      cpu:     1
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   64Mi
    Liveness:   http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GOGC:  30
    Mounts:
      /cert from tls-secret (ro)
  Volumes:
   tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  promstack-admission
    Optional:    false
```

### Kubernetes Version

```yaml
Client Version: v1.29.11
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.11
```

### Kubernetes Cluster Type

AKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml

```

### prometheus-operator log output

```shell
ts=2025-04-29T06:23:58.518603412Z level=info caller=/workspace/cmd/operator/main.go:214 msg="Starting Prometheus Operator" version="(version=0.82.0, branch=, revision=d6f3c91)" build_context="(go=go1.24.1, platform=linux/amd64, user=, date=20250417-10:00:43, tags=unknown)" feature_gates="Promet>
ts=2025-04-29T06:23:58.518920218Z level=info caller=/workspace/internal/goruntime/cpu.go:27 msg="Updating GOMAXPROCS=1: determined from CPU quota"
ts=2025-04-29T06:23:58.519266724Z level=info caller=/workspace/cmd/operator/main.go:227 msg="namespaces filtering configuration " config="{allow_list=\"\",deny_list=\"\",prometheus_allow_list=\"\",alertmanager_allow_list=\"\",alertmanagerconfig_allow_list=\"\",thanosruler_allow_list=\"\"}"
ts=2025-04-29T06:23:59.455971745Z level=info caller=/workspace/cmd/operator/main.go:268 msg="connection established" kubernetes_version=1.30.11
ts=2025-04-29T06:23:59.545352831Z level=info caller=/workspace/cmd/operator/main.go:353 msg="Kubernetes API capabilities" endpointslices=true
ts=2025-04-29T06:23:59.775819821Z level=warn caller=/workspace/pkg/server/server.go:164 msg="server TLS client verification disabled" client_ca_file=/etc/tls/private/tls-ca.crt err="stat /etc/tls/private/tls-ca.crt: no such file or directory"
ts=2025-04-29T06:23:59.776416432Z level=info caller=/workspace/pkg/server/server.go:301 msg="starting secure server" address=[::]:10250 http2=false
ts=2025-04-29T06:23:59.776489033Z level=info caller=/go/pkg/mod/k8s.io/apiserver@v0.32.3/pkg/server/dynamiccertificates/tlsconfig.go:243 msg="Starting DynamicServingCertificateController"
ts=2025-04-29T06:23:59.776623535Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.776662636Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.776701137Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for alertmanager"
ts=2025-04-29T06:23:59.776739537Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for thanos"
ts=2025-04-29T06:23:59.776759138Z level=info caller=/workspace/pkg/kubelet/controller.go:207 msg="Starting controller" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet
ts=2025-04-29T06:23:59.776970441Z level=info caller=/go/pkg/mod/k8s.io/apiserver@v0.32.3/pkg/server/dynamiccertificates/dynamic_serving_content.go:135 msg="Starting controller" name=servingCert::/cert/cert::/cert/key
ts=2025-04-29T06:23:59.880268774Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.880316375Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.880325975Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.880337076Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.880344476Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.880353876Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.880360876Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.880370576Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.880380376Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.880389777Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.880407977Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.880421077Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.880428277Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.880440077Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.880448178Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.880457778Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.880464678Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.880476078Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.977375698Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for alertmanager"
ts=2025-04-29T06:23:59.977419598Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for alertmanager"
ts=2025-04-29T06:23:59.977429098Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for alertmanager"
ts=2025-04-29T06:23:59.977440399Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for alertmanager"
ts=2025-04-29T06:23:59.977447699Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for alertmanager"
ts=2025-04-29T06:23:59.977462199Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for alertmanager"
ts=2025-04-29T06:23:59.977469799Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for alertmanager"
ts=2025-04-29T06:23:59.977481499Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for alertmanager"
ts=2025-04-29T06:23:59.9774893Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for alertmanager"
ts=2025-04-29T06:23:59.9775Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for alertmanager"
ts=2025-04-29T06:23:59.9775072Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for alertmanager"
ts=2025-04-29T06:23:59.9775143Z level=info caller=/workspace/pkg/alertmanager/operator.go:327 msg="successfully synced all caches" component=alertmanager-controller
ts=2025-04-29T06:23:59.97805991Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T06:23:59.980749157Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.980783358Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.980792558Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.980802958Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.980811259Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.980821359Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.980830359Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.980840359Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.980864059Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.98088056Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheusagent"
ts=2025-04-29T06:23:59.98089136Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheusagent"
ts=2025-04-29T06:23:59.98089976Z level=info caller=/workspace/pkg/prometheus/agent/operator.go:470 msg="successfully synced all caches" component=prometheusagent-controller
ts=2025-04-29T06:23:59.981146564Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.981169665Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.981179165Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.981193465Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.981209966Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.981231066Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.981248966Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.981268267Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.981283067Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.981294367Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for prometheus"
ts=2025-04-29T06:23:59.981301067Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for prometheus"
ts=2025-04-29T06:23:59.981307767Z level=info caller=/workspace/pkg/prometheus/server/operator.go:419 msg="successfully synced all caches" component=prometheus-controller
ts=2025-04-29T06:23:59.996243232Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:00.177781654Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for thanos"
ts=2025-04-29T06:24:00.177940557Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for thanos"
ts=2025-04-29T06:24:00.177955657Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for thanos"
ts=2025-04-29T06:24:00.177972157Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for thanos"
ts=2025-04-29T06:24:00.177984357Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for thanos"
ts=2025-04-29T06:24:00.178022258Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for thanos"
ts=2025-04-29T06:24:00.178037658Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for thanos"
ts=2025-04-29T06:24:00.178056359Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for thanos"
ts=2025-04-29T06:24:00.178070659Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for thanos"
ts=2025-04-29T06:24:00.178090459Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:313 msg="Waiting for caches to sync for thanos"
ts=2025-04-29T06:24:00.178103959Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/shared_informer.go:320 msg="Caches are synced for thanos"
ts=2025-04-29T06:24:00.17811666Z level=info caller=/workspace/pkg/thanos/operator.go:304 msg="successfully synced all caches" component=thanos-controller
ts=2025-04-29T06:24:00.178606368Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:00.449988884Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T06:24:00.558093902Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:00.787502551Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T06:24:00.873451561Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:00.916971978Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:01.325837091Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:01.836583951Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:03.505628211Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:03.529095306Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:05.663774775Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:05.668346072Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:07.774776368Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:07.793647584Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:09.900758326Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:09.906434487Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:12.0182548Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:12.021877665Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:14.145439456Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:14.149339226Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:16.26138831Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:16.267989029Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:18.394458686Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:18.398071752Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:20.521830783Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:20.526280164Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:22.664538458Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:22.667566713Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:24.755227688Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:24.773835985Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:26.859425451Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:26.894716329Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:28.994497687Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:29.003756912Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:31.103590094Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:31.12479697Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:33.235805283Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:33.239733041Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:35.395893271Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:35.399983431Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:37.524800703Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:37.546275117Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:39.661711952Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:39.666713325Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:41.791656958Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:41.814887223Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:43.913272609Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:43.917642797Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:46.022474212Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:46.044846659Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:48.153585073Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:48.157751545Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:50.291223254Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:50.294566512Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:52.421200688Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:52.427385796Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:54.561858508Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:54.578325395Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:56.720182736Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:56.73934937Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:24:58.860583091Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:24:58.865799474Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:25:00.972855167Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:25:00.978221152Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:25:03.206289168Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:25:03.215293512Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:25:07.735392474Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:25:07.927945973Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:25:08.128658212Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T06:25:08.750794671Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T06:25:09.078490985Z level=info caller=/workspace/pkg/thanos/operator.go:466 msg="sync thanos-ruler" component=thanos-controller key=monitoring/promstack-thanos-ruler
ts=2025-04-29T08:57:15.247605441Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T08:57:15.259522643Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T09:00:16.053610088Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T09:00:16.060607519Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T09:00:16.20423822Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T09:00:16.275426259Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T09:00:56.763109835Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T09:00:56.770587231Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T09:00:56.916747311Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T09:00:56.943870459Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T15:13:59.53142324Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T15:13:59.538559566Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T15:15:34.715743701Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T15:15:34.72242241Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T15:15:34.863045224Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-29T15:15:34.907960163Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-29T15:38:59.880098529Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tn
ts=2025-04-29T20:14:59.863718683Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tc
ts=2025-04-29T20:14:59.863784184Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001te
ts=2025-04-29T20:14:59.863792184Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001th
ts=2025-04-29T20:14:59.863799584Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tk
ts=2025-04-29T20:17:59.850674681Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tc
ts=2025-04-29T20:17:59.850725282Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001td
ts=2025-04-29T20:17:59.850732882Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001te
ts=2025-04-29T20:17:59.850738082Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001th
ts=2025-04-29T20:17:59.850742882Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tk
ts=2025-04-29T20:20:59.857869543Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tc
ts=2025-04-29T20:20:59.857918844Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001td
ts=2025-04-29T20:20:59.857925844Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001te
ts=2025-04-29T20:20:59.857933144Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001th
ts=2025-04-29T20:20:59.857941444Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tk
ts=2025-04-30T06:15:21.109982902Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-30T06:15:21.115947695Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-30T09:21:29.327445584Z level=info caller=/workspace/pkg/alertmanager/operator.go:546 msg="sync alertmanager" component=alertmanager-controller key=monitoring/promstack-alertmanager
ts=2025-04-30T09:21:29.333112367Z level=info caller=/workspace/pkg/prometheus/server/operator.go:768 msg="sync prometheus" component=prometheus-controller key=monitoring/promstack-prometheus
ts=2025-04-30T20:11:59.847334658Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001ts
ts=2025-04-30T20:11:59.847401859Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tx
ts=2025-04-30T20:14:59.862723749Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tt
ts=2025-04-30T20:17:59.855746834Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tt
ts=2025-04-30T20:17:59.855795835Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tv
ts=2025-04-30T20:20:59.854019197Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tt
ts=2025-04-30T20:20:59.854089798Z level=info caller=/workspace/pkg/kubelet/controller.go:337 msg="Node Ready condition is Unknown" component=kubelet_endpoints kubelet_object=kube-system/promstack-kubelet node=aks-general-12000105-vmss0001tv
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by simonpasquier**
## Description

Closes #7492

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [X] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

File: pkg/thanos/statefulset.go [hunk 1]
```diff
@@ -220,6 +220,7 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
 		},
 		"remote-write-config",
 	)
+	//if version.GTE(minRemoteWriteVersion) && len(tr.Spec.RemoteWrite) > 0 {
```
Comment (nicolastakashi) [inline pkg/thanos/statefulset.go:223]: should we remove it?

Comment (simonpasquier) [reply pkg/thanos/statefulset.go:223]: I'll update after I confirmed that the new e2e test fails without it :)

**Comment by simonpasquier** [comment]
This will need https://github.com/prometheus-operator/prometheus-operator/pull/7500 first to unblock the CI.

**Review by slashpai — APPROVED** [review]
