### PR TITLE
thanos: add support for web configuration to the ThanosRuler CRD

### LINKED ISSUE #6157: Add support for web configuration to the ThanosRuler CRD
**What is missing?**

As the ThanosRuler CRD doesn't allow the configuration of TLS for the Web Server at the moment, we were trying to use the additionalArgs to specify the http.config flag with a configuration that points to the TLS certificates.

While this works, the config-reloader breaks, as it's still using --reload-url=http://127.0.0.1:10902/-/reload, which returns:

level=error ts=2023-12-11T09:45:54.090853004Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 400 Bad Request; have you set `--web.enable-lifecycle` Prometheus flag?"

This appears to be fixed if we edit the statefulset manually and set the reload-url to https instead, but that change is reverted by the operator.

**Why do we need it?**

As the operator currently doesn't have any option to configure TLS on the Web UI port of ThanosRuler, it would be useful to be able to override the reload-url, so we can configure TLS using additionalArgs with the http.config option of thanos-ruler.

### PR DESCRIPTION
**Pull request by jamshidi799**
This enables us to set TLS for ThanosRuler

Fixes #6157

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
add support for web configuration to the ThanosRuler CRD
```

### CODE REVIEW

**Comment by slashpai** [comment]
Looks like you missed to generate and format code, can you run `make --always-make format generate`

**Comment by jamshidi799** [comment]
should I change something? Is everything ok?

File: pkg/thanos/operator.go [hunk 1]
```diff
@@ -17,6 +17,8 @@ package thanos
 import (
 	"context"
 	"fmt"
+	"github.com/prometheus-operator/prometheus-operator/pkg/assets"
+	"github.com/prometheus-operator/prometheus-operator/pkg/webconfig"
```
Comment (simonpasquier) [inline pkg/thanos/operator.go:21]: the `github.com/prometheus-operator/prometheus-operator/...`  imports need to go with their siblings.

File: pkg/thanos/operator.go [hunk 2]
```diff
@@ -547,6 +549,17 @@ func (o *Operator) sync(ctx context.Context, key string) error {
...
 
+	assetStore := assets.NewStore(o.kclient.CoreV1(), o.kclient.CoreV1())
+
+	tlsAssets, err := operator.ReconcileShardedSecretForTLSAssets(ctx, assetStore, o.kclient, newTLSAssetSecret(tr, o.config))
+	if err != nil {
+		return fmt.Errorf("failed to reconcile the TLS secrets: %w", err)
+	}
+
+	if err := o.createOrUpdateWebConfigSecret(ctx, tr); err != nil {
+		return fmt.Errorf("synchronizing web config secret failed: %w", err)
```
Comment (simonpasquier) [inline pkg/thanos/operator.go:560]: (nit)
```suggestion
		return fmt.Errorf("failed to synchronize web config secret: %w", err)
```

File: pkg/thanos/operator.go [hunk 3]
```diff
@@ -795,6 +810,36 @@ func (o *Operator) enqueueForNamespace(store cache.Store, nsName string) {
...
+	s := &v1.Secret{}
+	operator.UpdateObject(
+		s,
+		operator.WithLabels(o.config.Labels),
+		operator.WithAnnotations(o.config.Annotations),
+		operator.WithManagingOwner(tr),
+	)
+
+	if err := webConfig.CreateOrUpdateWebConfigSecret(ctx, o.kclient.CoreV1().Secrets(tr.Namespace), s); err != nil {
+		return fmt.Errorf("failed to reconcile web config secret: %w", err)
```
Comment (simonpasquier) [inline pkg/thanos/operator.go:837]: (nit)
```suggestion
		return fmt.Errorf("failed to update the web config secret: %w", err)
```

File: pkg/thanos/operator.go [hunk 4]
```diff
@@ -795,6 +810,36 @@ func (o *Operator) enqueueForNamespace(store cache.Store, nsName string) {
...
+		fields = tr.Spec.Web.WebConfigFileFields
+	}
+
+	webConfig, err := webconfig.New(
+		webConfigDir,
+		webConfigSecretName(tr.Name),
+		fields,
+	)
+	if err != nil {
+		return fmt.Errorf("failed to initialize web config: %w", err)
```
Comment (simonpasquier) [inline pkg/thanos/operator.go:825]: (nit)
```suggestion
		return fmt.Errorf("failed to initialize the web config: %w", err)
```

File: pkg/thanos/operator.go [hunk 5]
```diff
@@ -817,3 +862,20 @@ func applyConfigurationFromThanosRuler(a *monitoringv1.ThanosRuler) *monitoringv
...
+func newTLSAssetSecret(tr *monitoringv1.ThanosRuler, config Config) *v1.Secret {
+	s := &v1.Secret{
+		Data: map[string][]byte{},
+	}
+
+	operator.UpdateObject(
+		s,
+		operator.WithLabels(config.Labels),
+		operator.WithAnnotations(config.Annotations),
+		//operator.WithManagingOwner(tr),	todo: ?
```
Comment (simonpasquier) [inline pkg/thanos/operator.go:875]: why commented?

File: pkg/thanos/statefulset.go [hunk 6]
```diff
@@ -38,6 +39,8 @@ const (
 	rulesDir                  = "/etc/thanos/rules"
 	configDir                 = "/etc/thanos/config"
 	storageDir                = "/thanos/data"
+	webConfigDir              = "/etc/thanos/web_config" // todo: find the right path
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:42]:
```suggestion
	webConfigDir              = "/etc/thanos/web_config"
```

File: pkg/thanos/statefulset.go [hunk 7]
```diff
@@ -254,6 +257,15 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
 		trCLIArgs = append(trCLIArgs, monitoringv1.Argument{Name: "alert.relabel-config-file", Value: fullPath})
 	}
 
+	if tr.Spec.Web != nil {
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:260]: we need a version check here (web config requires Thanos v0.21.0 at least). If Thanos >= v0.21.0, the operator should always mount the TLS assets volume in the thanos container even if empty.

File: pkg/thanos/statefulset.go [hunk 8]
```diff
@@ -303,13 +316,37 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
...
+
 		additionalContainers = append(
 			additionalContainers,
 			operator.CreateConfigReloader(
 				"config-reloader",
 				operator.ReloaderConfig(config.ReloaderConfig),
+				operator.WebConfigFile(configReloaderWebConfigFile),
 				operator.ReloaderURL(url.URL{
-					Scheme: "http",
+					Scheme: "http", // fixme: should we allow for https?
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:349]: Yes the operator should check if the web config enables HTTPS (see what's been done for Alertmanager).

File: pkg/thanos/statefulset.go (hunk 7 above)
Comment (jamshidi799) [reply pkg/thanos/statefulset.go:260]: so the if condition should be like this?
`version.GTE(semver.MustParse("0.21.0"))`

Comment (simonpasquier) [reply pkg/thanos/statefulset.go:260]: correct

File: pkg/thanos/statefulset.go [hunk 9]
```diff
@@ -147,7 +147,11 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
 	thanosVersion := operator.StringValOrDefault(tr.Spec.Version, operator.DefaultThanosVersion)
 	if _, err := semver.ParseTolerant(thanosVersion); err != nil {
 		return nil, fmt.Errorf("failed to parse Thanos version: %w", err)
+	}
 
+	version, err := semver.ParseTolerant(thanosVersion)
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:152]: we already call `semver.ParseTolerant(thanosVersion)` above. Can you rearrange to have only one call?

File: pkg/thanos/statefulset.go [hunk 10]
```diff
@@ -303,13 +327,37 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
...
+		webConfig, err := webconfig.New(webConfigDir, webConfigSecretName(tr.Name), fields)
+		if err != nil {
+			return nil, err
+		}
+
+		confArg, configVol, configMount, err := webConfig.GetMountParameters()
+		if err != nil {
+			return nil, err
+		}
+		containerArgs = append(containerArgs, fmt.Sprintf("--%s=%s", "http.config", confArg.Value))
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:344]: we need a version check similar to https://github.com/prometheus-operator/prometheus-operator/blob/984b6e9697977fb494b006de3f20da4abc1d7a24/pkg/prometheus/server/statefulset.go#L277-L309

File: pkg/thanos/statefulset.go (hunk 9 above)
Comment (jamshidi799) [reply pkg/thanos/statefulset.go:149]: oh sorry I didn't see it

File: pkg/apis/monitoring/v1/thanos_types.go [hunk 11]
```diff
@@ -250,6 +250,24 @@ type ThanosRulerSpec struct {
...
+	// Defines the configuration of the ThanosRuler web server.
+	Web *ThanosRulerWebSpec `json:"web,omitempty"`
+}
+
+// ThanosRulerWebSpec defines the configuration of the ThanosRuler web server.
+// +k8s:openapi-gen=true
+type ThanosRulerWebSpec struct {
+	WebConfigFileFields `json:",inline"`
+
+	// The prometheus web page title.
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/thanos_types.go:262]:
```suggestion
	// The Thanos Ruler web page title.
```

File: pkg/thanos/statefulset.go [hunk 12]
```diff
@@ -254,6 +258,22 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
 		trCLIArgs = append(trCLIArgs, monitoringv1.Argument{Name: "alert.relabel-config-file", Value: fullPath})
 	}
 
+	if version.GTE(semver.MustParse("0.21.0")) {
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:261]: (nit) we could mount the secret for all versions (e.g. even if not used).

File: pkg/thanos/statefulset.go [hunk 13]
```diff
@@ -303,13 +324,39 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
...
+			webConfig, err := webconfig.New(webConfigDir, webConfigSecretName(tr.Name), fields)
+			if err != nil {
+				return nil, err
+			}
+
+			confArg, configVol, configMount, err := webConfig.GetMountParameters()
+			if err != nil {
+				return nil, err
+			}
+			containerArgs = append(containerArgs, fmt.Sprintf("--%s=%s", "http.config", confArg.Value))
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:342]: (nit)
```suggestion
			containerArgs = append(containerArgs, fmt.Sprintf("--http.config=%s", confArg.Value))
```

File: pkg/apis/monitoring/v1/thanos_types.go [hunk 14]
```diff
@@ -250,6 +250,24 @@ type ThanosRulerSpec struct {
...
+	// +optional
+	PageTitle *string `json:"pageTitle,omitempty"`
+
+	// Defines the maximum number of simultaneous connections
+	// A zero value means that Prometheus doesn't accept any incoming connection.
+	// +kubebuilder:validation:Minimum:=0
+	// +optional
+	MaxConnections *int32 `json:"maxConnections,omitempty"`
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/thanos_types.go:270]: I don't think that these fields are supported by Thanos Ruler.

File: pkg/apis/monitoring/v1/thanos_types.go [hunk 15]
```diff
@@ -250,6 +250,18 @@ type ThanosRulerSpec struct {
...
+}
+
+// ThanosRulerWebSpec defines the configuration of the ThanosRuler web server.
+// +k8s:openapi-gen=true
+type ThanosRulerWebSpec struct {
+	WebConfigFileFields `json:",inline"`
+
+	// The Thanos Ruler web page title.
+	// +optional
+	PageTitle *string `json:"pageTitle,omitempty"`
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/thanos_types.go:264]: This isn't used anywhere since not supported by Thanos?
```suggestion
```

File: pkg/thanos/statefulset.go [hunk 16]
```diff
@@ -303,13 +322,39 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
...
+				return nil, err
+			}
+			containerArgs = append(containerArgs, fmt.Sprintf("--http.config=%s", confArg.Value))
+			trVolumes = append(trVolumes, configVol...)
+			trVolumeMounts = append(trVolumeMounts, configMount...)
+
+			if tr.Spec.Web != nil {
+				configReloaderWebConfigFile = confArg.Value
+				configReloaderVolumeMounts = append(configReloaderVolumeMounts, configMount...)
+			}
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:347]: The test exists in Alertmanager/Prometheus to deal with older config reloader versions. Here we can expect that users have already updated to a recent version.
```suggestion
			configReloaderWebConfigFile = confArg.Value
			configReloaderVolumeMounts = append(configReloaderVolumeMounts, configMount...)

File: pkg/apis/monitoring/v1/thanos_types.go (hunk 15 above)
Comment (jamshidi799) [reply pkg/apis/monitoring/v1/thanos_types.go:264]: I didn't find `pageTitle` in Thanos Ruler flags so I'll remove it.

**Review by simonpasquier — APPROVED** [review]
Thanks!
