### PR TITLE
fix: Alertmanager and Prometheus don't pick up new certificates after renewal

### LINKED ISSUE #5527: Alertmanager TLS certs not being renewed
**What happened?**
When Alertmanager is configured to enable the web TLS, it is not able to detected updated secret with renewed certificate and apply it. We use cert-manager to keep certificates updated. I checked the secret, and it contains the correct updated certificate, but when I attached to the container the mounted TLS certificate was expired and not replaced by the new one.

I noticed the secret with TLS assets is mounted like this:

```yaml
  - mountPath: /etc/alertmanager/web_config/secret_alertmanager-server-tls_tls.key
    name: web-config-tls-secret-key-alertmanager-server-tls-58c25a53
    readOnly: true
    subPath: tls.key
  - mountPath: /etc/alertmanager/web_config/secret_alertmanager-server-tls_tls.crt
    name: web-config-tls-secret-cert-alertmanager-server-tls-58c25a53
    readOnly: true
    subPath: tls.crt
```

But [Kubernetes docs](https://kubernetes.io/docs/concepts/configuration/secret/) says:

> Note: A container using a Secret as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes#using-subpath) volume mount does not receive automated Secret updates.

When the certificate expires, and the new one is not reloaded Prometheus is no longer able to send the alerts. 

**Did you expect to see some different?**
When the certificate is renewed and specified secret updated, the certificate should also be updated inside the container. Also, Alertmanager and Prometheus should watch for the changes and load the changed certificates.

**How to reproduce it (as minimally and precisely as possible)**:

Kube-prometheus-stack Helm chart values:

```yaml
alertmanager:
  serviceMonitor:
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  alertmanagerSpec:
    replicas: 1
    web:
      tlsConfig:
        clientAuthType: "NoClientCert"
        keySecret:
          name: "alertmanager-server-tls"
          key: "tls.key"
        cert:
          secret:
            name: "alertmanager-server-tls"
            key: "tls.crt"
```

Cert-manager TLS certificate:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-server-tls
spec:
  secretName: alertmanager-server-tls
  issuerRef:
    name: vault
    kind: ClusterIssuer
  duration: 1h
  renewBefore: 15m 
  commonName: alertmanager
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - "prometheus-stack-alertmanager"
    - "prometheus-stack-alertmanager.prometheus-stack"
    - "prometheus-stack-alertmanager.prometheus-stack.svc"
    - "prometheus-stack-alertmanager.prometheus-stack.svc.cluster"
    - "prometheus-stack-alertmanager.prometheus-stack.svc.cluster.local"
```

**Environment**

* Prometheus Operator version:

    `v0.63.0`
    

* Kubernetes version information:

    `v1.25.3`
    

* Kubernetes cluster kind:

    Tested both on the Kind cluster and Kubeadm baremetal.

* Prometheus Operator Logs:

```
prometheus-stack-operator-75987f8f8f-8b67k level=info ts=2023-04-25T13:14:01.369962961Z caller=operator.go:1330 component=prometheusoperator key=prometheus-stack/prometheus-stack-pr
ometheus msg="update prometheus status"
prometheus-stack-operator-75987f8f8f-8b67k level=info ts=2023-04-25T13:14:01.783686712Z caller=operator.go:1330 component=prometheusoperator key=prometheus-stack/prometheus-stack-pr
ometheus msg="update prometheus status"
```

* Prometheus Logs:

```
prometheus-prometheus-stack-prometheus-0 prometheus ts=2023-04-25T13:38:32.628Z caller=notifier.go:532 level=error component=notifier alertmanager=https://10.244.3.47:9093/api/v2/al
erts count=1 msg="Error sending alert" err="Post \"https://10.244.3.47:9093/api/v2/alerts\": x509: certificate has expired or is not yet valid: current time 2023-04-25T13:38:32Z is
after 2023-04-25T11:15:10Z"
prometheus-prometheus-stack-prometheus-0 prometheus ts=2023-04-25T13:38:52.855Z caller=notifier.go:532 level=error component=notifier alertmanager=https://10.244.3.47:9093/api/v2/al
erts count=1 msg="Error sending alert" err="Post \"https://10.244.3.47:9093/api/v2/alerts\": x509: certificate has expired or is not yet valid: current time 2023-04-25T13:38:52Z is
after 2023-04-25T11:15:10Z"
```

* Alertmanager Logs:

```
alertmanager-prometheus-stack-alertmanager-0 alertmanager 2023/04/25 13:40:02 http: TLS handshake error from 10.244.3.48:55178: remote error: tls: bad certificate
alertmanager-prometheus-stack-alertmanager-0 alertmanager 2023/04/25 13:40:02 http: TLS handshake error from 10.244.3.48:55184: remote error: tls: bad certificate
```

### PR DESCRIPTION
**Pull request by xiu**
## Description
The fix is to not use `subPath` when mounting web certificates. As per
[Kubernetes' documentation][1], mounts using subPath will not get updates. This
commit changes it to full mounts. Prometheus and Alertmanager use
[exporter-toolkit][2] which reloads the certs for every query.
    
This commit also extends Prometheus' and Alertmanager's stateful tests to check
prometheus-config-reloader arguments.
    
References:
* https://github.com/prometheus-operator/prometheus-operator/issues/5527
* https://github.com/prometheus-operator/prometheus-operator/pull/5535#discussion_r1194940482
    
[1]: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod
[2]: https://github.com/prometheus/exporter-toolkit

Fixes #5527 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Prometheus and Alertmanager will now use updated certificates (for instance, in the case of a certificate renewal).
```

### CODE REVIEW

**Comment by xiu** [comment]
First tentative, web-config certs are now mounted in full. Still need to mount the corresponding secrets in `prometheus-config-reloader`, it currently mounts `web-config` which is not useful in this case.

File: pkg/webconfig/tls_credentials.go [hunk 1]
```diff
@@ -126,7 +126,7 @@ func (a tlsCredentials) mountParamsForSecret(
 		Name:      volumeName,
 		ReadOnly:  true,
 		MountPath: mountPath,
-		SubPath:   secret.Key,
+		//SubPath:   secret.Key,
```
Comment (ArthurSens) [inline pkg/webconfig/tls_credentials.go:129]: Should we delete commented code?

**Review by ArthurSens — COMMENTED** [review]
I'm quite unfamiliar with TLS certification 😅 

How do you generate an expired TLS certificate, renew it and make sure that the renewed certificated is being served to the appropriate pods?

**Comment by xiu** [comment]
> I'm quite unfamiliar with TLS certification 😅 
> 
> How do you generate an expired TLS certificate, renew it and make sure that the renewed certificated is being served to the appropriate pods?

Here I would create a secret containing a cert/key/ca, reference it, check that it's configured and then update the secret and check that the new secret is in place. I'll add an end to end test to that one 👍

File: pkg/webconfig/tls_credentials.go (hunk 1 above)
Comment (xiu) [reply pkg/webconfig/tls_credentials.go]: Done, thanks!

File: pkg/webconfig/tls_credentials.go [hunk 2]
```diff
@@ -160,7 +160,7 @@ func (a tlsCredentials) mountParamsForConfigmap(
 		Name:      volumeName,
 		ReadOnly:  true,
 		MountPath: mountPath,
-		SubPath:   configMap.Key,
+		//SubPath:   configMap.Key,
```
[the remark this answers is not in the document]
Comment (xiu) [reply pkg/webconfig/tls_credentials.go]: Done, thanks!

**Comment by xiu** [comment]
> Here I would create a secret containing a cert/key/ca, reference it, check that it's configured and then update the secret and check that the new secret is in place. I'll add an end to end test to that one 👍

Done with the latest changes for alertmanager, will add one for Prometheus as well later.

**Comment by xiu** [comment]
> > Here I would create a secret containing a cert/key/ca, reference it, check that it's configured and then update the secret and check that the new secret is in place. I'll add an end to end test to that one 👍
> 
> Done with the latest changes for alertmanager, will add one for Prometheus as well later.

Done with Prometheus. I added a unittest for PrometheusAgent, it's mostly a lot of duplication from `prometheus/server`, you might want to check it out @ArthurSens. I didn't add an e2e test for PrometheusAgent though.

**Review by ArthurSens — APPROVED** [review]
Without manually testing it myself, looks good! Good work with tests, they made me confident that the change works :)

Only have one small nit to help our future selves to understand why certs are mounted differently

File: pkg/alertmanager/statefulset.go [hunk 3]
```diff
@@ -659,6 +659,18 @@ func makeStatefulSetSpec(a *monitoringv1.Alertmanager, config Config, tlsAssetSe
 		amArgs = append(amArgs, fmt.Sprintf("--%s=%s", confArg.Name, confArg.Value))
 		volumes = append(volumes, configVol...)
 		amVolumeMounts = append(amVolumeMounts, configMount...)
+
+		for _, vol := range configVol {
+			if !strings.HasPrefix(vol.Name, webconfig.VolumePrefix) {
+				continue
+			}
+			mountPath := webConfigDir + "/" + vol.Name
+			configReloaderVolumeMounts = append(configReloaderVolumeMounts, v1.VolumeMount{
```
[the remark this answers is not in the document]
Comment (xiu) [reply pkg/alertmanager/statefulset.go]: Done in 5ebc34ab3 :) Did it in multiple places, let me know if it fits.

**Review by JoaoBraveCoding — COMMENTED** [review]
Small nit but lgtm! E2E tests are great!

File: pkg/alertmanager/statefulset.go [hunk 4]
```diff
@@ -659,6 +659,24 @@ func makeStatefulSetSpec(a *monitoringv1.Alertmanager, config Config, tlsAssetSe
...
+			// If we don't receive updates, we can't detect updated certificates and thus reload services.
+			//
+			// References:
+			// * https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod
+			// * https://github.com/prometheus-operator/prometheus-operator/issues/5527
+			configReloaderVolumeMounts = append(configReloaderVolumeMounts, v1.VolumeMount{
+				Name:      vol.Name,
+				MountPath: mountPath,
+			})
+			watchedDirectories = append(watchedDirectories, mountPath)
```
[the remark this answers is not in the document]
Comment (xiu) [reply pkg/alertmanager/statefulset.go:681]: Reworded but part of 7031589d4

File: pkg/alertmanager/statefulset.go [hunk 5]
```diff
@@ -659,6 +659,27 @@ func makeStatefulSetSpec(a *monitoringv1.Alertmanager, config Config, tlsAssetSe
 		amArgs = append(amArgs, fmt.Sprintf("--%s=%s", confArg.Name, confArg.Value))
 		volumes = append(volumes, configVol...)
 		amVolumeMounts = append(amVolumeMounts, configMount...)
+
+		for _, vol := range configVol {
```
Comment (JoaoBraveCoding) [inline pkg/alertmanager/statefulset.go:663]: nit: This code seems exactly the same on all 3 components, part of me feels like we should be able to extract it somewhere else and simply call a function. WDYT? This obviously can also be done in a follow up

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm, just one (non-blocking) question/possible improvement

File: pkg/alertmanager/statefulset.go (hunk 5 above)
Comment (xiu) [reply pkg/alertmanager/statefulset.go]: Done in 5f34f9150056f261f8c52db6dfb799453d79d4e2, pending e2e tests confirmation 😅

Comment (xiu) [reply pkg/alertmanager/statefulset.go]: And done 🟢

**Review by ArthurSens — APPROVED** [review]

File: pkg/alertmanager/statefulset.go [hunk 6]
```diff
@@ -659,6 +659,16 @@ func makeStatefulSetSpec(a *monitoringv1.Alertmanager, config Config, tlsAssetSe
 		amArgs = append(amArgs, fmt.Sprintf("--%s=%s", confArg.Name, confArg.Value))
 		volumes = append(volumes, configVol...)
 		amVolumeMounts = append(amVolumeMounts, configMount...)
+
+		// Add the TLS credentials volumes to the list of directories prometheus-config-reloader watches. When changes
+		// happen in these directories (e.g. if a certificate is renewed), prometheus-config-reloader will ask
+		// prometheus to reload its configuration.
```
[the remark this answers is not in the document]
Comment (xiu) [reply pkg/alertmanager/statefulset.go:665]: Interesting! Let me try :)

File: pkg/prometheus/agent/statefulset.go [hunk 7]
```diff
@@ -219,6 +219,18 @@ func makeStatefulSetSpec(
 		return nil, err
 	}
 
+	var watchedDirectories []string
```
Comment (JoaoBraveCoding) [inline pkg/prometheus/agent/statefulset.go:222]: nit: this change seems like it can be reverted, unless I'm missing something or if you believe it makes more sense have it in this part

File: pkg/prometheus/server/statefulset.go [hunk 8]
```diff
@@ -291,6 +291,18 @@ func makeStatefulSetSpec(
...
+		{
+			Name:      "config",
+			MountPath: prompkg.ConfDir,
+		},
+		{
+			Name:      "config-out",
+			MountPath: prompkg.ConfOutDir,
+		},
+	}
+
```
Comment (JoaoBraveCoding) [inline pkg/prometheus/server/statefulset.go:305]: nit: (same as previous nit) this change seems like it can be reverted, unless I'm missing something or if you believe it makes more sense have it in this part

**Review by JoaoBraveCoding — APPROVED** [review]
2 small nit's but lgtm

File: pkg/prometheus/agent/statefulset.go (hunk 7 above)
Comment (xiu) [reply pkg/prometheus/agent/statefulset.go:222]: haha you were faster than me, I'm cleaning it up slowly :p Thanks!

File: pkg/prometheus/server/statefulset.go (hunk 8 above)
Comment (xiu) [reply pkg/prometheus/server/statefulset.go:305]: https://github.com/prometheus-operator/prometheus-operator/pull/5535#discussion_r1197680834

File: pkg/alertmanager/statefulset.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (xiu) [reply pkg/alertmanager/statefulset.go]: Works, thanks! I had some tests failing at first but it was because I didn't wait enough for the secrets to be updated in the pods.

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm

**Comment by xiu** [comment]
All done, should be good to merge :+1:

**Comment by ArthurSens** [comment]
Thank youuuu
