### PR TITLE
FIX: LabelName validation issue 

### LINKED ISSUE #6889: API validation not working for `map[v1.LabelName]string` type structures
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
Issue was discovered while refactoring the `StaticConfig` struct. API validations are not adhered to for the LabelName type when it is part of the map structure. 

## Steps to Reproduce
1. Run the operator (I did it in a local cluster, with the current version code of the operator)
2. Create the manifest.
3. run `kubectl apply -f <filename.yaml>`

## Expected Result
The resource should be rejected because the `LabelName` does not follow the API validation rules.
 
## Actual Result
The resource gets created.

### Prometheus Operator Version

```shell
v0.76.0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-08-15T02:13:19Z"
  compiler: gc
  gitCommit: a51b3b711150f57ffc1f526a640ec058514ed596
  gitTreeState: clean
  gitVersion: v1.30.4
  goVersion: go1.22.6
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2023-06-15T00:36:28Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
```
```


### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

Other (please comment)

### Manifests

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: static-config
  namespace: default
  labels:
    prometheus: system-monitoring-prometheus
    app.kubernetes.io/name: scrape-config-example
spec:
  staticConfigs:
    - labels:
        -"1owner": "prometheus"
```

### prometheus-operator log output

```shell
mviswanathsai@pop-os:~$ kubectl create -f static_config.yaml 
scrapeconfig.monitoring.coreos.com/static-config created
```

### Anything else?

I ran a local deployment using `./scripts/runvexternal.sh -c` with the latest code version at the time of writing this issue.

### PR DESCRIPTION
**Pull request by mviswanathsai**
## Description

Following @simonpasquier 's [suggestion](https://github.com/prometheus-operator/prometheus-operator/pull/6867#discussion_r1735808482).

Closes #6889 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Fix LabelName validation issue 
```

### CODE REVIEW

File: pkg/prometheus/resource_selector.go [hunk 1]
```diff
@@ -1493,3 +1498,22 @@ func (rs *ResourceSelector) validateScalewaySDConfigs(ctx context.Context, sc *m
 
 	return nil
 }
+
+func (rs *ResourceSelector) validateStaticConfig(sc *monitoringv1alpha1.ScrapeConfig) error {
+	for i, config := range sc.Spec.StaticConfigs {
+		if config.Labels != nil {
```
Comment (simonpasquier) [inline pkg/prometheus/resource_selector.go:1504]: no need to check for nil, we can do `range config.Labels` directly.

File: pkg/prometheus/resource_selector.go [hunk 2]
```diff
@@ -827,6 +827,11 @@ func (rs *ResourceSelector) SelectScrapeConfigs(ctx context.Context, listFn List
 			continue
 		}
 
+		if err = rs.validateStaticConfig(sc); err != nil {
```
Comment (simonpasquier) [inline pkg/prometheus/resource_selector.go:830]:
```suggestion
		// The Kubernetes API can't do the validation (for now) because kubebuilder validation markers don't work on map keys with custom type.
		// https://github.com/prometheus-operator/prometheus-operator/issues/6889
		if err = rs.validateStaticConfig(sc); err != nil {
```

File: pkg/prometheus/resource_selector.go [hunk 3]
```diff
@@ -1493,3 +1498,22 @@ func (rs *ResourceSelector) validateScalewaySDConfigs(ctx context.Context, sc *m
 
 	return nil
 }
+
+func (rs *ResourceSelector) validateStaticConfig(sc *monitoringv1alpha1.ScrapeConfig) error {
+	for i, config := range sc.Spec.StaticConfigs {
+		if config.Labels != nil {
+			for labelName := range config.Labels {
+				regexp, err := regexp.Compile("^[a-zA-Z_][a-zA-Z0-9_]*$")
```
Comment (simonpasquier) [inline pkg/prometheus/resource_selector.go:1506]: we can use `model.LabelName(labelName).IsValid()`

**Comment by mviswanathsai** [comment]
PTAL @simonpasquier

**Review by simonpasquier — APPROVED** [review]
Thanks!
