### PR TITLE
test:e2e:Prometheus: Fix flake in check for minReadySeconds

### LINKED ISSUE #4401: PromMinReadySeconds e2e test is flaky
I've seen the test fail occasionally because the modification of the minReadySeconds field hasn't been propagated to the statefulset. Maybe the update didn't happen yet and the test should retry? 

```
2021-11-09T14:28:31.2359914Z === CONT  TestAllNS/y/PromMinReadySeconds
2021-11-09T14:28:53.4706077Z     prometheus_test.go:3754: expected MinReadySeconds to be 10 but got 5
```

https://github.com/prometheus-operator/prometheus-operator/blob/6dfe2c320963277d3e6aa9da25d2a347a776535f/test/e2e/prometheus_test.go#L3742-L3755

cc @PhilipGough

### PR DESCRIPTION
**Pull request by PhilipGough**
## Description

Fixes #4401 

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

File: test/e2e/prometheus_test.go [hunk 1]
```diff
@@ -3730,13 +3730,22 @@ func testPromMinReadySeconds(t *testing.T) {
...
 
-	promSS, err := kubeClient.AppsV1().StatefulSets(ns).Get(context.Background(), "prometheus-basic-prometheus", metav1.GetOptions{})
-	if err != nil {
-		t.Fatal(err)
-	}
+	var got int32
+	err = wait.Poll(time.Second, time.Minute*5, func() (bool, error) {
+		promSS, err := kubeClient.AppsV1().StatefulSets(ns).Get(context.Background(), "prometheus-basic-prometheus", metav1.GetOptions{})
+		if err != nil {
+			return false, err
```
Comment (fpetkovski) [inline test/e2e/prometheus_test.go:3737]: I think this that returning an error will short-circuit the wait.Poll function and won't really reduce the flake. What we want is 
```
if err != nil {
  return false, nil
}
```

Comment (PhilipGough) [reply test/e2e/prometheus_test.go:3737]: Hey @fpetkovski - I'm not entirely sure I agree since from https://github.com/prometheus-operator/prometheus-operator/pull/4406/files#diff-b3d3450b51af206bb0009c2b9c2f863c3d03a3575d64cbdb18510a2bc834144aR3728 we expect the statefulset to exist which is why I kept the hard error. I don't *think* that is what was causing the flake, it was because the spec hadn't yet been updated which the retry logic should solve.

Our other tests don't retry on error for the `Get Resource` calls so I would not expect this to behave or be handled any differently.

That said, I don't think changing it to retry on error is a big issue so I can do it if you prefer. Just telling you my thought process :)

Comment (fpetkovski) [reply test/e2e/prometheus_test.go:3737]: I see, I was under the impression that the flake was caused because we didn't wait long enough. In that case, it's correct to do what you've done and return an error if the sts is missing :+1:

**Review by fpetkovski — APPROVED** [review]
Since these sorts of flakes are hard to debug, I'm fine with merging this and monitoring the CI for a bit.

File: test/e2e/prometheus_test.go [hunk 2]
```diff
@@ -3730,13 +3730,22 @@ func testPromMinReadySeconds(t *testing.T) {
 		t.Fatal("Creating prometheus failed: ", err)
 	}
 
-	promSS, err := kubeClient.AppsV1().StatefulSets(ns).Get(context.Background(), "prometheus-basic-prometheus", metav1.GetOptions{})
-	if err != nil {
-		t.Fatal(err)
-	}
+	var got int32
+	err = wait.Poll(time.Second, time.Minute*5, func() (bool, error) {
```
Comment (simonpasquier) [inline test/e2e/prometheus_test.go:3734]: I don't think that a wait.Poll is needed here since the sts should be created with the expected value.

Comment (PhilipGough) [reply test/e2e/prometheus_test.go]: good point

**Review by simonpasquier — APPROVED** [review]
approve
