### PR TITLE
Check if controllers' CRDs are provided and manageable by operator

### LINKED ISSUE #6140: Errors about CRDs not present even if they are not needed
**What happened?**

I'm doing Prometheus Federation and my federated Prometheuses don't need these components: _Alertmanagers_, _AlertmanagerConfigs_ and _ThanosRulers_.

I'm using this Helm Chart: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/54.1.0

Even if I set `enabled` to `false` for `alertmanager` and `thanosRuler`, the operator is still watching for their CRDs.

The less CRDs to install the better as each time they are applied it's an overhead, so that's why I would like to avoid installing the ones that are not needed (https://github.com/prometheus-operator/prometheus-operator/tree/v0.69.1/example/prometheus-operator-crd).

**Environment**

* Prometheus Operator version: _v0.69.1_
* Prometheus Operator Logs (repeated every minute or so):
```
level=warn ts=2023-12-04T15:54:14.891376049Z caller=klog.go:108 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1alpha1.AlertmanagerConfig: the server could not find the requested resource (get alertmanagerconfigs.monitoring.coreos.com)"
level=error ts=2023-12-04T15:54:14.891484742Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1alpha1.AlertmanagerConfig: failed to list *v1alpha1.AlertmanagerConfig: the server could not find the requested resource (get alertmanagerconfigs.monitoring.coreos.com)"
level=warn ts=2023-12-04T15:54:23.849004248Z caller=klog.go:108 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)"
level=error ts=2023-12-04T15:54:23.849040616Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.ThanosRuler: failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)"
level=warn ts=2023-12-04T15:54:32.908493503Z caller=klog.go:108 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1.Alertmanager: the server could not find the requested resource (get alertmanagers.monitoring.coreos.com)"
level=error ts=2023-12-04T15:54:32.9085719Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.Alertmanager: failed to list *v1.Alertmanager: the server could not find the requested resource (get alertmanagers.monitoring.coreos.com)"
```

Thanks for your help.

### PR DESCRIPTION
**Pull request by haanhvu**
## Description

Only start each controller when its crd is provided and manageable by the operator, and fail the operator if no controllers start.

Fixes #6140

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Check locally with some crds not provided.

Before the change:
```
level=warn ts=2024-02-29T14:21:04.383739949Z caller=klog.go:118 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: failed to list *v1.Prometheus: the server could not find the requested resource (get prometheuses.monitoring.coreos.com)"
level=error ts=2024-02-29T14:21:04.383844053Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: Failed to watch *v1.Prometheus: failed to list *v1.Prometheus: the server could not find the requested resource (get prometheuses.monitoring.coreos.com)"
```

With the change:
```
level=info ts=2024-02-29T14:27:23.197293317Z caller=operator.go:425 component=prometheusagent-controller msg="successfully synced all caches"
```

When no controllers are provided:
```
level=error ts=2024-02-29T14:46:33.051429048Z caller=main.go:431 msg="no controller is supported"
```

## Changelog entry

Only start each controller when its crd is provided and manageable by the operator, and fail the operator if no controllers start.

### CODE REVIEW

File: cmd/operator/main.go [hunk 1]
```diff
@@ -325,16 +355,80 @@ func run(fs *flag.FlagSet) int {
 		}
 	}
 
-	ao, err := alertmanagercontroller.New(ctx, restConfig, cfg, logger, r, canReadStorageClass, eventRecorderFactory)
+	alertManagerSupported, err := checkPrerequisites(
```
Comment (ArthurSens) [inline cmd/operator/main.go:358]:
```suggestion
	alertmanagerSupported, err := checkPrerequisites(
```

**Review by ArthurSens — COMMENTED** [review]
Awesome, thanks for raising the PR!

This is a small code change but a big behavior change for the operator in my opinion. I'm worried that we might require different RBAC permissions in the future and forget to change those pre-requisites. Would it make sense to add e2e tests?

**Comment by haanhvu** [comment]
> I'm worried that we might require different RBAC permissionss in the future and forget to change those pre-requisites. Would it make sense to add e2e tests?

@ArthurSens Yeah right now the permissions are hardcoded. It's indeed a valid concern. Instead of adding a new e2e test, I think the better way is getting the permission of each resource and return it to `checkPrerequisites()`, instead of hardcoding the permissions like now. Is it possible to do that (in code)?

**Comment by simonpasquier** [comment]
This is great!

>  I'm worried that we might require different RBAC permissions in the future and forget to change those pre-requisites. 

It wouldn't be very different than with the current situation? e.g. if the operator starts requiring permission "update" on resource "foo" and users don't update the prometheus-operator SA RBAC, the controller starts but it wouldn't work fully.

**Review by ArthurSens — APPROVED** [review]
Yeah, let's see how this evolves

LGTM

File: cmd/operator/main.go (hunk 1 above)
Comment (haanhvu) [reply cmd/operator/main.go]: I fixed this nit in the last commit. CI says `TestAllNS/y/PromRulesExceedingConfigMapLimit` fails this time.

This test passes locally for me. And it doesn't make sense that a typo fix could fail an e2e test. Could you reactivate CI to see if it's flaky?

Comment (haanhvu) [reply cmd/operator/main.go]: I just realized I didn't rebase to the latest main. Let me rebase to see how it goes.

Comment (haanhvu) [reply cmd/operator/main.go]: After rebased everything is green now. Sorry for making noise...

File: cmd/operator/main.go [hunk 2]
```diff
@@ -327,16 +357,80 @@ func run(fs *flag.FlagSet) int {
...
+	if thanosRulerSupported {
+		to, err = thanoscontroller.New(ctx, restConfig, cfg, logger, r, canReadStorageClass, eventRecorderFactory)
+		if err != nil {
+			level.Error(logger).Log("msg", "instantiating thanos controller failed", "err", err)
+			cancel()
+			return 1
+		}
+	}
+
+	if po == nil && pao == nil && ao == nil && to == nil {
```
Comment (simonpasquier) [inline cmd/operator/main.go:432]:
```suggestion
	if po == nil && pao == nil && ao == nil && to == nil && kc == nil {
```

File: cmd/operator/main.go [hunk 3]
```diff
@@ -327,16 +357,80 @@ func run(fs *flag.FlagSet) int {
...
+		level.Error(logger).Log("msg", "no controller is supported")
```
Comment (simonpasquier) [inline cmd/operator/main.go:433]:
```suggestion
		level.Error(logger).Log("msg", "no controller can be started, check the RBAC permissions of the service account")
```

File: cmd/operator/main.go (hunk 1 above)
Comment (ArthurSens) [reply cmd/operator/main.go]: I think we have a few flaky tests and that was one of them, don't worry 😅

**Comment by ArthurSens** [comment]
@simonpasquier, I remember that when I did something similar with the prometheus-agent controller the openshift e2e test capture a degradation that we didn't. Do you think it is worth testing this PR with openshift?

**Comment by simonpasquier** [comment]
I'm quite confident but sure it wouldn't hurt to run a pre-test against the OpenShift CI. cc @slashpai who's signed up for the next release :smiley:

**Comment by slashpai** [comment]
> I'm quite confident but sure it wouldn't hurt to run a pre-test against the OpenShift CI. cc @slashpai who's signed up for the next release 😃

I missed the notification, I cherry-picked the changes https://github.com/openshift/prometheus-operator/pull/282

**Comment by slashpai** [comment]
@simonpasquier I tested with cherry-picked changes https://github.com/openshift/prometheus-operator/pull/282 and it is passing test. So this looks good to go?

**Comment by ArthurSens** [comment]
Nice, let's merge it then :)
