### PR TITLE
Validate prometheus rules when generating rule file content

### LINKED ISSUE #4181: Invalid alert labels in PrometheusRule rule blocks reloading of other valid rules
**What happened?**

Invalid alert labels in `PrometheusRule` rule blocks reloading of valid rules
I see this in prom logs:
```
level=error ts=2021-07-22T21:01:10.938Z caller=manager.go:956 component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules/prometheus-prometheus-promoperator-prometheus-rulefiles-0/ns-team-prj-service.yaml: group \"API Metrics\", rule 1, \"memory usage\": invalid label name: app.kubernetes.io/part-of"
level=error ts=2021-07-22T21:01:10.938Z caller=main.go:977 msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
```

This was generated apparently by a rogue alert defn where an invalid rule label was defined:
```yaml
 alert:API Metrics
          expr: >
           .....
          for: 10m
          labels:
            app.kubernetes.io/part-of: service
            env: prod
```

**Did you expect to see something different?**

I would expect the operator checks for alert rule definition validity and doesn't update the prom rules files if invalid rules are defined. This is especially useful in multi-tenant environments where PrometheusRules are defined by tenants of a central operator

### PR DESCRIPTION
**Pull request by amuraru**
## Description

This functionality is available in the custom validation admission webhook
but for environments where the webhooks cannot be enabled this patch enables
in-band validation of prometheus rules as well.

Fixes #4181 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Validate prometheus rules when generating rule file content_

### CODE REVIEW

**Comment by fpetkovski** [comment]
Great contribution, this lgtm. 

cc @simonpasquier

**Comment by amuraru** [comment]
@fpetkovski Filip - would you be able to kick of thr PR checks here - it says a maintainer need to approve the workflow running for a 1st time contributor.
Thanks

**Comment by fpetkovski** [comment]
I believe @paulfantom or @dgrisonnet would be able to help with that.

File: pkg/prometheus/rules.go [hunk 1]
```diff
@@ -221,11 +224,20 @@ func (c *Operator) selectRules(p *monitoringv1.Prometheus, namespaces []string)
 	return rules, nil
 }
 
-func generateContent(promRule monitoringv1.PrometheusRuleSpec) (string, error) {
+func generateContent(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
 	content, err := yaml.Marshal(promRule)
 	if err != nil {
 		return "", errors.Wrap(err, "failed to marshal content")
 	}
+	_, errs := rulefmt.Parse(content)
```
Comment (paulfantom) [inline pkg/prometheus/rules.go:232]: What will happen if rule has additional fields like `partial_response_strategy: "warn"` needed sometimes by thanos ([docs](https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#partial-response))? Can we add a test case for this?

Comment (amuraru) [reply pkg/prometheus/rules.go:232]: @paulfantom - good call!
You're right - partial_response_strategy field is indeed defined in https://github.com/prometheus-operator/prometheus-operator/blob/fb24ca8fd26597c5a2d69ccac949aa5a76cf29ce/pkg/apis/monitoring/v1/types.go#L1328

but not in upstream prometheus 

https://github.com/prometheus/prometheus/blob/b1ed4a0a663d0c62526312311c7529471abbc565/pkg/rulefmt/rulefmt.go#L107

The latter is used for validation so we need to find a way to reconcile this.

Btw - this may be considered a bug in the current version as the webhook validation does the same thing so when enabled, valid thanos rules may fail validation

Comment (amuraru) [reply pkg/prometheus/rules.go]: @paulfantom can you check the latest version of this PR - I extended the check to ignore `PartialResponseStrategy` field if defined

File: pkg/thanos/rules.go [hunk 2]
```diff
@@ -220,15 +223,37 @@ func (o *Operator) selectRules(t *monitoringv1.ThanosRuler, namespaces []string)
...
+		level.Debug(logger).Log("msg", m, "content", content)
+		for _, err := range errs {
+			level.Info(logger).Log("msg", m, "err", err)
+		}
+		return "", errors.New(m)
+	}
 	return string(content), nil
 }
 
+func validateRule(promRule monitoringv1.PrometheusRuleSpec) []error {
```
Comment (paulfantom) [inline pkg/thanos/rules.go:243]: Can we not duplicate code and reuse same function from `pkg/prometheus/rules.go` ?

File: pkg/prometheus/rules.go [hunk 3]
```diff
@@ -221,14 +224,37 @@ func (c *Operator) selectRules(p *monitoringv1.Prometheus, namespaces []string)
...
 	}
+	errs := validateRule(promRule)
+	if len(errs) != 0 {
+		const m = "Invalid rule"
+		level.Debug(logger).Log("msg", m, "content", content)
+		for _, err := range errs {
+			level.Info(logger).Log("msg", m, "err", err)
+		}
+		return "", errors.New(m)
+	}
```
Comment (paulfantom) [inline pkg/prometheus/rules.go:240]: Would it make sense to wrap it into a function and reuse in `pkg/thanos/rules.go` as well as in admission webhook code?

File: pkg/prometheus/rules.go (hunk 1 above)
Comment (paulfantom) [reply pkg/prometheus/rules.go]: > Btw - this may be considered a bug in the current version as the webhook validation does the same thing so when enabled, valid thanos rules may fail validation

Definitely a bug, could you open an issue for it (or maybe you would you like to work on this?)? It might be good to reuse code from this PR in the admission webhook part too. Ideally, such a fix would be in a separate PR though.

Comment (amuraru) [reply pkg/prometheus/rules.go]: Agree - let me wrap up this PR and file a separate issues and PR for the admission hook

File: pkg/thanos/rules.go (hunk 2 above)
Comment (amuraru) [reply pkg/thanos/rules.go:243]: Thought about that, yes. Currently prometheus and thanos are decoupled packages and couldn't find a common package to factor out this validation logic.

if you think that thanos pkg could depend on prometheus pkg I can do that

Comment (paulfantom) [reply pkg/thanos/rules.go:243]: The validation logic should be the same in all 3 places (prometheus, thanos, and admission webhook packages), and introducing dependency will allow us to keep it that way in the long run. So yes, let's introduce it.

**Comment by amuraru** [comment]
Updated PR based on your @paulfantom review comments.

File: pkg/prometheus/rules.go [hunk 4]
```diff
@@ -22,13 +22,17 @@ import (
 	"strconv"
 	"strings"
 
+	"github.com/prometheus/prometheus/pkg/rulefmt"
+	thanostypes "github.com/thanos-io/thanos/pkg/store/storepb"
```
Comment (paulfantom) [inline pkg/prometheus/rules.go:26]: `go.sum` needs to be updated for this. Please run `go mod tidy`

**Comment by amuraru** [comment]
@paulfantom I think I implemented all the suggestions - would you please review the last version and maybe kick the ci tests? Thanks

**Review by paulfantom — APPROVED** [review]
lgtm on green

**Comment by amuraru** [comment]
Fixed formatting errors reported by `Generate and format (ubuntu-latest)` check
