### PR TITLE
pkg/alertmanager: define all possible receivers

### LINKED ISSUE #3665: Slack receivers are not being populated using managed secret for alertmanager
**What happened?**
Following the steps described [here](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md#manually-managed-secret), you should be able to define alertmanager config using managed secret. When adding receivers of slack_config type, operator is not creating it properly. It's working with webhook and pagerduty, but not using slack_config. I'm able to see the correct information in my managed secret, but the `<mysecret-name>-generated` secret does not have slack_config receivers.

**Did you expect to see something different?**
I want to see slack receivers properly populated by operator.

**How to reproduce it (as minimally and precisely as possible)**:
Create alertmanager config file `alertmanager.yaml`:

```yaml
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'myslack'
receivers:
- name: 'myslack'
  slack_configs:
  - api_url: http://slack.example.com
    send_resolved: true
```

Create  secret:

```bash
kubectl create secret generic alertmanager-example --from-file=alertmanager.yaml
```

Check managed secret:

```bash
kubectl get secret alertmanager-example -o=jsonpath="{.data.alertmanager\.yaml}" -n monitoring | base64 -d
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'myslack'
receivers:
- name: 'myslack'
  slack_configs:
  - api_url: http://slack.example.com
    send_resolved: true
```

Check generated secret:
```bash
kubectl get secret alertmanager-example-generated -o=jsonpath="{.data.alertmanager\.yaml}" -n monitoring | base64 -d
global:
  resolve_timeout: 5m
route:
  receiver: myslack
  group_by:
  - job
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: myslack
templates: []
```

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.43.2`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-a84824", GitCommit:"a84824a1c7b79853d0c57143ea42c9de1788dbba", GitTreeState:"clean", BuildDate:"2020-08-05T01:08:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    `eks`

* Manifests:

     `Already attached.`

* Prometheus Operator Logs:

     `No error logs from operator.`

**Anything else we need to know?**:

No.

### PR DESCRIPTION
**Pull request by simonpasquier**
If the user-defined Alertmanager configuration declared a receiver that
isn't yet supported by AlertmanagerConfig (e.g. email, Pushover or
VictorOps), the receiver declaration would be dropped from the generated
configuration.

Closes #3665

### CODE REVIEW

**Review by lilic — APPROVED** [review]
lgtm

File: pkg/alertmanager/types.go [hunk 1]
```diff
@@ -0,0 +1,292 @@
...
+	parsed, err := time.ParseDuration(string(text))
+	if err == nil {
+		*d = duration(parsed)
+	}
+	return err
+}
+
+func (d duration) MarshalText() ([]byte, error) {
+	return []byte(time.Duration(d).String()), nil
+}
```
Comment (paulfantom) [inline pkg/alertmanager/types.go:279]: Why this is in types.go?
