### PR TITLE
Disable incompatible timestamp from go-kit logger used by HTTP server

### LINKED ISSUE #3959: Incompatible timestamp field value in json logs
**What happened?**

The date format value of the timestamp field (`ts`) in JSON log entry is different when the error originates from the Golang `net/http` library. The [error logger wrapper](https://github.com/prometheus-operator/prometheus-operator/blob/v0.45.0/cmd/operator/main.go#L390) configured is using its own `ts` field (coming from the parsed entry) that has precedence over (overwrites) the one defined by the wrapped base logger of the operator.

**Did you expect to see something different?**

Would expect that the date format of the timestamp field to be consistent among all the logs.

**How to reproduce it (as minimally and precisely as possible)**:

Just sending an invalid HTTPS request to the server when configured in TLS mode (`--web.enable-tls` flag) will generate a log entry with a timestamp value incompatible with the standard format (`time.RFC3339Nano`) used by the operator logger.

Examples:
```
{"caller":"http: TLS handshake error from 127.0.0.1:35138","msg":"EOF","ts":"2021/04/07 14:46:42"}
```
```
{"caller":"http: TLS handshake error from 127.0.0.1:35140","msg":"local error: tls: bad record MAC","ts":"2021/04/07 14:46:42"}
```
```
{"caller":"http: TLS handshake error from 10.40.5.33:32818","msg":"remote error: tls: bad certificate","ts":"2021/04/04 17:34:16"}
```

**Environment**

* Prometheus Operator version:

```
$ /bin/operator --version
prometheus-operator, version 0.45.0 (branch: refs/tags/v0.45.0, revision: 5555f492df250168657b72bb8cb60bec071de71f)
  build user:       lilic
  build date:       20210113-16:18:28
  go version:       go1.15.6
  platform:         linux/amd64
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.1201", GitCommit:"615449f7595f7220169b45eba3fe1b01f9b730de", GitTreeState:"clean", BuildDate:"2021-03-09T03:18:04Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Minikue, GCP

### PR DESCRIPTION
**Pull request by mtherreault**
Fixes #3959 

```release-note:bug
Fix incompatible timestamp field in json logs when emitted by HTTP server
```

### CODE REVIEW

File: cmd/operator/main.go [hunk 1]
```diff
@@ -448,7 +448,7 @@ func Main() int {
 	srv := &http.Server{
 		Handler:   mux,
 		TLSConfig: tlsConfig,
-		ErrorLog:  stdlog.New(log.NewStdlibAdapter(logger), "", stdlog.LstdFlags),
+		ErrorLog:  stdlog.New(log.NewStdlibAdapter(logger), "", 0),
```
Comment (simonpasquier) [inline cmd/operator/main.go:451]: could you add a comment explaining why we set the flag to 0?

Comment (mtherreault) [reply cmd/operator/main.go]: Added comment and further improved generated log entry with better flag setting.

We now have an appropriate and consistent `caller` field:
```
{"caller":"server.go:3093","msg":"http: TLS handshake error from 127.0.0.1:59116: EOF","ts":"2021-04-10T19:17:06.7564989Z"}
```
Instead of begin mistakenly extracted (parsed) from the message as before:
```
{"caller":"http: TLS handshake error from 127.0.0.1:36752","msg":"EOF","ts":"2021-04-09T01:55:08.2770325Z"}
```

**Review by simonpasquier — APPROVED** [review]
thanks!
