### PR TITLE
Replace app label names with app.kubernetes.io/name

### LINKED ISSUE #3706: Add label "app" to PodMetadata doesn't work
**What happened?**
Label "app" added with PodMetadata is not propagated to prometheus pod

**Did you expect to see something different?**
With this Prometheus configuration:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
...
spec:
...
  podMetadata:
    labels:
      app: custom-label
...
```
I expect to have a Prometheus pod like this:
```
kind: Pod
apiVersion: v1
metadata:
...
  labels:
    app: custom-label
...
spec:
...
```
but the Prometheus pod is always created with 
```
kind: Pod
apiVersion: v1
metadata:
...
  labels:
    app: prometheus
...
spec:
...
```

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `prometheus-operator:0.37.0`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"b66f2d3", GitTreeState:"clean", BuildDate:"2020-08-11T15:2
3:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2fbd7c7", GitCommit:"2fbd7c7", GitTreeState:"clean", BuildDate:"2020-10-15T16:25:
45Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
`
    

* Kubernetes cluster kind:

    Openshift cluster 4.5.16

* Manifests:
* Prometheus Operator Logs:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by hooten**
Signed-off-by: Dustin Hooten <dustinhooten@gmail.com>

This PR replaces the `app` label names with `app.kubernetes.io/name` where appropriate. That was suggested in [this comment](https://github.com/prometheus-operator/prometheus-operator/issues/3706#issuecomment-734187876). It will allow users to specify an `app` label in `podMetadata` field of the PrometheusSpec.

Closes #3706

**Release Note Template (will be copied)**

```release-note:change
Replace app label names with app.kubernetes.io/name
```

### CODE REVIEW

**Comment by hooten** [comment]
I would appreciate a review when you get a chance. Thanks!

File: pkg/thanos/statefulset.go [hunk 1]
```diff
@@ -480,7 +479,7 @@ func makeStatefulSetService(tr *monitoringv1.ThanosRuler, config Config) *v1.Ser
 				},
 			},
 			Selector: map[string]string{
-				"app": "thanos-ruler",
+				"app.kubernetes.io/name": "thanos-ruler",
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:482]:
```suggestion
				"app.kubernetes.io/name": thanosRulerLabel,
```

**Review by simonpasquier — APPROVED** [review]
:+1: leaving the final approval to @brancz

**Comment by brancz** [comment]
lgtm

**Comment by hooten** [comment]
Thanks!

**Comment by coderanger** [comment]
This is a potentially breaking change for anyone with their own services routing on these labels. Can we offer both labels for some period to allow for a smooth upgrade?

**Comment by hooten** [comment]
Version 0.47.0 was cut 2 days ago. I think that version has both sets of labels.

**Comment by QuentinBisson** [comment]
This change is a breaking change still because label selectors are immutable on statefulsets so users that want to update will have to delete the statefulset or force update it
