### PR TITLE
pkg/apis: Support Prometheus RuleGroup Limit

### LINKED ISSUE #4998: The "GroupRule" struct is missing the "limit" field.
**What happened?**
I can't create a alerting rule with the "limit" field so that I can't limit the number of alerts an alerting can produce.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `v0.59.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
the offical Prometheus is support the limit field in `group_rule` section.
Reference: https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule_group
image

### PR DESCRIPTION
**Pull request by slashpai**
Fixes #4998

Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>

## Description

Support Prometheus RuleGroup Limit

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Support Prometheus RuleGroup Limit
```

### CODE REVIEW

File: pkg/apis/monitoring/v1/types.go [hunk 1]
```diff
@@ -1828,6 +1828,9 @@ type RuleGroup struct {
 	// +kubebuilder:validation:Pattern="^(?i)(abort|warn)?$"
 	// +kubebuilder:default:=""
 	PartialResponseStrategy string `json:"partial_response_strategy,omitempty"`
+	// Limit the number of alerts an alerting rule and series a recording
+	// rule can produce.
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/types.go:1832]: need to mention which Prometheus/Thanos versions are required

Comment (slashpai) [reply pkg/apis/monitoring/v1/types.go:1832]: Done

**Comment by slashpai** [comment]
@simonpasquier PTAL

**Review by cuizhaoyue — APPROVED** [review]

**Comment by cuizhaoyue** [comment]
@simonpasquier when can this PR merge to the main branch? I am looking for the function that support prometheus RuleGroup Limit.

**Comment by slashpai** [comment]
https://github.com/prometheus-operator/prometheus-operator/issues/5124 this needs to be merged so that I can update it further to do version check

**Comment by simonpasquier** [comment]
@slashpai I guess you meant https://github.com/prometheus-operator/prometheus-operator/pull/5177 which I've just merged :)

Something that would be a natural follow-up is to add a `spec.enforcedGroupLimit` field to the Prometheus and ThanosRuler CRDs (e.g. a way for admins to ensure that user rules don't overload the system).

File: pkg/operator/rules.go [hunk 2]
```diff
@@ -63,11 +64,31 @@ func NewPrometheusRuleSelector(ruleFormat RuleConfigurationFormat, labelSelector
 	}, nil
 }
 
-func generateRulesConfiguration(ruleformat RuleConfigurationFormat, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
-	if ruleformat == PrometheusFormat {
-		// Unset partialResponseStrategy field.
-		for i := range promRule.Groups {
+func generateRulesConfiguration(ruleformat RuleConfigurationFormat, version semver.Version, namespace string, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (JoaoBraveCoding) [inline pkg/operator/rules.go:67]: nit: fewer parameters
```suggestion
func generateRulesConfiguration(ruleformat RuleConfigurationFormat, version semver.Version, promRule monitoringv1.PrometheusRule, logger log.Logger) (string, error) {
```

File: pkg/operator/rules.go [hunk 3]
```diff
@@ -63,11 +64,31 @@ func NewPrometheusRuleSelector(ruleFormat RuleConfigurationFormat, labelSelector
...
+		if ruleformat == PrometheusFormat {
+			if promRule.Groups[i].Limit != 0 {
+				if version.LT(minVersionLimitsProm) {
+					level.Warn(logger).Log("msg", fmt.Sprintf("limit` is supported only from Prometheus version %q", minVersionLimitsProm),
+						"prometheusrule", promRule.Groups[i].Name,
+						"namespace", namespace,
+					)
+				}
+			}
+			// Unset partialResponseStrategy field.
```
Comment (JoaoBraveCoding) [inline pkg/operator/rules.go:81]: This way the `for` loop to me seems simpler, we can then get rid of the else below 
```suggestion
        minVersionLimits := semver.MustParse("2.31.0")
        component := "Prometheus"
        if ruleformat != PrometheusFormat {
           minVersionLimits := semver.MustParse("0.24.0")
           component := "Thanos"
        } 

	for i := range promRule.Groups {
		if promRule.Groups[i].Limit != 0 {
			if version.LT(minVersionLimits) {
				level.Warn(logger).Log("msg", fmt.Sprintf("`limit` is supported only from %s version %q", component, minVersionLimits),
						"prometheusrule", promRule.Groups[i].Name,
						"namespace", namespace,
					)
				}
			}
		if component == "Prometheus" {
			// Unset partialResponseStrategy field.
```

**Comment by JoaoBraveCoding** [comment]
Also, it seems you might have forgotten to run `make format generate`

File: pkg/operator/rules.go (hunk 3 above)
Comment (slashpai) [reply pkg/operator/rules.go:81]: That looks simplified, thanks for the suggestion :)

**Comment by slashpai** [comment]
> Also, it seems you might have forgotten to run `make format generate`

No I did run that. Looks like go version issue since I am using 1.19. I will update to 1.20 and format again

File: pkg/operator/rules.go (hunk 2 above)
Comment (slashpai) [reply pkg/operator/rules.go:67]: I had tried with that but based on how we call  `generateRulesConfiguration()` it is not straight forward :)

File: pkg/operator/rules.go [hunk 4]
```diff
@@ -63,10 +64,25 @@ func NewPrometheusRuleSelector(ruleFormat RuleConfigurationFormat, labelSelector
 	}, nil
 }
 
-func generateRulesConfiguration(ruleformat RuleConfigurationFormat, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
-	if ruleformat == PrometheusFormat {
-		// Unset partialResponseStrategy field.
-		for i := range promRule.Groups {
+func generateRulesConfiguration(ruleformat RuleConfigurationFormat, version semver.Version, namespace string, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:67]: The `version` parameter could be provided in `NewPrometheusRuleSelector()` instead. Also we could pass the version as a string and let `NewPrometheusRuleSelector()` build the semver.Version (since it already knows the flavor, e.g.  Thanos or Prometheus, it should good pick up the good default value).

Comment (slashpai) [reply pkg/operator/rules.go:67]: I initially added like that but I was thinking if version needs to be part of `PrometheusRuleSelector` struct

Comment (slashpai) [reply pkg/operator/rules.go:67]: Do we want version field to be part of  `PrometheusRuleSelecto struct` ?

Comment (slashpai) [reply pkg/operator/rules.go]: Discussed offline and decided to have version field in `PrometheusRuleSelector` struct

File: pkg/operator/rules.go (hunk 2 above)
Comment (slashpai) [reply pkg/operator/rules.go]: Updated

**Comment by slashpai** [comment]
@simonpasquier @JoaoBraveCoding  Addressed review comments

**Review by JoaoBraveCoding — APPROVED** [review]
One small non-blocking nit, apart from that it's a /lgtm from my side

Good job JP! 💪

File: pkg/operator/rules.go [hunk 5]
```diff
@@ -42,31 +43,50 @@ const (
...
 		ruleInformer: ruleInformer,
 		logger:       logger,
 	}, nil
 }
 
-func generateRulesConfiguration(ruleformat RuleConfigurationFormat, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
-	if ruleformat == PrometheusFormat {
-		// Unset partialResponseStrategy field.
-		for i := range promRule.Groups {
+func generateRulesConfiguration(ruleformat RuleConfigurationFormat, version semver.Version, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:74]: do we need to pass again `ruleformat`?

Comment (simonpasquier) [inline pkg/operator/rules.go:74]:
```suggestion
func (pr *PrometheusRuleSelector) generateRulesConfiguration(promRule monitoringv1.PrometheusRuleSpec) (string, error) {
    logger := log.With(pr.logger, "prometheusrule", promRule.Name, "prometheusrule-namespace", promRule.Namespace)
```

File: pkg/operator/rules.go [hunk 6]
```diff
@@ -42,31 +43,50 @@ const (
...
 	nsLabeler    *namespacelabeler.Labeler
 	ruleInformer *informers.ForResource
 	logger       log.Logger
 }
 
-func NewPrometheusRuleSelector(ruleFormat RuleConfigurationFormat, labelSelector *metav1.LabelSelector, nsLabeler *namespacelabeler.Labeler, ruleInformer *informers.ForResource, logger log.Logger) (*PrometheusRuleSelector, error) {
+func NewPrometheusRuleSelector(ruleFormat RuleConfigurationFormat, version string, labelSelector *metav1.LabelSelector, nsLabeler *namespacelabeler.Labeler, ruleInformer *informers.ForResource, logger log.Logger) (*PrometheusRuleSelector, error) {
+	componentVersion, err := semver.ParseTolerant(version)
+	if err != nil {
+		return nil, errors.Wrap(err, "failed to parse Prometheus version")
```
Comment (simonpasquier) [inline pkg/operator/rules.go:56]: (nit) The caller should already log information about the component.
```suggestion
		return nil, errors.Wrap(err, "failed to parse version")
```

File: pkg/operator/rules.go [hunk 7]
```diff
@@ -42,31 +43,50 @@ const (
...
+		component = "Thanos"
+	}
+
+	for i := range promRule.Groups {
+		if promRule.Groups[i].Limit != 0 {
+			if version.LT(minVersionLimits) {
+				level.Warn(logger).Log("msg", fmt.Sprintf("`limit` is supported only from %s version %q", component, minVersionLimits))
+			}
+		}
+		if component == "Prometheus" {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:88]: better to use the const value
```suggestion
		if cr.ruleFormat == PrometheusFormat {
```

File: pkg/operator/rules.go [hunk 8]
```diff
@@ -42,31 +43,50 @@ const (
...
+	minVersionLimits := semver.MustParse("2.31.0")
+	component := "Prometheus"
+	if ruleformat == ThanosFormat {
+		minVersionLimits = semver.MustParse("0.24.0")
+		component = "Thanos"
+	}
+
+	for i := range promRule.Groups {
+		if promRule.Groups[i].Limit != 0 {
+			if version.LT(minVersionLimits) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:84]:
```suggestion
		if promRule.Groups[i].Limit != 0 && version.LT(minVersionLimits) {
			promRule.Groups[i].Limit = 0
```

File: pkg/operator/rules.go [hunk 9]
```diff
@@ -142,7 +162,8 @@ func (pr *PrometheusRuleSelector) Select(namespaces []string) (map[string]string
 			continue
 		}
 
-		content, err = generateRulesConfiguration(pr.ruleFormat, promRule.Spec, pr.logger)
+		pr.logger = log.With(pr.logger, "prometheusrule", promRule.Name, "prometheusrule-namespace", promRule.Namespace)
```
Comment (simonpasquier) [inline pkg/operator/rules.go:165]: this would overwrite the logger field at every loop. See my other comment above to make generateRulesConfiguration() a pointer receiver's method.

File: pkg/operator/rules.go (hunk 5 above)
Comment (slashpai) [reply pkg/operator/rules.go]: We cannot update log like that since promRule is of type monitoringv1.PrometheusRuleSpec and doesnt have the fields Name and Namespace

**Comment by slashpai** [comment]
This is ready for review again :)
cc: @simonpasquier

File: pkg/operator/rules.go [hunk 10]
```diff
@@ -42,40 +43,62 @@ const (
...
 		logger:       logger,
 	}, nil
 }
 
-func generateRulesConfiguration(ruleformat RuleConfigurationFormat, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
-	if ruleformat == PrometheusFormat {
-		// Unset partialResponseStrategy field.
-		for i := range promRule.Groups {
-			promRule.Groups[i].PartialResponseStrategy = ""
+func (pr *PrometheusRuleSelector) generateRulesConfiguration(promRule *monitoringv1.PrometheusRule) (string, error) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:74]:
```suggestion
func (prs *PrometheusRuleSelector) generateRulesConfiguration(promRule *monitoringv1.PrometheusRule) (string, error) {
```

File: pkg/operator/rules.go [hunk 11]
```diff
@@ -42,40 +43,62 @@ const (
...
+
+	if pr.ruleFormat == ThanosFormat {
+		minVersionLimits = semver.MustParse("0.24.0")
+		component = "Thanos"
+	}
+
+	for i := range promRuleSpec.Groups {
+		if promRuleSpec.Groups[i].Limit != 0 {
+			if pr.version.LT(minVersionLimits) {
+				level.Warn(logger).Log("msg", fmt.Sprintf("`limit` is supported only from %s version %q", component, minVersionLimits))
```
Comment (simonpasquier) [inline pkg/operator/rules.go:88]: The limit field should be dropped if the version doesn't support it. 
To catch this case, We need a unit test exercising with Prometheus/Thanos versions not having limit support.

File: pkg/operator/rules.go [hunk 12]
```diff
@@ -42,40 +43,62 @@ const (
...
+	component := "Prometheus"
+
+	if pr.ruleFormat == ThanosFormat {
+		minVersionLimits = semver.MustParse("0.24.0")
+		component = "Thanos"
+	}
+
+	for i := range promRuleSpec.Groups {
+		if promRuleSpec.Groups[i].Limit != 0 {
+			if pr.version.LT(minVersionLimits) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:87]: (nit) a bit simpler to read.
```suggestion
		if promRuleSpec.Groups[i].Limit != 0 && pr.version.LT(minVersionLimits) {
```

**Comment by slashpai** [comment]
@simonpasquier addressed comments

**Review by JoaoBraveCoding — COMMENTED** [review]
one small nit

File: pkg/apis/monitoring/v1/prometheusrule_types.go [hunk 13]
```diff
@@ -70,6 +70,11 @@ type RuleGroup struct {
 	// More info: https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#partial-response
 	// +kubebuilder:validation:Pattern="^(?i)(abort|warn)?$"
 	PartialResponseStrategy string `json:"partial_response_strategy,omitempty"`
+	// Limit the number of alerts an alerting rule and series a recording
+	// rule can produce.
+	// Limit is supported starting with Prometheus >= 2.31 and Thanos Ruler >= 0.24.
+	// +optional
+	Limit int `json:"limit,omitempty"`
```
[the remark this answers is not in the document]
Comment (slashpai) [reply pkg/apis/monitoring/v1/prometheusrule_types.go:77]: why we need a pointer here? 🤔 
I see in [prometheus](https://github.com/prometheus/prometheus/blob/aeecf6854f9daa69c337ba1b406afb83bcaae4f3/model/rulefmt/rulefmt.go#L140) as well they use int

[the remark this answers is not in the document]
Comment (simonpasquier) [reply pkg/apis/monitoring/v1/prometheusrule_types.go:77]: https://github.com/prometheus-operator/prometheus-operator/pull/4999#discussion_r1175278431

> Reflecting on the latest discussions around optional fields (from https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required), we should have a pointer field to signal that the field is optional.

[the remark this answers is not in the document]
Comment (slashpai) [reply pkg/apis/monitoring/v1/prometheusrule_types.go:77]: my bad, I miss read that

**Comment by slashpai** [comment]
should be good now

**Review by simonpasquier — APPROVED** [review]
thanks!
