### PR TITLE
promcfg: Remove web console arguments if prometheus version >= 3

### LINKED ISSUE #7319: Wrong web.console.* settings for prometheus >= 3.0.0
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Description

Values for `web.console.templates` and `web.console.libraries` command line arguments are set to /etc/prometheus/consoles and /etc/prometheus/consoles_libraries. These locations where symlinks in the official prometheus container images until version 3.x With versions >= 3.0.0 these symlinks no longer exist.

### Prometheus Operator Version

```shell
Image:         quay.io/prometheus-operator/prometheus-operator:v0.78.2
    Image ID:      quay.io/prometheus-operator/prometheus-operator@sha256:ec69d3f89a28b16b2f43877eef0cbeeaea124f6b20fe641dc03ff1755bd374bd
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-07-17T00:06:19Z"
  compiler: gc
  gitCommit: 4e4a18878ce330fefda1dc46acca88ba355e9ce7
  gitTreeState: clean
  gitVersion: v1.29.7
  goVersion: go1.22.5
  major: "1"
  minor: "29"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-10-22T20:26:48Z"
  compiler: gc
  gitCommit: 00f20d443ba0cbc485d6ce36a7d3f9a9c4e8ed7a
  gitTreeState: clean
  gitVersion: v1.30.6
  goVersion: go1.22.8
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

yaml manifests

### Manifests

```yaml

```

### prometheus-operator log output

```shell
Not relevant
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Mberga14**
## Description

Fixes #7319

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

Updated the unit TestPrometheusAdditionalArgsNoError unit test that checks for these arguments with both a `v2` and `v3` prometheus config.  

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Remove `web.console.templates` and `web.console.libraries` symlinks in >= v3 prometheus
```

### CODE REVIEW

File: pkg/prometheus/promcfg.go [hunk 1]
```diff
@@ -1102,6 +1102,11 @@ func (cg *ConfigGenerator) BuildCommonPrometheusArgs() []monitoringv1.Argument {
 		{Name: "config.file", Value: path.Join(ConfOutDir, ConfigEnvsubstFilename)},
 	}
 
+	if cg.version.Major >= 3 {
+		// remove web.console.templates and web.console.libraries if prometheus version is 3.0.0 or greater
+		promArgs = promArgs[len(promArgs)-1:]
+	}
```
Comment (simonpasquier) [inline pkg/prometheus/promcfg.go:1108]: (suggestion) I would rather reverse the test 
```suggestion
	if cg.version.Major == 2 {
		// Add web.console.templates and web.console.libraries only if Prometheus version is v2.x.
		promArgs = append(promArgs, {Name: "web.console.templates", Value: "/etc/prometheus/consoles"}, ...)
	}
```

File: pkg/prometheus/server/statefulset_test.go [hunk 2]
```diff
@@ -2353,14 +2351,17 @@ func TestPrometheusAdditionalArgsNoError(t *testing.T) {
 		"--storage.tsdb.no-lockfile",
 	}
 
+	expectedPrometheusArgsV2 := append([]string{"--web.console.templates=/etc/prometheus/consoles",
```
Comment (simonpasquier) [inline pkg/prometheus/server/statefulset_test.go:2354]: I wouldn't mind code duplication in tests. If you want, you can also use table-driven tests with 1 input for v2 and 1 input for v3.

https://go.dev/wiki/TableDrivenTests

Comment (Mberga14) [reply pkg/prometheus/server/statefulset_test.go]: Agreed, refactored so the test is using table driven test.

File: pkg/prometheus/promcfg.go (hunk 1 above)
Comment (Mberga14) [reply pkg/prometheus/promcfg.go]: Flipped the condition
