### PR TITLE
pkg/apis: Add comment on default metrics path

### LINKED ISSUE #4874: No default described for endpoint path
**What happened?**
I looked at the docs and I couldn't find out which path ServiceMonitor used by default

**Did you expect to see something different?**
I expected to see a default

**How to reproduce it (as minimally and precisely as possible)**:
https://prometheus-operator.dev/docs/operator/api/#endpoint

**Environment**
N/A
* Prometheus Operator version:
N/A

* Kubernetes version information:
N/A

* Kubernetes cluster kind:
N/A

* Manifests:
N/A

* Prometheus Operator Logs:
N/A

**Anything else we need to know?**: I assume it's `/metrics`, but there's nothing authoritative that I can find.

### PR DESCRIPTION
**Pull request by slashpai**
Fixes #4874

Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

File: pkg/apis/monitoring/v1/types.go [hunk 1]
```diff
@@ -1135,6 +1135,7 @@ type Endpoint struct {
 	// Name or number of the target port of the Pod behind the Service, the port must be specified with container port property. Mutually exclusive with port.
 	TargetPort *intstr.IntOrString `json:"targetPort,omitempty"`
 	// HTTP path to scrape for metrics.
+	// Defaults to `/metrics`.
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/types.go:1138]:
```suggestion
	// If empty, Prometheus uses the default value (e.g. `/metrics`).
```

Comment (simonpasquier) [reply pkg/apis/monitoring/v1/types.go:1138]: yes please

**Comment by slashpai** [comment]
done

File: pkg/apis/monitoring/v1/types.go [hunk 2]
```diff
@@ -1417,7 +1419,7 @@ type ProberSpec struct {
 	// Defaults to `http`.
 	Scheme string `json:"scheme,omitempty"`
 	// Path to collect metrics from.
-	// Defaults to `/probe`.
+	// If empty, Prometheus uses the default value (e.g. `/probe`).
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1/types.go:1422]: Ah sorry for the incorrect reply. For this one I think we can rely on a default value in the OpenAPI spec since the operator already sets the value [explicitly](https://github.com/prometheus-operator/prometheus-operator/blob/17618aa437b6d284c7d5e310e1ab0eb67d6427c6/pkg/prometheus/promcfg.go#L951-L954).
