### PR TITLE
test: Add ScrapeConfig end to end tests

### LINKED ISSUE #5554: Implement end to end tests for ScrapeConfig
**Context**
This is a follow-up from #5335.

From @ArthurSens (https://github.com/prometheus-operator/prometheus-operator/pull/5335#pullrequestreview-1402538680):
> On follow-up PRs, do you think it would be useful to have e2e tests for the lifecycle of a ScrapeConfig resource? E.g. create/update/delete and make sure Prometheus config is updated correctly?

Test cases to implement:
* Create ScrapeConfig and checking that the scrape job appears in Prometheus
* Update a ScrapeConfig
* Delete a ScrapeConfig and checking that the scrape job disappears from Prometheus
* Starting the operator without the ScrapeConfig CRD and making sure it doesn't crash (#5550)

### PR DESCRIPTION
**Pull request by xiu**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Fixes #5554 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

File: test/e2e/scrapeconfig_test.go [hunk 1]
```diff
@@ -0,0 +1,263 @@
...
+func testPromOperatorStartsWithoutScrapeConfigCRD(t *testing.T) {
+	skipPrometheusTests(t)
+
+	testCtx := framework.NewTestCtx(t)
+	defer testCtx.Cleanup(t)
+	ns := framework.CreateNamespace(context.Background(), t, testCtx)
+	framework.SetupPrometheusRBAC(context.Background(), t, testCtx, ns)
+
+	err := framework.DeleteCRD(context.Background(), "scrapeconfigs.monitoring.coreos.com")
+	require.NoError(t, err)
```
Comment (ArthurSens) [inline test/e2e/scrapeconfig_test.go:236]: Hey, looks like the scrapeConfig CRD was never installed in the first place 😅 

https://github.com/prometheus-operator/prometheus-operator/blob/820c2a1556053f5bd8393107c72a5ed2fc4f1e8d/test/framework/framework.go#L320-L327

I believe this snippet should be installing ScrapeConfig instead of PrometheusAgent

Comment (ArthurSens) [reply test/e2e/scrapeconfig_test.go:236]: Actually it is installing, just the function that checks if it was installed correctly is incorrect

File: test/framework/scrapeconfig.go [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+	return wait.PollUntilContextTimeout(ctx, time.Second, f.DefaultTimeout, false, func(ctx context.Context) (bool, error) {
+		_, err := f.MonClientV1alpha1.ScrapeConfigs(ns).Get(ctx, name, metav1.GetOptions{})
+		if apierrors.IsNotFound(err) {
+			return false, nil
+		} else if err != nil {
+			return false, err
+		}
+		return true, nil
+	})
+}
```
Comment (ArthurSens) [inline test/framework/scrapeconfig.go:79]: Looks like this function isn't used?

File: test/framework/scrapeconfig.go [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+
+func (f *Framework) DeleteScrapeConfig(ctx context.Context, ns string, r string) error {
+	err := f.MonClientV1alpha1.ScrapeConfigs(ns).Delete(ctx, r, metav1.DeleteOptions{})
+	if err != nil {
+		return fmt.Errorf("deleting %v ScrapeConfig rule in namespace %v failed: %v", r, ns, err.Error())
+	}
+
+	return nil
+}
```
Comment (ArthurSens) [inline test/framework/scrapeconfig.go:105]: Same thing here, could find where it is used 🤔

File: test/e2e/scrapeconfig_test.go [hunk 4]
```diff
@@ -0,0 +1,263 @@
...
+	"k8s.io/apimachinery/pkg/fields"
+	"k8s.io/apimachinery/pkg/util/wait"
+
+	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
+	monitoringv1alpha1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1"
+)
+
+// testScrapeConfigCreation tests multiple ScrapeConfig definitions
+func testScrapeConfigCreation(t *testing.T) {
+	skipPrometheusTests(t)
```
Comment (JoaoBraveCoding) [inline test/e2e/scrapeconfig_test.go:34]: nit: I'm not sure this validation should be here since this test will be part of `testAllNSPrometheus`. No other test in this group has this check AFAICS.

File: test/e2e/scrapeconfig_test.go [hunk 5]
```diff
@@ -0,0 +1,263 @@
...
+			_, err := framework.MonClientV1alpha1.ScrapeConfigs(ns).Create(context.Background(), sc, metav1.CreateOptions{})
+
+			if err == nil {
+				require.Falsef(t, test.expectedError, "expected error but got nil")
+				return
+			}
+
+			require.Truef(t, apierrors.IsInvalid(err), "expected Invalid error but got %v", err)
+
+			require.True(t, test.expectedError)
```
Comment (JoaoBraveCoding) [inline test/e2e/scrapeconfig_test.go:123]: WDYT if we change it like this? What prompted my comment was this principle https://gist.github.com/adamveld12/c0d9f0d5f0e1fba1e551#indent-error-flow
```suggestion
			if test.expectedError {
			        require.Error(t, err)		
  				require.Truef(t, apierrors.IsInvalid(err), "expected Invalid error but got %v", err)
				return
			}
			require.NoError(t, err)
			require.Falsef(t, test.expectedError, "expected error but got nil")
```

File: test/e2e/scrapeconfig_test.go [hunk 6]
```diff
@@ -0,0 +1,263 @@
...
+		if len(targets) != 3 {
+			return false, nil
+		}
+
+		return true, nil
+	})
+	require.NoError(t, err)
+
+	// 3. Remove the ScrapeConfig and check that the targets disappear in Prometheus
+	err = framework.MonClientV1alpha1.ScrapeConfigs(ns).Delete(context.Background(), "scrape-config", metav1.DeleteOptions{})
```
Comment (JoaoBraveCoding) [inline test/e2e/scrapeconfig_test.go:206]: Here we could use `DeleteScrapeConfig`

**Review by JoaoBraveCoding — COMMENTED** [review]
just some small comments

File: test/e2e/scrapeconfig_test.go (hunk 1 above)
Comment (xiu) [reply test/e2e/scrapeconfig_test.go:236]: @ArthurSens I'm not sure I follow. Do you mean that `WaitForCRDReady` is not working as intended?

File: test/e2e/scrapeconfig_test.go (hunk 5 above)
Comment (xiu) [reply test/e2e/scrapeconfig_test.go]: lgtm!

File: test/framework/scrapeconfig.go (hunk 2 above)
Comment (xiu) [reply test/framework/scrapeconfig.go:79]: removed it

File: test/framework/scrapeconfig.go (hunk 3 above)
Comment (xiu) [reply test/framework/scrapeconfig.go:105]: just switched to using it in the last commit 😅

File: test/e2e/scrapeconfig_test.go (hunk 4 above)
Comment (xiu) [reply test/e2e/scrapeconfig_test.go:34]: switched to skipPrometheusAllNSTests :+1:

File: test/e2e/scrapeconfig_test.go (hunk 1 above)
Comment (ArthurSens) [reply test/e2e/scrapeconfig_test.go:235]: Yes, because you're checking for PrometheusAgent instead of ScrapeConfig 😅 

Probably just a copy paste mistake

Comment (xiu) [reply test/e2e/scrapeconfig_test.go:235]: oooooh indeed 😅 ``` 		return f.MonClientV1alpha1.PrometheusAgents(v1.NamespaceAll).List(ctx, opts) ```

Thanks!

**Comment by xiu** [comment]
We should be good to merge now :)

File: test/e2e/scrapeconfig_test.go [hunk 7]
```diff
@@ -0,0 +1,262 @@
...
+		{
+			Targets: []monitoringv1alpha1.Target{"target1:9090", "target2:9090"},
+		},
+	}
+	_, err = framework.CreateScrapeConfig(context.Background(), ns, sc)
+	require.NoError(t, err)
+
+	// Check that the targets appear in Prometheus
+	err = wait.PollUntilContextTimeout(context.Background(), 5*time.Second, 2*time.Minute, false, func(ctx context.Context) (bool, error) {
+		targets, pollErr := framework.GetActiveTargets(ctx, ns, "prometheus-operated")
```
Comment (simonpasquier) [inline test/e2e/scrapeconfig_test.go:163]: can it use `WaitForActiveTargets` instead?

Comment (xiu) [reply test/e2e/scrapeconfig_test.go]: Oh, very nice! 👍  Done in 604686b0611e2b676b49c48e18c4a736d57ac5ca

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm

**Review by simonpasquier — APPROVED** [review]

**Comment by simonpasquier** [comment]
:shipit:
