### PR TITLE
alertmanager: Support Slack webhook URL via file path in config

### LINKED ISSUE #4045: slack_api_url_file value is missing
**What happened?**

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

Use config from here: 
https://github.com/prometheus/alertmanager/commit/59c7fd5053d503037702ad10e4a733aac89e615a

* Prometheus Operator Logs:

```
failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 2: field slack_api_url_file not found in type config.plain"
```

**Anything else we need to know?**:

the file to change is : https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/alertmanager/types.go

The code changes are: 

line 54 : SlackAPIURLFile  string          `yaml:"slack_api_url_file,omitempty" json:"slack_api_url_file,omitempty"`

line158: 	APIURLFile    string            `yaml:"api_url_file,omitempty" json:"api_url_file,omitempty"`

### PR DESCRIPTION
**Pull request by PhilipGough**
## Description

This change supports https://github.com/prometheus/alertmanager/pull/2534 in the managed secret and allows config to accept the Slack webhook URL as a file path.

Fixes #4045 

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry
_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Adds `slack_api_url_file` globally and `api_url_file` in Slack config to the managed secret to support reading URL from file
```

### CODE REVIEW

**Comment by PhilipGough** [comment]
Supersedes and Closes #4092

File: pkg/alertmanager/operator.go [hunk 1]
```diff
@@ -1141,14 +1162,18 @@ func checkOpsGenieConfigs(ctx context.Context, configs []monitoringv1alpha1.OpsG
...
+func checkSlackConfigs(ctx context.Context, configs []monitoringv1alpha1.SlackConfig, namespace string, key string, store *assets.Store, version semver.Version) error {
 	for i, config := range configs {
 		slackConfigKey := fmt.Sprintf("%s/slack/%d", key, i)
 
 		if config.APIURL != nil {
 			if _, err := store.GetSecretKey(ctx, namespace, *config.APIURL); err != nil {
 				return err
 			}
+		} else {
+			if config.APIURLFile != "" && !allowFileURL(version) {
```
Comment (fpetkovski) [inline pkg/alertmanager/operator.go:1174]: I think this could be an `else if` for slightly better readability.

**Review by fpetkovski — COMMENTED** [review]
Just one tiny nit from my side, everything else looks very good :+1:

**Review by simonpasquier — COMMENTED** [review]
Rather than failing when the Alertmanager's version doesn't support the new field, we should fallback and not inject the value into the final configuration. This would be consistent with how the Prometheus controller handles such situations.
If you want to have a look, #4110 is implementing something similar (though for a different purpose).

File: pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go [hunk 2]
```diff
@@ -225,6 +225,10 @@ type SlackConfig struct {
 	// object and accessible by the Prometheus Operator.
 	// +optional
 	APIURL *v1.SecretKeySelector `json:"apiURL,omitempty"`
+	// The file path to read a file which contains the Slack webhook URL.
+	// Ignored if apiURL is set
+	// +optional
+	APIURLFile string `json:"apiUrlFile,omitempty"`
```
Comment (simonpasquier) [inline pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go:231]: One issue I see with supporting `APIURLFile` for AlertmanagerConfig resources is that someone can potentially send  notifications to a Stack URL which they didn't provide. The risk is low though because you have to know the file's path in the Alertmanager container. Still it would be a precedent (currently any sensitive material is only referenced via `v1.SecretKeySelector`) and it breaks the kind of isolation we're aiming for with AlertmanagerConfig.

Comment (PhilipGough) [reply pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go]: Noted, reverted this and moved it so that it can be read from the secret only. Thanks

File: pkg/alertmanager/amcfg.go [hunk 3]
```diff
@@ -127,6 +129,52 @@ func (cg *configGenerator) generateConfig(
 	return yaml.Marshal(baseConfig)
 }
 
+// sanitizeBaseConfig checks provided config is valid for the version it is being
+// generated against - strips fields from config is unsupported
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go:133]: I suppose
```suggestion
// generated against - strips fields from config if unsupported
```

File: pkg/alertmanager/amcfg.go [hunk 4]
```diff
@@ -127,6 +129,52 @@ func (cg *configGenerator) generateConfig(
...
+			msg := "slack_api_url_file supported in AlertManager >= 0.22 only - dropping field from provided config"
+			level.Warn(cg.logger).Log("msg", msg, "current_version", cg.amVersion.String())
+			amConf.Global.SlackAPIURLFile = ""
+		}
+	}
+
+	if amConf.Receivers == nil {
+		return
+	}
+
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go:158]: It would work equally since a nil slice is equivalent to an empty slice for `range`

```suggestion
```

File: pkg/alertmanager/amcfg.go [hunk 5]
```diff
@@ -127,6 +129,52 @@ func (cg *configGenerator) generateConfig(
...
+	for i, globalReceiver := range amConf.Receivers {
+		for j, slackConfig := range globalReceiver.SlackConfigs {
+			if slackConfig.APIURL != nil && slackConfig.APIURLFile != "" {
+				msg := "api_url and api_url_file are mutually exclusive for slack receiver config - api_url has been preferred"
+				level.Warn(cg.logger).Log("msg", msg)
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go:163]:
```suggestion
				level.Warn(cg.logger).Log("msg", msg, "receiver", amConf.Receivers[i].Name)
```

File: pkg/alertmanager/amcfg.go [hunk 6]
```diff
@@ -127,6 +129,52 @@ func (cg *configGenerator) generateConfig(
...
+				amConf.Receivers[i].SlackConfigs[j].APIURLFile = ""
+				continue
+			}
+
+			if slackConfig.APIURLFile != "" && !fileURLAllowed {
+				msg := "api_url_file supported in AlertManager >= 0.22 only - dropping field from provided config"
+				level.Warn(cg.logger).Log("msg", msg, "current_version", cg.amVersion.String())
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go:170]: ditto about logging the receiver's name

File: pkg/alertmanager/amcfg.go (hunk 4 above)
Comment (PhilipGough) [reply pkg/alertmanager/amcfg.go]: indeed :)

File: pkg/alertmanager/amcfg.go [hunk 7]
```diff
@@ -127,6 +129,48 @@ func (cg *configGenerator) generateConfig(
...
+		}
+
+		if amConf.Global.SlackAPIURLFile != "" && !fileURLAllowed {
+			msg := "slack_api_url_file supported in AlertManager >= 0.22 only - dropping field from provided config"
+			level.Warn(cg.logger).Log("msg", msg, "current_version", cg.amVersion.String())
+			amConf.Global.SlackAPIURLFile = ""
+		}
+	}
+
+	for i, globalReceiver := range amConf.Receivers {
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go:155]: (nit)
```suggestion
	for i, receiverConfig := range amConf.Receivers {
```

**Review by simonpasquier — COMMENTED** [review]
it looks like it's breaking the generated config from what the e2e tests say.

**Review by simonpasquier — COMMENTED** [review]
I've just realized that  in a different code path, we're sanitizing the configuration for the `authorization` field but it only applies to the `AlertmanagerConfig` resources (e.g. you can declare an `authorization` key in the raw secret while the Alertmanager version doesn't support it and thus break Alertmanager).
Moving forward I think it makes sense to sanitize the configuration only once once, that is when we've merged the base configuration with the `AlertmanagerConfig` objects. What do you think?

https://github.com/prometheus-operator/prometheus-operator/blob/7925986b5e53ea40413d74ae221603e26f2b3d50/pkg/alertmanager/amcfg.go#L821-L836

**Comment by PhilipGough** [comment]
@simonpasquier make sense, will refactor based on that suggestion

File: pkg/alertmanager/amcfg.go [hunk 8]
```diff
@@ -869,3 +864,78 @@ func (cg *configGenerator) convertTLSConfig(ctx context.Context, in *monitoringv
...
+				slackConfig.APIURLFile = ""
+			}
+		}
+	}
+}
+
+// sanitize globalConfig - gc must not be nil
+func (gc *globalConfig) sanitize(amVersion semver.Version, logger log.Logger) {
+	if gc.HTTPConfig != nil {
+		gc.HTTPConfig.sanitize(amVersion, logger)
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go:906]: we need to sanitize all `*httpClientConfig` fields (e.g. for all receivers).

File: pkg/alertmanager/amcfg.go [hunk 9]
```diff
@@ -869,3 +864,78 @@ func (cg *configGenerator) convertTLSConfig(ctx context.Context, in *monitoringv
...
+
+// sanitize httpClientConfig - hc must not be nil
+func (hc *httpClientConfig) sanitize(amVersion semver.Version, logger log.Logger) {
+	if hc.BasicAuth != nil {
+		msg := "'basicAuth' and 'authorization' are mutually exclusive, 'basicAuth' has taken precedence"
+		level.Warn(logger).Log("msg", msg)
+		hc.Authorization = nil
+	}
+
+	if httpAuthzAllowed := amVersion.GTE(semver.MustParse("0.22.0")); !httpAuthzAllowed {
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go:936]: need to check for `hc.Authorization != nil`?

File: pkg/alertmanager/amcfg.go (hunk 8 above)
Comment (PhilipGough) [reply pkg/alertmanager/amcfg.go:906]: I missed that they all had that conf :/

**Comment by simonpasquier** [comment]
Thanks!
