### PR TITLE
Fixes ThanoRuler StatefulSet re-creation bug

### LINKED ISSUE #5317: Thanos ruler statefulset getting repeatedly re-created
**What happened?**

When we specify more than one label `ThanosRuler.Spec.Labels`, the StatefulSet starts getting re-created repeatedly. This happens because prometheus-operator goes through the map of labels without any order which then results in the arguments of the thanos ruler container always changing which leads to prometheus-operator always recreating the StatefulSet unless it computed the thanos ruler arguments in the same order

Related issue: https://issues.redhat.com/browse/OCPBUGS-6055

**Did you expect to see something different?**

The computation of the thanos ruler arguments should always be done in the same order

**How to reproduce it (as minimally and precisely as possible)**:

Specify multiple labels in `ThanosRuler.Spec.Labels`

**Environment**

* Prometheus Operator version:

    `0.62.0 / 2023-01-04`

* Kubernetes version information:

    `not relevant`
    

* Kubernetes cluster kind:

    not relevant

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
Signed-off-by: JoaoBraveCoding <jmarcal@redhat.com>

## Description

Issue: fixes #5317

Problem: see issue #5317

Solution: add arguments to Thanos container by iterating over the sorted list of the keys of the map ThanosRuler.Spec.Labels

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [X] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
- fixes ThanoRuler StatefulSet re-creation bug if labels specified
```

### CODE REVIEW

File: pkg/thanos/statefulset.go [hunk 1]
```diff
@@ -192,8 +192,10 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
 	trVolumeMounts := []v1.VolumeMount{}
 
 	trCLIArgs = append(trCLIArgs, monitoringv1.Argument{Name: "label", Value: fmt.Sprintf(`%s="$(POD_NAME)"`, defaultReplicaLabelName)})
-	for k, v := range tr.Spec.Labels {
-		trCLIArgs = append(trCLIArgs, monitoringv1.Argument{Name: "label", Value: fmt.Sprintf(`%s="%s"`, k, v)})
+	labels := operator.Labels{LabelsMap: tr.Spec.Labels}
+	sortedKeys := labels.SortedKeys()
+	for _, k := range sortedKeys {
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:197]: nit
```suggestion
	for _, k := range labels.SortedKeys() {
```

**Review by simonpasquier — COMMENTED** [review]
just 2 minor comments otherwise lgtm

**Review by simonpasquier — APPROVED** [review]
:+1:
