### PR TITLE
#3623: Fix usage of --prometheus-default-base-image, --alertmanager-default-base-image, --thanos-default-base-image

### LINKED ISSUE #3623: The --prometheus-default-base-image flag (and others) doesn't work
Hello, I want to install Prometheus form a private registry, I have replaced two value  in `bundle.yaml`:
```
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --prometheus-config-reloader=registry.local:9050/quay.io/prometheus-operator/prometheus-config-reloader:v0.42.1
        image: registry.local:9050/quay.io/prometheus-operator/prometheus-operator:v0.42.1
```
but after deploying, Prometheus generate two docker image that I don't know how can I replace them with my private docker images, these are images name:

- quay.io/prometheus/prometheus
- jimmidyson/configmap-reload:v0.4.0
is that any way to deploy Prometheus with private repository images?

### PR DESCRIPTION
**Pull request by nrchakradhar**
Closes #3623

### CODE REVIEW

**Comment by nrchakradhar** [comment]
I ran the new tests written by me and they passed. In CI, I am getting the following error:

ok  	github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1	0.035s
?   	github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1	[no test files]
FAIL
Makefile:242: recipe for target 'test-unit' failed

Not sure why? Please help.

**Comment by simonpasquier** [comment]
@nrchakradhar some tests failed to build because of a function signature change. It can be better found in the [raw logs](https://pipelines.actions.githubusercontent.com/vPMnvJjkGBteTBBeHIuBuscIAxYyVzD3ZDtsis3lp8F0MLY5xH/_apis/pipelines/1/runs/375/signedlogcontent/15?urlExpires=2020-11-03T07%3A48%3A37.6609174Z&urlSigningMethod=HMACV1&urlSignature=tI%2BHEoASL6PkrA6H%2FCKCJKHdFLspfQuYixY0k%2FF8TKA%3D):

```
2020-11-02T17:55:20.5795997Z # github.com/prometheus-operator/prometheus-operator/pkg/prometheus [github.com/prometheus-operator/prometheus-operator/pkg/prometheus.test]
2020-11-02T17:55:20.5797669Z pkg/prometheus/statefulset_test.go:670:30: not enough arguments in call to makeStatefulSet
2020-11-02T17:55:20.5799401Z 	have ("github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1".Prometheus, *operator.Config, nil, string)
2020-11-02T17:55:20.5801167Z 	want (string, "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1".Prometheus, *operator.Config, []string, string, int32)
2020-11-02T17:55:20.5802657Z pkg/prometheus/statefulset_test.go:703:30: not enough arguments in call to makeStatefulSet
2020-11-02T17:55:20.5803905Z 	have ("github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1".Prometheus, *operator.Config, nil, string)
2020-11-02T17:55:20.5805546Z 	want (string, "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1".Prometheus, *operator.Config, []string, string, int32)
2020-11-02T17:55:21.1529665Z === RUN   TestBuildImagePath
2020-11-02T17:55:21.1531126Z --- PASS: TestBuildImagePath (0.00s)
2020-11-02T17:55:21.1531774Z === RUN   TestNewTLSConfig
2020-11-02T17:55:21.1532519Z --- PASS: TestNewTLSConfig (0.00s)
2020-11-02T17:55:21.1533260Z PASS
2020-11-02T17:55:21.1534185Z ok  	github.com/prometheus-operator/prometheus-operator/pkg/operator	0.066s
2020-11-02T17:55:21.1535536Z FAIL	github.com/prometheus-operator/prometheus-operator/pkg/prometheus [build failed]
```

**Comment by nrchakradhar** [comment]
Thanks @simonpasquier . I missed the merges that had happened. I had made changes in another branch and that was not having shards.

File: pkg/alertmanager/statefulset.go [hunk 1]
```diff
@@ -210,7 +210,7 @@ func makeStatefulSetSpec(a *monitoringv1.Alertmanager, config Config) (*appsv1.S
 	// details see https://github.com/prometheus-operator/prometheus-operator/issues/1659
 	a = a.DeepCopy()
 
-	amBaseImage := operator.StringValOrDefault(a.Spec.BaseImage, operator.DefaultAlertmanagerBaseImage)
+	amBaseImage := operator.StringValOrDefault(a.Spec.BaseImage, config.AlertmanagerDefaultBaseImage)
```
Comment (simonpasquier) [inline pkg/alertmanager/statefulset.go:213]: I've noticed that we're not consistent across the code base on when we call `operator.BuildImagePath()`: like here we call it before overriding the default image's path with `Spec.Image` (if it isn't empty), in other places like [prometheus](https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/prometheus/statefulset.go#L320-L327) we call `operator.BuildImagePath()` after overriding.

cc @brancz @s-urbaniak @lilic

File: pkg/prometheus/statefulset_test.go [hunk 2]
```diff
@@ -650,6 +650,75 @@ func TestTagAndShaAndVersion(t *testing.T) {
 	}
 }
 
+func TestPrometheusDefaultBaseImageFlag(t *testing.T) {
```
Comment (simonpasquier) [inline pkg/prometheus/statefulset_test.go:653]: I'd like to see more tests to cover the various combinations. [Table-driven tests](https://github.com/golang/go/wiki/TableDrivenTests) would reduce duplication. I have [something](https://github.com/simonpasquier/prometheus-operator/blob/6d4136af478965acb85cb7bf6f3b499bb9986dc7/pkg/alertmanager/statefulset_test.go#L450) in a branch of my personal fork (I started to work on the fix but I didn't have time to finish), feel free to have a look and get inspiration.

**Review by simonpasquier — COMMENTED** [review]
Nice start! [Thanos ruler](https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/thanos/statefulset.go#L155-L162) would need an update too.

**Comment by nrchakradhar** [comment]
> Nice start! [Thanos ruler](https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/thanos/statefulset.go#L155-L162) would need an update too.

Yes. My bad. I missed it. I will add.

File: pkg/prometheus/statefulset_test.go (hunk 2 above)
Comment (nrchakradhar) [reply pkg/prometheus/statefulset_test.go:653]: Sure. I will have a look and try to put a separate PR.

File: pkg/alertmanager/statefulset.go (hunk 1 above)
Comment (lilic) [reply pkg/alertmanager/statefulset.go:213]: Interesting, yeah the `operator.BuildImagePath ` is meant to be used to create the image path so we should be consistent in using it, agreed.

File: pkg/prometheus/statefulset_test.go (hunk 2 above)
Comment (nrchakradhar) [reply pkg/prometheus/statefulset_test.go:653]: Prometheus:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/prometheus/statefulset.go#L320-L324

Additional Thanos in Prometheues:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/prometheus/statefulset.go#L686-L698

Alertmanager:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/alertmanager/statefulset.go#L213-L223

Thanos:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/thanos/statefulset.go#L155-L162

Which pattern above is to be used across all?
SHA and Tag is not available for the Thanos - not sure why?

File: pkg/alertmanager/statefulset.go (hunk 1 above)
Comment (nrchakradhar) [reply pkg/alertmanager/statefulset.go:213]: Prometheus:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/prometheus/statefulset.go#L320-L324

Additional Thanos in Prometheues:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/prometheus/statefulset.go#L686-L698

Alertmanager:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/alertmanager/statefulset.go#L213-L223

Thanos:
https://github.com/prometheus-operator/prometheus-operator/blob/30b03e839a460ef230256873c10ad56f9a5abd37/pkg/thanos/statefulset.go#L155-L162

Which pattern above is to be used across all?
SHA and Tag is not available for the Thanos - not sure why?

Comment (simonpasquier) [reply pkg/alertmanager/statefulset.go:213]: Thanos doesn't have SHA and tag values because these fields have been deprecated for Alertmanager and Prometheus before the Thanos Ruler CRD exists.

This is the API documentation of the `Image` field:

```
Image if specified has precedence over baseImage, tag and sha combinations. Specifying the version is still necessary to ensure the Prometheus Operator knows what version of Prometheus is being configured.
```

I'd say that the operator should pick the value of `Image` unmodified if it isn't empty otherwise it should construct the image path from `BaseImage` + `SHA` + `Tag`. Which would be more or less the implementation for Alertmanager except that it shouldn't even call `BuildImagePath()` if `Image` isn't empty. But lets hear what other maintainers think :)

Comment (nrchakradhar) [reply pkg/alertmanager/statefulset.go:213]: gentle ping to @lilic @brancz @s-urbaniak Please let me know your agreement or otherwise with @simonpasquier comments above. I can make the changes and commit them.

**Comment by MartyD24** [comment]
Hi guys, we desperatly need this, when do you plan to merge into master-branch? We would need a working "--prometheus-default-base-image". Thx in Advance. And keep up the good work !!!!

File: pkg/alertmanager/statefulset.go (hunk 1 above)
Comment (lilic) [reply pkg/alertmanager/statefulset.go:213]: > Which would be more or less the implementation for Alertmanager except that it shouldn't even call BuildImagePath() if Image isn't empty.

yes that sounds good for me, we could just put that logic in the BuildImagePath function and just call that, or is there anything specific to Alertmanager @simonpasquier ?

Comment (simonpasquier) [reply pkg/alertmanager/statefulset.go:213]: > is there anything specific to Alertmanager?

Not that I know of.

Comment (lilic) [reply pkg/alertmanager/statefulset.go:213]: Then I would prefer if we do it the same for both Prometheus and alertmanager, so lets adjust the BuildImagePath function, does that sound good?

Comment (nrchakradhar) [reply pkg/alertmanager/statefulset.go:213]: I have made a new function in image.go. Please check if its fine. I can make changes in other places as well and submit the fix for final apporval

Comment (simonpasquier) [reply pkg/alertmanager/statefulset.go:213]: I think that @lilic's idea was to pass `a.Spec.Image` as an additional parameter to `BuildImagePath()` and return it unmodified if it isn't empty. The rest of `BuildImagePath()` would stay the same. And in this code we can remove any `if` statements:

```
amImagePath, err := operator.BuildImagePath(
    operator.StringPtrValOrDefault(a.Spec.Image, ""), // image path from path.
    operator.StringValOrDefault(a.Spec.BaseImage, config.AlertmanagerDefaultBaseImage), // base image path from spec or from operator's config.
    operator.StringValOrDefault(a.Spec.Version, operator.DefaultAlertmanagerVersion), // version from spec or operator's default.
    operator.StringValOrDefault(a.Spec.Tag, ""), // tag from spec.
    operator.StringValOrDefault(a.Spec.SHA, ""), // SHA from spec.
)
```

Comment (nrchakradhar) [reply pkg/alertmanager/statefulset.go:213]: Passing a.Spec.Image as additional argument is fine with me. I think that by passing additional arguments, we can avoid calling operator.StringValOrDefault till the time its really made use of. Does that make sense?

Comment (lilic) [reply pkg/alertmanager/statefulset.go:213]: Yes sorry for not being specific enough, exactly what Simon said is what I had in mind. This would be the central function to decide on image building path then.

Comment (nrchakradhar) [reply pkg/alertmanager/statefulset.go:213]: The types for members which have same name in different specs are NOT consistent between different specs. This is making the `BuildImagePath `to be not useful consistently and also making code a little messy.
Example
Image is **pointer to string** in PrometheusSpec , but **plain string** in ThanosRulerSpec .
Similarly, BaseImage is **plain string** in PrometheusSpec , but **pointer to string** in ThanosSpec.
ThanosSpec has everything as pointer to string :confused:
```
type PrometheusSpec struct {
Version string
Tag string
SHA string
Image *string
BaseImage string
....
}
```

```
type AlertmanagerSpec struct {
Image *string
Version string
Tag string
SHA string
BaseImage string
...
}
```
```
type ThanosRulerSpec struct {
	Image string
...
```

```
type ThanosSpec struct {
Image *string
Version *string
Tag *string
SHA *string
BaseImage *string
...
}
```
I would propose to modify all Spec to have one set of types aligned to PrometheusSpec.
AlertManagerSpec is already aligned.

```
type ThanosRulerSpec struct {
	Image *string
...
```

```
type ThanosSpec struct {
Image *string
Version string
Tag string
SHA string
BaseImage string
...
}
```
With this, BuildImagePath will be consistently usable. Will this have any side effects? I can make the changes and see whether CI tests pass or not. If there are any early WARNINGs please let me know. :hand:

Comment (simonpasquier) [reply pkg/alertmanager/statefulset.go:213]: `BuildImagePath()` only deals with values and not pointers. I'm fine with the caller doing the conversion using `operator.StringPtrValOrDefault() or `operator.StringValOrDefault()` as needed. Does it make sense?

Comment (nrchakradhar) [reply pkg/alertmanager/statefulset.go:213]: Fine.  Let me make changes accordingly. I would still feel that aligning all the types across spec's will make code even simpler and consistent. It can be done in another PR. I can create an issue for the same if there is agreement.

Comment (lilic) [reply pkg/alertmanager/statefulset.go:213]: If by spec you mean the user facing API, we cannot and should not change those, we need to workaround those in code.

Comment (nrchakradhar) [reply pkg/alertmanager/statefulset.go]: By spec, I am referring to types defined in pkg/apis/monitoring/v1/types.go for PrometheusSpec, AlertManagerSpec, and ThanosSpec

**Comment by nrchakradhar** [comment]
@simonpasquier @lilic PTAL.

File: pkg/thanos/statefulset.go [hunk 3]
```diff
@@ -152,14 +152,13 @@ func makeStatefulSetSpec(tr *monitoringv1.ThanosRuler, config Config, ruleConfig
 		return nil, errors.New(tr.GetName() + ": thanos ruler requires query config or at least one query endpoint to be specified")
 	}
 
-	trBaseImage := operator.StringValOrDefault(config.ThanosDefaultBaseImage, operator.DefaultThanosBaseImage)
-	trImagePath, err := operator.BuildImagePath(trBaseImage, operator.DefaultThanosVersion, "", "")
+	trImagePath, err := operator.BuildImagePath(
+		tr.Spec.Image,
+		operator.StringValOrDefault(config.ThanosDefaultBaseImage, operator.DefaultThanosBaseImage),
+		operator.DefaultThanosVersion, "", "")
```
Comment (simonpasquier) [inline pkg/thanos/statefulset.go:158]:
```suggestion
	trImagePath, err := operator.BuildImagePath(
		tr.Spec.Image,
		operator.StringValOrDefault(config.ThanosDefaultBaseImage, operator.DefaultThanosBaseImage),
		operator.DefaultThanosVersion,
		"",
		"",
	)
```

**Review by simonpasquier — COMMENTED** [review]
A few nits otherwise LGTM

**Review by simonpasquier — APPROVED** [review]
lgtm, I'll let @lilic have a final look and merge at will.

**Review by lilic — APPROVED** [review]
Great work, thanks!

🎉
