### PR TITLE
Fix: One Alertmanager Config failing blocks all others.

### LINKED ISSUE #6532: One AlertmanagerConfig failing to sync, blocks all others
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

In our multi-tenant clusters, we have many users deploying their own `AlertmanagerConfig` objects in their namespaces, and they all get synced to a central Alertmanager.

If in namespace we create a `AlertmanagerConfig` Object that for some reason fails to get synced to the managed Alertmanager, then the Operator will **NOT** ignore it and try and load other newly created `AlertmanagerConfig` Objects coming in from other namespaces.

For example, we heavily work with Slack receivers. If for the URL secret, the value has any issues the Prometheus Operator fails to sync the `AlertmanagerConfig` reporting the following error:

```
level=error ts=2024-04-19T07:26:08.458451375Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring-system/kps-alertmanager\" failed: provision alertmanager configuration: failed to generate Alertmanager configuration: AlertmanagerConfig test/slack-receiver: SlackConfig[0]: invalid URL \"'https://hooks.slack.com/services/XXX/XXX/XXX'\" in key \"url\" from secret \"slackapiurl-secret\": validate url from string failed for 'https://hooks.slack.com/services/XXX/XXX/XXX': parse \"'https://hooks.slack.com/services/XXX/XXX/XXX'\": first path segment in URL cannot contain colon"
```

This error seems to block Prometheus Operator from syncing any other valid `AlertmanagerConfig` Objects.

## Steps to Reproduce

1. Create namespace "test";

```sh
kubectl create ns test
```

2. Create a secret inside that namespace with a improperly formatted Slack URL endpoint

```sh
kubectl -n test create secret generic  slackapiurl-secret --from-literal=url=\'https://hooks.slack.com/services/XXX/XXX/XXX\'
```

3. Create a standard `AlertmanagerConfig` with a Slack Receiver\Route using the above created secret

```sh
cat <<EOF | kubectl apply -f -
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-receiver
  namespace: test
spec:
  inhibitRules:
  - equal:
    - alertname
    sourceMatch:
    - name: 'severity'
      value: 'critical'
      matchType: '='
    targetMatch:
    - name: 'severity'
      value: 'warning'
      matchType: '='
  receivers:
  - name: SlackAlerts
    slackConfigs:
      - channel: '#slack-channel-example'
        apiURL:
          name: slackapiurl-secret
          key: url
        sendResolved: true
  route:
    receiver: 'SlackAlerts'
    groupBy: [cluster_short, alertname]
    groupWait: 60s
    groupInterval: 15m
    repeatInterval: 4h
    continue: true
EOF
```

4. Check the Operator Logs and confirm that indeed it's failing to sync this new config

```sh
kubectl -n monitoring-system logs -l app.kubernetes.io/component=prometheus-operator | grep level=error

level=error ts=2024-04-19T07:26:08.458451375Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring-system/kps-alertmanager\" failed: provision alertmanager configuration: failed to generate Alertmanager configuration: AlertmanagerConfig test/slack-receiver: SlackConfig[0]: invalid URL \"'https://hooks.slack.com/services/XXX/XXX/XXX'\" in key \"url\" from secret \"slackapiurl-secret\": validate url from string failed for 'https://hooks.slack.com/services/XXX/XXX/XXX': parse \"'https://hooks.slack.com/services/XXX/XXX/XXX'\": first path segment in URL cannot contain colon"
```

5. Repeat steps 1 to 3 on a new namespace, but this time, on step 2, create a valid secret. For example:

```sh
kubectl create ns test2 
kubectl -n test2 create secret generic  slackapiurl-secret --from-literal=url=https://hooks.slack.com/services/XXX/XXX/XXX
```

6. Check The Operator logs and we wont see any reference of the proper `AlertmanagerConfig` Object getting synced to Alertmanager. Going to the Web Ui Status page also confirms that no new configuration got generated.

## Expected Result

The Operator should "ignore" or bypass the failing `AlertmanagerConfig` Object sync, and proceed with syncing other valid available resources.

## Actual Result

The Operator fails to sync any other `AlertmanagerConfig` Object as soon as a single one fails to get synced properly into Alertmanager.

### Prometheus Operator Version

```shell
**Operator Image being used**: quay.io/prometheus-operator/prometheus-operator:v0.73.1
```

### Kubernetes Version

```yaml
v1.28.5
```

### Kubernetes Cluster Type

kubeadm

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

_No response_

### prometheus-operator log output

```shell
level=error ts=2024-04-19T07:26:08.458451375Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring-system/kps-alertmanager\" failed: provision alertmanager configuration: failed to generate Alertmanager configuration: AlertmanagerConfig test/slack-receiver: SlackConfig[0]: invalid URL \"'https://hooks.slack.com/services/XXX/XXX/XXX'\" in key \"url\" from secret \"slackapiurl-secret\": validate url from string failed for 'https://hooks.slack.com/services/XXX/XXX/XXX': parse \"'https://hooks.slack.com/services/XXX/XXX/XXX'\": first path segment in URL cannot contain colon"
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by codeknight03**
## Description
We need to validate the urls passed as secrets in AlertManagerConfig receivers ( Slack and Discord in particular) to ensure we discard the faulty config early and don't create a hang up at the conversion stage.
Closes #6532

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Build the image and try passing a malformed url in slack config for which the operator logs show error.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
   Fix one alertmanagerconfig failing to sync blocks all others
```

### CODE REVIEW

**Comment by yp969803** [comment]
@codeknight03 seen youe commits, i think this will resolve the issue, as the invalid URLs can be detected now before generating configFile, Can you write the unit tests for this, for confirmation.
You can also merge your 2 commits.

**Comment by haanhvu** [comment]
Have you checked this change in a local cluster to see if it fixed the issue?

File: pkg/alertmanager/operator.go [hunk 1]
```diff
@@ -1267,8 +1267,12 @@ func checkDiscordConfigs(
...
 		}
 
-		if _, err := store.GetSecretKey(ctx, namespace, config.APIURL); err != nil {
-			return fmt.Errorf("failed to retrieve API URL: %w", err)
+		url, err := store.GetSecretKey(ctx, namespace, config.APIURL)
+		if err != nil {
+			return err
+		}
+		if _, err := validation.ValidateURL(strings.TrimSpace(url)); err != nil {
+			return fmt.Errorf("discord webhook 'url' %s invalid: %w", url, err)
```
Comment (simonpasquier) [inline pkg/alertmanager/operator.go:1275]: The error from ValidateURL() already contains the URL value. Also since we treat the URL as a secret, we shouldn't log it and we'd need a ValidateSecretURL() function.
```suggestion
			return err
```

**Comment by haanhvu** [comment]
I took a look at this. Here's what I see:

- Have you reproduced this issue before the fix? Have you reproduced this issue again with the fix to see if it works?
- I haven't reproduced. But from what I see in the codebase this change seems working. Besides Discord and Slack, do we need validation for other receivers too?
- I think we need a new test case for invalid url for each receiver in `TestProvisionAlertmanagerConfiguration` in `pkg/alertmanager/operator_test.go` (need @simonpasquier or other maintainers to confirm though)

File: pkg/alertmanager/operator.go (hunk 1 above)
Comment (haanhvu) [reply pkg/alertmanager/operator.go:1275]: > we'd need a ValidateSecretURL() function

You mean we'd need to define a new ValidateSecretURL() function? Why? I thought we already got the URL string from GetSecretKey() in the previous line, so ValidateURL() is enough? 🤔

Comment (simonpasquier) [reply pkg/alertmanager/operator.go:1275]: It's because `ValidateURL()` would return the URL value in the error which isn't something you want for a "secret" URL.

**Comment by simonpasquier** [comment]
Thanks @haanhvu for the comments. Yes I agree that we'd need unit tests to validate the fix.

File: pkg/alertmanager/validation/validation.go [hunk 2]
```diff
@@ -33,3 +34,25 @@ func ValidateURL(url string) (*config.URL, error) {
...
 	return &u, nil
 }
+
+// ValidateSecretURL against config.URL
+// This is for URLs which are retrieved from secrets and should not
+// logged part of the err.
+func ValidateSecretURL(url string) error {
+	var u config.URL
+
+	err := json.Unmarshal([]byte(fmt.Sprintf(`"%s"`, url)), &u)
```
Comment (mviswanathsai) [inline pkg/alertmanager/validation/validation.go:44]: Just out of curiosity, can't we just use `url.Parse()`? I see that it hasn't been used in the `ValidateURL()` func as well, is there any particular reason why we opt for manually un-marshalling the URL?

Comment (codeknight03) [reply pkg/alertmanager/validation/validation.go:44]: My initial understanding was since `config.url` is a custom type exposed by the `alermanager` package which has custom methods implemented so we might be using this in-order to be able to call these methods as per need. 

But now I am seeing it also has `SecretURL` as type, not sure if we could used that in the  `validateSecretURL()` method.

https://github.com/prometheus/alertmanager/blob/main/config/config.go#L128-L150

**Review by simonpasquier — COMMENTED** [review]
2 small nits.

**Comment by codeknight03** [comment]
@simonpasquier are you looking for further changes on this one?

**Comment by 1337andre** [comment]
Hi, any updates on this? We run into the same issue

**Comment by slashpai** [comment]
@codeknight03 Can you rebase to fix conflicts? We have operator release today if @simonpasquier is ok with changes happy to merge this

**Review by simonpasquier — DISMISSED** [review]
thanks!

**Comment by codeknight03** [comment]
@slashpai / @simonpasquier . Can you guys merge this one for the coming release ?

File: pkg/alertmanager/operator.go [hunk 3]
```diff
@@ -1264,9 +1271,13 @@ func checkDiscordConfigs(
 			return err
 		}
 
-		if _, err := store.GetSecretKey(ctx, namespace, config.APIURL); err != nil {
+		url, err := store.GetSecretKey(ctx, namespace, config.APIURL)
+		if err != nil {
 			return fmt.Errorf("failed to retrieve API URL: %w", err)
 		}
+		if err := validation.ValidateSecretURL(strings.TrimSpace(url)); err != nil {
+			return fmt.Errorf("discord webhook 'url' secret failed validation: %w", err)
```
Comment (simonpasquier) [inline pkg/alertmanager/operator.go:1279]:
```suggestion
			return fmt.Errorf("failed to validate API URL: %w", err)
```

File: pkg/alertmanager/operator.go [hunk 4]
```diff
@@ -1193,6 +1193,13 @@ func checkPagerDutyConfigs(
 			}
 		}
 
+		if config.URL != "" {
+			if _, err := validation.ValidateURL(strings.TrimSpace(config.URL)); err != nil {
+				return fmt.Errorf("pagerduty 'url' %s invalid: %w", config.URL, err)
```
Comment (simonpasquier) [inline pkg/alertmanager/operator.go:1198]:
```suggestion
				return fmt.Errorf("failed to validate URL: %w", err)
```

File: pkg/alertmanager/operator.go [hunk 5]
```diff
@@ -1285,9 +1296,13 @@ func checkSlackConfigs(
 		}
 
 		if config.APIURL != nil {
-			if _, err := store.GetSecretKey(ctx, namespace, *config.APIURL); err != nil {
+			url, err := store.GetSecretKey(ctx, namespace, *config.APIURL)
+			if err != nil {
 				return err
 			}
+			if err := validation.ValidateSecretURL(strings.TrimSpace(url)); err != nil {
+				return fmt.Errorf("slack api 'url' secret failed validation: %w", err)
```
Comment (simonpasquier) [inline pkg/alertmanager/operator.go:1304]:
```suggestion
				return fmt.Errorf("failed to validate API URL: %w", err)
```

File: pkg/alertmanager/operator.go [hunk 6]
```diff
@@ -1315,8 +1330,8 @@ func checkWebhookConfigs(
 			if err != nil {
 				return err
 			}
-			if _, err := validation.ValidateURL(strings.TrimSpace(url)); err != nil {
-				return fmt.Errorf("webhook 'url' %s invalid: %w", url, err)
+			if err := validation.ValidateSecretURL(strings.TrimSpace(url)); err != nil {
+				return fmt.Errorf("webhook 'url' secret failed validation: %w", err)
```
Comment (simonpasquier) [inline pkg/alertmanager/operator.go:1334]:
```suggestion
				return fmt.Errorf("failed to validate URL: %w", err)
```

**Review by simonpasquier — COMMENTED** [review]
Just a few remarks to make error messages more consistent.

**Comment by slashpai** [comment]
@codeknight03 once review comments are addressed should be good to merge and have it in release tomorrow.

**Comment by codeknight03** [comment]
@slashpai good to be merged.

File: pkg/alertmanager/operator.go [hunk 7]
```diff
@@ -1193,6 +1193,13 @@ func checkPagerDutyConfigs(
 			}
 		}
 
+		if config.URL != "" {
+			if _, err := validation.ValidateURL(strings.TrimSpace(config.URL)); err != nil {
+				return fmt.Errorf("failed to validate URL: %w ", err)
+			}
+
```
Comment (slashpai) [inline pkg/alertmanager/operator.go:1200]: nit: remove extra blank line here

File: pkg/alertmanager/validation/validation_test.go [hunk 8]
```diff
@@ -63,3 +63,42 @@ func TestValidateUrl(t *testing.T) {
...
+			if tc.expectErr {
+				if err == nil {
+					t.Fatal("expected error but got none")
+				}
+				return
+			}
+			if err != nil {
+				t.Fatal(err)
+			}
+
```
Comment (slashpai) [inline pkg/alertmanager/validation/validation_test.go:101]: nit: remove extra blank line

**Review by slashpai — APPROVED** [review]
lgtm, just non-blocking comments

**Review by simonpasquier — APPROVED** [review]
thanks!

**Comment by slashpai** [comment]
Thank you @codeknight03 for your work on this
