### PR TITLE
pkg/prometheus: skip invalid service monitors

### LINKED ISSUE #3327: Add new metric when prometheus is stuck on "creating config failed"
**What is missing?**

There is no metric to alert when prometheus fail to create the new configuration before reload it.

**Context:**
We work on a shared kubernetes cluster with different teams and someone deleted, by mistake, one secret used to get the api credentials used by the service monitor. And because of that prometheus started to throw this error:

```
E0709 12:11:36.444821       1 operator.go:994] Sync "prometheus-operator" failed: creating config failed: could not generate basicAuth for servicemonitor my-app. secret username key "user" in secret "basic-auth" not found
```

And because of this error all the new service monitor we configure are not added to the configuration (maybe a related bug?)

**Why do we need it?**

We need to know when the create configuration procedure is failing to fix it as soon we notice to improve our reliability.

**Environment**

* Prometheus Operator version:

    `v0.38.1`

### LINKED ISSUE #3329: Incorrect ServiceMonitor blocks prometheus deployment
**What happened?**

During re-deploying a cluster I did following:

1. Created Prometheus object with:
```
serviceMonitorNamespaceSelector: {}
serviceMonitorSelector: {}
```
2. Added ServiceMonitor which references non-existing Secret via `bearerTokenSecret`
3. Prometheus pod wasn't created and prometheus-operator logs suggested incorrect ServiceMonitor
4. Waited for about an hour
5. Added a Secret to satisfy SM from 2.
6. prometheus pod came up

**Did you expect to see something different?**

Prometheus should start and show 0 targets and not be blocked by incorrect ServiceMonitor. 

**How to reproduce it (as minimally and precisely as possible)**:

0. Start prometheus-operator
1. Create Prometheus object
2. Create ServiceMonitor referencing not existing Secret via `bearerTokenSecret`
3. Observe :)

**Environment**

* Prometheus Operator version:

    `v0.40.0`
    

* Kubernetes version information:

    `1.18.4`
    

* Kubernetes cluster kind:

    k3s

* Manifests:

1. SealedSecret: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/homeassistant/08_servicemonitor.yaml
2. Prometheus CR: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/prometheus/05_prometheus.yaml
3. Prometheus-operator deployment: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/prometheus-operator/04_deployment.yaml

* Prometheus Operator Logs:

Pods were rotated before I could gather logs.

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by simonpasquier**
Previously the operator would fail the reconciliation when a service
monitor was referencing a bad secret or configmap (either the object
didn't exist or the key was missing).

With this change, the operator will skip these service monitors.

Relates to #3327
Closes #3329

### CODE REVIEW

**Comment by bergerx** [comment]
We are also getting hit by this issue. Will likely resolve #3329 as well.

File: pkg/prometheus/operator.go [hunk 1]
```diff
@@ -1937,35 +1646,58 @@ func (c *Operator) selectServiceMonitors(p *monitoringv1.Prometheus) (map[string
...
+		}
+
+		if err != nil {
+			level.Warn(c.logger).Log(
+				"msg", "skipping servicemonitor",
+				"error", err.Error(),
+				"servicemonitor", namespaceAndName,
+				"namespace", p.Namespace,
+				"prometheus", p.Name,
+			)
```
Comment (s-urbaniak) [inline pkg/prometheus/operator.go:1689]: do we want to add a new counting metric too? I believe this would be valuable to track.

File: pkg/prometheus/operator.go [hunk 2]
```diff
@@ -2088,3 +1820,216 @@ func (c *Operator) listMatchingNamespaces(selector labels.Selector) ([]string, e
...
+		name: sel.Name,
+		key:  sel.Key,
+	}
+}
+
+func (k tlsAssetKey) String() string {
+	return fmt.Sprintf("%s_%s_%s_%s", k.from, k.ns, k.name, k.key)
+}
+
+type assetStore struct {
```
Comment (s-urbaniak) [inline pkg/prometheus/operator.go:1853]: nit: let's split this type and the key type into its own `asset_store.go` and also maybe add some tests?

File: pkg/prometheus/operator.go [hunk 3]
```diff
@@ -2088,3 +1820,216 @@ func (c *Operator) listMatchingNamespaces(selector labels.Selector) ([]string, e
...
+	return assetStore
+}
+
+func (a *assetStore) keyFunc(obj interface{}) (string, error) {
+	switch v := obj.(type) {
+	case *v1.ConfigMap:
+		return fmt.Sprintf("0/%s/%s", v.GetNamespace(), v.GetName()), nil
+	case *v1.Secret:
+		return fmt.Sprintf("1/%s/%s", v.GetNamespace(), v.GetName()), nil
+	}
```
Comment (s-urbaniak) [inline pkg/prometheus/operator.go:1883]: client go has `k8s.io/apimachinery/pkg/api/meta.Accessor()` and `k8s.io/apimachinery/pkg/api/meta.TypeAccessor()` functions which let you retrieve the name, namespace, and type, but admittedly this is strictly bound to secrets and configmaps, hence this should be fine.

File: pkg/prometheus/operator.go [hunk 4]
```diff
@@ -2088,3 +1820,216 @@ func (c *Operator) listMatchingNamespaces(selector labels.Selector) ([]string, e
...
+func newAssetStore(cmClient corev1client.ConfigMapsGetter, sClient corev1client.SecretsGetter) *assetStore {
+	assetStore := &assetStore{
+		cmClient:          cmClient,
+		sClient:           sClient,
+		tlsAssets:         make(map[tlsAssetKey]TLSAsset),
+		bearerTokenAssets: make(map[string]BearerToken),
+		basicAuthAssets:   make(map[string]BasicAuthCredentials),
+	}
+
+	assetStore.objStore = cache.NewStore(assetStore.keyFunc)
```
Comment (s-urbaniak) [inline pkg/prometheus/operator.go:1872]: nit: i think this could be inlined with the struct declaration above with a single return.

File: pkg/prometheus/operator.go [hunk 5]
```diff
@@ -2088,3 +1820,216 @@ func (c *Operator) listMatchingNamespaces(selector labels.Selector) ([]string, e
...
+			Name:      sel.Name,
+			Namespace: namespace,
+		},
+	})
+	if err != nil {
+		return "", errors.Wrapf(err, "unexpected store error when getting secret %q", sel.Name)
+	}
+
+	if !exists {
+		secret, err := a.sClient.Secrets(namespace).Get(context.TODO(), sel.Name, metav1.GetOptions{})
```
Comment (s-urbaniak) [inline pkg/prometheus/operator.go:2019]: let's pass the context in the function.

File: pkg/prometheus/operator.go [hunk 6]
```diff
@@ -2088,3 +1820,216 @@ func (c *Operator) listMatchingNamespaces(selector labels.Selector) ([]string, e
...
+			Name:      sel.Name,
+			Namespace: namespace,
+		},
+	})
+	if err != nil {
+		return "", errors.Wrapf(err, "unexpected store error when getting configmap %q", sel.Name)
+	}
+
+	if !exists {
+		cm, err := a.cmClient.ConfigMaps(namespace).Get(context.TODO(), sel.Name, metav1.GetOptions{})
```
Comment (s-urbaniak) [inline pkg/prometheus/operator.go:1989]: let's pass the context in the function.

File: pkg/prometheus/operator.go [hunk 7]
```diff
@@ -1877,11 +1580,17 @@ func (c *Operator) createOrUpdateTLSAssetSecret(p *monitoringv1.Prometheus) erro
...
+			return errors.Wrapf(err, "remote write %d", i)
+		}
+	}
+
+	for key, asset := range store.tlsAssets {
+		tlsAssetsSecret.Data[key.String()] = []byte(asset)
 	}
 
-	_, err = sClient.Get(context.TODO(), tlsAssetsSecret.Name, metav1.GetOptions{})
+	_, err := sClient.Get(context.TODO(), tlsAssetsSecret.Name, metav1.GetOptions{})
```
Comment (s-urbaniak) [inline pkg/prometheus/operator.go:1593]: As we add additional parameters to the function body, maybe let's start adding context here too? Not critical here, we can do this as a follow-up.

File: pkg/prometheus/operator.go (hunk 2 above)
Comment (s-urbaniak) [reply pkg/prometheus/operator.go:1853]: Also let's add a little bit of internal documentation what the asset store is about and its invariants (support for configmap and secret). I believe it is worth quickly documenting that this store is built and used during each reconcilation run to gather and temporarily store tls and bearer assets in order to be rendered as prometheus config.

It is important that the store is not used between reconcilation runs, it is just a temporary buffer.

**Comment by s-urbaniak** [comment]
This is looking great, thank you! In addition I believe it makes the reconciliation code much more readable :tada: I really just a few documentational/organizational nits, plus i think we should add some unit tests for the temporary store.

File: pkg/prometheus/operator.go (hunk 2 above)
Comment (simonpasquier) [reply pkg/prometheus/operator.go]: done

File: pkg/prometheus/operator.go (hunk 3 above)
Comment (simonpasquier) [reply pkg/prometheus/operator.go]: I've looked into this but as you said, the code is so small that it isn't worth the indirection IMO.

File: pkg/prometheus/operator.go (hunk 4 above)
Comment (simonpasquier) [reply pkg/prometheus/operator.go]: done

**Comment by simonpasquier** [comment]
@s-urbaniak I've updated with your comments. About passing a context to the `assetStore`'s functions, I feel like it can be tackled later (at least consistently in all the packages that use `context.TODO()`).

File: pkg/prometheus/operator.go (hunk 3 above)
Comment (s-urbaniak) [reply pkg/prometheus/operator.go]: agreed

**Comment by s-urbaniak** [comment]
LGTM :+1:
