### PR TITLE
pkg/prometheus: Add validations for relabel configs

### LINKED ISSUE #2503: Prometheus breaks: relabel configuration for replace action requires 'target_label' value
**What did you do?**
Deployed SNMP with prometheus operator by using additionalscrapeconfigs

**What did you expect to see?**
Prometheus in running state and see snmp targets under targets section.

**What did you see instead? Under which circumstances?**

```
$ ns get pods prometheus-k8s-0
NAME               READY   STATUS             RESTARTS   AGE
prometheus-k8s-0   2/3     CrashLoopBackOff   10         29m
```

**Environment**
development 

* Prometheus Operator version: 

	v0.25.0

* Kubernetes version information:

	v1.9.2+coreos.0

* Kubernetes cluster kind: 

	Kubespray 

* Manifests:

prometheus-prometheus.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  externalLabels:
    cluster: test-10
  nodeSelector:
    prometheus-node: "1"
  replicas: 1
  resources:
    requests:
      memory: 2Gi
  retention: 60d
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
        selector:
          matchLabels:
            lvm-volume: database-prometheus
  version: v2.5.0
  additionalScrapeConfigs:
    name: snmp-endpoints
    key: endpoints.yaml
```

endpoints.yaml
```
- job_name: "snmp-exporter"
  scrape_timeout: 300s
  scrape_interval: 300s
  static_configs:
    - targets: [ 'cisco1.test8.com', 'cisco2.test8.com', 'cisco3.test8.com', 'cisco4.test8.com']
  metrics_path: /snmp
  params:
    module: [zec]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter.monitoring.svc.cluster.local:9116
```

* Prometheus Operator Logs:

```
caller=main.go:625 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
```

### PR DESCRIPTION
**Pull request by slashpai**
Fixes #2503, #3942

Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

This PR is to add validation for relabelling configs

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Added validations for relabel configs
```

### CODE REVIEW

File: pkg/operator/validations.go [hunk 1]
```diff
@@ -34,3 +34,13 @@ func ValidateDurationField(durationField string) error {
...
+
+func ValidateRelabelAction(relabelAction string) bool {
+	validRelabelActions := []string{"replace", "keep", "drop", "hashmod", "labelmap", "labeldrop", "labelkeep"}
+	for _, action := range validRelabelActions {
+		if action == relabelAction {
+			return true
+		}
+	}
+	return false
+}
```
Comment (PhilipGough) [inline pkg/operator/validations.go:46]: This function does not really validate anything so perhaps it would be better named as `IsValidRelabelAction`? Or potentially, instead of this function maintain a lookup `ValidRelabelActions map[string]struct{}{}`?

To me, the map would be clearer and would avoid allocating the slice each time inside the function (which could also be declared as a package level var in the current implementation)

Comment (slashpai) [reply pkg/operator/validations.go:46]: Good suggestion. I will update :)

Comment (slashpai) [reply pkg/operator/validations.go]: updated

File: pkg/operator/validations.go [hunk 2]
```diff
@@ -19,6 +19,17 @@ import (
 	"github.com/prometheus/common/model"
 )
 
+// ValidRelabelActions for relabelling
+var ValidRelabelActions = map[string]bool{
```
Comment (simonpasquier) [inline pkg/operator/validations.go:23]: (nit) a more idiomatic way is to use a map of strings to empty structs.

```suggestion
var ValidRelabelActions = map[string]struct{}{
```

**Review by simonpasquier — COMMENTED** [review]
IMHO it would be even better to discard the invalid resources beforehand. This would happen [here](https://github.com/prometheus-operator/prometheus-operator/blob/009606736ffdcc14b23c77831a5ded26b3c8db43/pkg/prometheus/operator.go#L1512-L1525) in the select*() functions.

**Comment by simonpasquier** [comment]
It would also be a good case for implementing a validating webhook for service/pod monitors and probes.

**Comment by slashpai** [comment]
@simonpasquier I updated the PR with changes, can you review again? :)

File: pkg/prometheus/operator.go [hunk 3]
```diff
@@ -2081,3 +2121,14 @@ func validateRemoteWriteSpec(spec monitoringv1.RemoteWriteSpec) error {
 
 	return nil
 }
+
+func validateRelabelConfig(rc monitoringv1.RelabelConfig) error {
+	if _, exists := operator.ValidRelabelActions[rc.Action]; !exists {
+		return errors.Errorf("%s is an invalid relabel action", rc.Action)
+	}
+	// both replace and hashmod need targetLabel
+	if (rc.Action == "replace" || rc.Action == "hashmod") && rc.TargetLabel == "" {
```
Comment (simonpasquier) [inline pkg/prometheus/operator.go:2130]: it would be nice to have constants for the know actions.

**Review by simonpasquier — COMMENTED** [review]
[More validations](
https://github.com/prometheus/prometheus/blob/f041a6a228b1a7e34e1337e5c0974db63820c6cb/model/relabel/relabel.go#L106-L130
) are needed and we should also push validations down to the [OpenAPI spec](https://book.kubebuilder.io/reference/markers/crd-validation.html)  as much as we can (for instance, the `action` field could have `//+kubebuilder:default=replace` and `//+kubebuilder:validation:Enum=replace,keep,...`).

File: pkg/operator/validations.go [hunk 4]
```diff
@@ -19,6 +19,17 @@ import (
...
+// ValidRelabelActions for relabelling
+var ValidRelabelActions = map[string]struct{}{
+	"replace":   {},
+	"keep":      {},
+	"drop":      {},
+	"hashmod":   {},
+	"labelmap":  {},
+	"labeldrop": {},
+	"labelkeep": {},
+}
```
Comment (PhilipGough) [inline pkg/operator/validations.go:31]: these are already defined here https://github.com/prometheus/prometheus/blob/4c56a193c518ae6f56008b0a4c850a9c3f1477c6/model/relabel/relabel.go#L44-L56 in a pkg we already import so might be worth considering reusing the consts?

File: pkg/prometheus/operator.go (hunk 3 above)
Comment (PhilipGough) [reply pkg/prometheus/operator.go:2130]: yes, see https://github.com/prometheus/prometheus/blob/4c56a193c518ae6f56008b0a4c850a9c3f1477c6/model/relabel/relabel.go#L44-L56

**Comment by PhilipGough** [comment]
@slashpai looking good overall, just a couple of comments for consideration

**Comment by slashpai** [comment]
Updated as per review comments

**Comment by slashpai** [comment]
@simonpasquier Please review, I will add some more tests but let me know if any other changes needed :)

**Comment by slashpai** [comment]
Updated

File: pkg/prometheus/operator_test.go [hunk 5]
```diff
@@ -264,3 +265,49 @@ func TestValidateRemoteWriteConfig(t *testing.T) {
 		})
 	}
 }
+
+func TestRelabelConfig(t *testing.T) {
```
Comment (simonpasquier) [inline pkg/prometheus/operator_test.go:269]:
```suggestion
func TestValidateRelabelConfig(t *testing.T) {
```

File: pkg/prometheus/operator_test.go [hunk 6]
```diff
@@ -264,3 +265,49 @@ func TestValidateRemoteWriteConfig(t *testing.T) {
...
+			relabelConfig: monitoringv1.RelabelConfig{
+				Action:      "replace",
+				TargetLabel: "test_valid_action_with_target_label",
+			},
+		},
+	} {
+		t.Run(fmt.Sprintf("%s Action(%s)", tc.relabelConfig.Action, tc.relabelConfig.TargetLabel), func(t *testing.T) {
+			err := validateRelabelConfig(tc.relabelConfig)
+			if err != nil && !tc.expectedErr {
+				t.Fatalf("unexpected error occurred: %v", err)
```
Comment (simonpasquier) [inline pkg/prometheus/operator_test.go:306]:
```suggestion
				t.Fatalf("expected no error, got: %v", err)
```

File: pkg/prometheus/operator.go [hunk 7]
```diff
@@ -2081,3 +2123,37 @@ func validateRemoteWriteSpec(spec monitoringv1.RemoteWriteSpec) error {
 
 	return nil
 }
+
+func validateRelabelConfig(rc monitoringv1.RelabelConfig) error {
+	relabelTarget := regexp.MustCompile(`^(?:(?:[a-zA-Z_]|\$(?:\{\w+\}|\w+))+\w*)+$`)
+
+	if _, err := relabel.NewRegexp(rc.Regex); err != nil {
+		return errors.Errorf("regex for relabel configuration %s doesn't compile", rc.Regex)
```
Comment (simonpasquier) [inline pkg/prometheus/operator.go:2131]:
```suggestion
		return errors.Wrapf(err, "invalid regex for relabel configuration", rc.Regex)
```

**Review by simonpasquier — COMMENTED** [review]
a few minor comments otherwise :+1:

File: pkg/prometheus/operator_test.go [hunk 8]
```diff
@@ -264,3 +265,49 @@ func TestValidateRemoteWriteConfig(t *testing.T) {
 		})
 	}
 }
+
+func TestRelabelConfig(t *testing.T) {
+	for _, tc := range []struct {
+		relabelConfig monitoringv1.RelabelConfig
+		expectedErr   bool
+	}{
+		{
```
Comment (simonpasquier) [inline pkg/prometheus/operator_test.go:274]: could you add a few more test cases and a comment at the top of each case to explain what we're testing?

Comment (slashpai) [reply pkg/prometheus/operator_test.go:276]: I added some more

**Comment by slashpai** [comment]
@simonpasquier  Addressed comments and added some more tests

**Review by simonpasquier — APPROVED** [review]
lgtm
