### PR TITLE
Ensure group_by values are unique in alertmanager config

### LINKED ISSUE #4402: AlertmanagerConfig with duplicate group_by labels generates an invalid configuration
The following AlertmanagerConfig definition would trigger an invalid configuration:

```yaml
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'null'
  receivers:
  - name: 'null'
```

Alertmanager logs:

```
level=error ts=2021-11-15T15:42:06.617Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="duplicated label \"job\" in group_by"
```

cc @PhilipGough

### PR DESCRIPTION
**Pull request by PhilipGough**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Elements in the routes `groupBy` list must be unique and furthermore, when the special value '...' is provided, there must be no other elements in the list.

Fixes #4402 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Ensure group_by values are unique in alertmanager config
```

### CODE REVIEW

File: pkg/alertmanager/validation.go [hunk 1]
```diff
@@ -218,6 +218,19 @@ func validateAlertManagerRoutes(r *monitoringv1alpha1.Route, receivers map[strin
 		return errors.Errorf("receiver %q not found", r.Receiver)
 	}
 
+	if groupLen := len(r.GroupBy); groupLen > 0 {
```
Comment (fpetkovski) [inline pkg/alertmanager/validation.go:221]: For my understanding, what is the reason for using both the OpenAPI validation and implementing our own operator-side validation?

Comment (PhilipGough) [reply pkg/alertmanager/validation.go:221]: From my understanding, there are at least a couple of reasons:

1. There are some cases that the OpenAPi validation (at least with the kubebuilder annotations) do not cover. This PR actually contains an example of one of those. We want unique items in the slice (covered with `UniqueItems`), but we also want to validate that if `'...'` is in the list, there are no other items, so we need to validate ourselves server-side (unless I've missed something).
2. We implement a validating webhook, so it made sense to split out the entire validation and have the admission controller call that.

Comment (PhilipGough) [reply pkg/alertmanager/validation.go:221]: The error message from the failing test is as follows: `alertmanager_instance_namespaces_test.go:136: initialize AlertmanagerConfig CRD: create CRD alertmanagerconfigs on the apiserver: create CRD: AlertmanagerConfig: CustomResourceDefinition.apiextensions.k8s.io "alertmanagerconfigs.monitoring.coreos.com" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[route].properties[groupBy].uniqueItems: Forbidden: uniqueItems cannot be set to true since the runtime complexity becomes quadratic`

I went digging around and found https://github.com/kubernetes/community/pull/708/ and https://github.com/kubernetes/kubernetes/commit/fd09c3dbb67374e4f4b46b820b5cd3d9a3124cda#diff-6d0d1a9c59e6d17eea2b3ccdf2d6eb7d6169efdf7ed5d5e1f5c09ce5632efd18R205 which basically means we cannot have the `UniqueItems:=true`, so again a custom validation func is required. 

I am surprised this is not supported for basic types like int and string but here we are.

Comment (fpetkovski) [reply pkg/alertmanager/validation.go:221]: Alright, this explains it then. Thanks for the input.

**Review by fpetkovski — APPROVED** [review]

File: pkg/alertmanager/validation.go (hunk 1 above)
Comment (sttts) [reply pkg/alertmanager/validation.go:221]: Make it list-type set and it will be checked for duplicates.
