### PR TITLE
Fix flaky e2e Alertmanager test 

### LINKED ISSUE #3540: Flaky e2e test: E2E tests (alertmanager)
We seem to have had a flaky test for some time, here are some examples I did not have a chance to look into it yet, but it does finish after some retries.

https://github.com/prometheus-operator/prometheus-operator/runs/1155429560?check_suite_focus=true 
>         --- FAIL: TestAllNS/x/AMClusterAfterRollingUpdate (81.08s)
https://github.com/prometheus-operator/prometheus-operator/runs/1153860258?check_suite_focus=true
>         --- FAIL: TestAllNS/x/AMZeroDowntimeRollingDeployment (184.50s)

Seems like there are a couple of flakes, not just one. Might be as easy as retrying or as difficult as rewriting tests.

### PR DESCRIPTION
**Pull request by arghya88**
Fixes #3540

### CODE REVIEW

File: test/framework/alertmanager.go [hunk 1]
```diff
@@ -217,10 +217,7 @@ func amImage(version string) string {
 func (f *Framework) WaitForAlertmanagerInitialized(ns, name string, amountPeers int, forceEnableClusterMode bool) error {
 	var pollError error
 	err := wait.Poll(time.Second, time.Minute*5, func() (bool, error) {
-		amStatus, err := f.GetAlertmanagerStatus(ns, name)
-		if err != nil {
-			return false, err
-		}
+		amStatus := f.GetAlertmanagerStatus(ns, name)
```
Comment (simonpasquier) [inline test/framework/alertmanager.go:220]: As written in the issue, we should return false to retry later and the returned error needs to be saved in case the wait loop fails eventually. 

```suggestion
		amStatus, err := f.GetAlertmanagerStatus(ns, name)
		if err != nil {
			pollError := fmt.Errorf("failed to query Alertmanager: %s", err)
			return false, nil
		}
```

File: test/framework/alertmanager.go [hunk 2]
```diff
@@ -257,19 +254,22 @@ func (f *Framework) WaitForAlertmanagerInitialized(ns, name string, amountPeers
 	return nil
 }
 
-func (f *Framework) GetAlertmanagerStatus(ns, n string) (models.AlertmanagerStatus, error) {
+func (f *Framework) GetAlertmanagerStatus(ns, n string) models.AlertmanagerStatus {
```
Comment (simonpasquier) [inline test/framework/alertmanager.go:257]: `GetAlertmanagerStatus()` shouldn't swallow the error.

File: test/framework/alertmanager.go [hunk 3]
```diff
@@ -348,10 +348,7 @@ func (f *Framework) GetSilences(ns, n string) (models.GettableSilences, error) {
 // string.
 func (f *Framework) WaitForAlertmanagerConfigToContainString(ns, amName, expectedString string) error {
 	err := wait.Poll(10*time.Second, time.Minute*5, func() (bool, error) {
-		amStatus, err := f.GetAlertmanagerStatus(ns, "alertmanager-"+amName+"-0")
-		if err != nil {
-			return false, err
-		}
+		amStatus := f.GetAlertmanagerStatus(ns, "alertmanager-"+amName+"-0")
```
Comment (simonpasquier) [inline test/framework/alertmanager.go:351]: same here

File: test/framework/alertmanager.go [hunk 4]
```diff
@@ -258,17 +261,22 @@ func (f *Framework) WaitForAlertmanagerInitialized(ns, name string, amountPeers
...
 
 func (f *Framework) GetAlertmanagerStatus(ns, n string) (models.AlertmanagerStatus, error) {
+
 	var amStatus models.AlertmanagerStatus
 	request := ProxyGetPod(f.KubeClient, ns, n, "/api/v2/status")
 	resp, err := request.DoRaw(context.TODO())
+
 	if err != nil {
+
+		fmt.Errorf("failed to get alertmanager status response: %v", err)
```
Comment (simonpasquier) [inline test/framework/alertmanager.go:271]:
```suggestion
```

File: test/framework/alertmanager.go [hunk 5]
```diff
@@ -258,17 +261,22 @@ func (f *Framework) WaitForAlertmanagerInitialized(ns, name string, amountPeers
...
 		return amStatus, err
 	}
 
 	if err := json.Unmarshal(resp, &amStatus); err != nil {
+
+		fmt.Errorf("failed to unmarshal alertmanager status response: %v", err)
```
Comment (simonpasquier) [inline test/framework/alertmanager.go:277]:
```suggestion
```

File: test/framework/alertmanager.go [hunk 6]
```diff
@@ -347,10 +355,14 @@ func (f *Framework) GetSilences(ns, n string) (models.GettableSilences, error) {
 // configuration via the Alertmanager's API and checks if it contains the given
 // string.
 func (f *Framework) WaitForAlertmanagerConfigToContainString(ns, amName, expectedString string) error {
+
+	var pollError error
```
Comment (simonpasquier) [inline test/framework/alertmanager.go:359]: you'd need to modify L376 to report `pollErr` there (see L254 for example). Also it would make sense to set  `pollErr` when the returned config doesn't match with the expected value.

Comment (arghya88) [reply test/framework/alertmanager.go:355]: Done...PTAL

File: test/framework/alertmanager.go [hunk 7]
```diff
@@ -215,11 +215,14 @@ func amImage(version string) string {
 }
 
 func (f *Framework) WaitForAlertmanagerInitialized(ns, name string, amountPeers int, forceEnableClusterMode bool) error {
+
```
Comment (lilic) [inline test/framework/alertmanager.go:218]: Nitpick: but we tend to not do a new line after function decleration, so this is not really needed.

Comment (arghya88) [reply test/framework/alertmanager.go:218]: Let me fix it quickly

**Review by simonpasquier — COMMENTED** [review]
All good for me. It can be merged on green.

**Comment by lilic** [comment]
Thanks! 🎉
