### PR TITLE
fix: update reloader requests and limits when updated

### LINKED ISSUE #5970: reloader config limits and requests not being updated
I have set the flags to modify the reloader cpu requests, but they are not applied:

- prometheusOperator version: `0.68.0`
- prometheus version: `v2.47.1`

- Prometheus operator pod description:
```yaml
Containers:
  prometheus-operator:
    Image: quay.io/prometheus-operator/prometheus-operator:v0.68.0
    Args:
      --kubelet-service=kube-system/kubelet
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0
      --config-reloader-cpu-request=10m
      --config-reloader-cpu-limit=20m
```

- Prometheus pod description: (i restarted it after applying the operator)
```yaml
 config-reloader:
    Image: quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
      --reload-url=http://localhost:9090/prometheus/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
      --watched-dir=/etc/prometheus/rules/prometheus-monitoring-rulefiles-0
    Limits:
      cpu:     10m
      memory:  50Mi
    Requests:
      cpu:     10m
      memory:  50Mi
```

_Originally posted by @ebarped in https://github.com/prometheus-operator/prometheus-operator/issues/5446#issuecomment-1750436288_

### PR DESCRIPTION
**Pull request by simonpasquier**
## Description

Closes #5970

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [X] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by simonpasquier** [comment]
Need to add tests for this.

File: pkg/operator/config.go [hunk 1]
```diff
@@ -72,10 +72,12 @@ func DefaultConfig(cpu, memory string) Config {
...
-	CPURequests    Quantity
-	CPULimits      Quantity
-	MemoryRequests Quantity
-	MemoryLimits   Quantity
+	// The struct tag are needed for github.com/mitchellh/hashstructure to take
+	// the field values into account when generating the statefulset hash.
+	CPURequests    Quantity `hash:"string"`
+	CPULimits      Quantity `hash:"string"`
+	MemoryRequests Quantity `hash:"string"`
+	MemoryLimits   Quantity `hash:"string"`
```
Comment (ArthurSens) [inline pkg/operator/config.go:80]: Interesting! TIL

File: test/framework/framework.go [hunk 2]
```diff
@@ -195,14 +195,21 @@ func (f *Framework) MakeEchoDeployment(group string) *appsv1.Deployment {
...
+	Namespace              string
+	AllowedNamespaces      []string
+	DeniedNamespaces       []string
+	PrometheusNamespaces   []string
+	AlertmanagerNamespaces []string
+	EnableAdmissionWebhook bool
+	ClusterRoleBindings    bool
+	EnableScrapeConfigs    bool
+	AdditionalArgs         []string
+}
```
Comment (ArthurSens) [inline test/framework/framework.go:208]: Loved the abstraction here!

**Review by ArthurSens — APPROVED** [review]
