### PR TITLE
pkg/operator: create Select method for rule selection 

### LINKED ISSUE #5191: Reject invalid PrometheusRule objects beforehand rather than failing the reconciliation
**What is missing?**

When the Thanos/Prometheus controllers detect an invalid PrometheusRule object (invalid PromQL expression for instance), they fail the reconciliation (and for Prometheus, the `Reconciled`  condition will be set to False). Instead the controllers should reject the invalid object and proceed (just like we do for service/pod monitors and probes).

**Why do we need it?**

In self-service environments, blocking the reconciliation means that one single user can block all other users if they push a bad rule.

**Environment**

* Prometheus Operator version: N/A

**Anything else we need to know?**:

Probably a good time to refactor the code handling the rules which is duplicated between pkg/prometheus and pkg/thanos.

### PR DESCRIPTION
**Pull request by slashpai**
Fixes #5191

Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Update logic on selecting prometheus rules by rejecting invalid ones instead of failing reconciliation
```

### CODE REVIEW

**Comment by slashpai** [comment]
Removing draft for initial review

File: pkg/prometheus/rules.go [hunk 1]
```diff
@@ -190,32 +189,43 @@ func (c *Operator) selectRules(p *monitoringv1.Prometheus, namespaces []string)
...
-			return nil, marshalErr
+	}
+
+	var rejected int
+	rules := make(map[string]string, len(promRules))
+
+	for ruleName, promRule := range promRules {
+		var err error
+		if err := nsLabeler.EnforceNamespaceLabel(promRule); err != nil {
+			break
```
Comment (simonpasquier) [inline pkg/prometheus/rules.go:212]: this should be `continue` + you want something like we do in selectProbes()
https://github.com/prometheus-operator/prometheus-operator/blob/a382d0952fc48afa49bf71d4803186ce866956dd/pkg/prometheus/operator.go#L2220-L2229

File: pkg/prometheus/rules.go [hunk 2]
```diff
@@ -190,32 +189,43 @@ func (c *Operator) selectRules(p *monitoringv1.Prometheus, namespaces []string)
...
+		}
+
+		content, err := generateRulesConfiguration(promRule.Spec, c.logger)
+		if err != nil {
+			rejected++
+			level.Warn(c.logger).Log(
+				"msg", "skipping prometheusrule",
+				"error", err.Error(),
+				"prometheusrule", promRule.Name,
+				"namespace", p.Namespace,
```
Comment (JoaoBraveCoding) [inline pkg/prometheus/rules.go:222]: shouldn't it be the rule namespace? Since users will want to know in which namespace is the prometheus rule that contains the error 

```suggestion
				"namespace", promRule.Namespace,
```

Comment (slashpai) [reply pkg/prometheus/rules.go:222]: Correct. my bad :)

File: pkg/prometheus/rules.go (hunk 1 above)
Comment (slashpai) [reply pkg/prometheus/rules.go]: done

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm 👍

**Comment by slashpai** [comment]
Need to implement for Thanos as well. I will look in reducing duplicate code between Thanos and Prometheus

**Comment by slashpai** [comment]
@simonpasquier Can you take another look at this?

**Review by simonpasquier — COMMENTED** [review]
Can we factorize the 2 `selectRules()` methods (probably in pkg/operator)?

File: pkg/operator/rules.go [hunk 3]
```diff
@@ -24,10 +24,28 @@ import (
...
 	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
+	"github.com/prometheus-operator/prometheus-operator/pkg/informers"
+	"github.com/prometheus-operator/prometheus-operator/pkg/k8sutil"
+	namespacelabeler "github.com/prometheus-operator/prometheus-operator/pkg/namespace-labeler"
 	thanostypes "github.com/thanos-io/thanos/pkg/store/storepb"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/client-go/tools/cache"
 )
 
+type PromRuleCommonFields struct {
```
Comment (slashpai) [inline pkg/operator/rules.go:37]: Tried this approach to avoid passing all these fields to function. Also looking for better name for this struct :)

**Comment by slashpai** [comment]
@simonpasquier PTAL when you get a chance :)

File: pkg/operator/rules.go (hunk 3 above)
Comment (simonpasquier) [reply pkg/operator/rules.go:37]: I'd suggest to leave the initialization of the label selector and namespace labeler to the caller. It will make the struct more lightweight + Prometheus & Thanos don't create the same ns labeler (because of the partial response strategy).

```golang
type PrometheusRuleSelector struct {
   labelSelector labels.Selector
   nsLabeler namespacelabeler.Labeler
   rulesInfs *informers.ForResource
   logger log.Logger
   metrics *Metrics
}

func NewPrometheusRuleSelector(...) *PrometheusRuleSelector {
...
}

func (prs *PrometheusRuleSelector) Select(namespaces ...string) (map[string]string, error) {
...
}
```

File: pkg/operator/rules.go [hunk 4]
```diff
@@ -69,3 +87,104 @@ func ValidateRule(promRule monitoringv1.PrometheusRuleSpec) []error {
...
+		}
+		content, err = GenerateRulesConfiguration(promRule.Spec, p.Logger)
+		if err != nil {
+			rejected++
+			level.Warn(p.Logger).Log(
+				"msg", "skipping prometheusrule",
+				"error", err.Error(),
+				"prometheusrule", promRule.Name,
+				"namespace", promRule.Namespace,
+				objectType, p.ResourceName,
```
Comment (simonpasquier) [inline pkg/operator/rules.go:154]: we can pass a wrapped logger for PrometheusRuleSelector (e.g. `log.With(c.logger, "prometheus", p.Name, "namespace", p.Namespace)`).

File: pkg/operator/rules.go [hunk 5]
```diff
@@ -69,3 +87,104 @@ func ValidateRule(promRule monitoringv1.PrometheusRuleSpec) []error {
...
+		"msg", "selected Rules",
+		"rules", strings.Join(ruleNames, ","),
+		"namespace", p.ResourceName,
+		"prometheus", p.ResourceName,
+	)
+
+	if pKey, ok := keyFunc(p.Logger, p); ok {
+		p.Metrics.SetSelectedResources(pKey, monitoringv1.PrometheusRuleKind, len(rules))
+		p.Metrics.SetRejectedResources(pKey, monitoringv1.PrometheusRuleKind, rejected)
+	}
```
[the remark this answers is not in the document]
Comment (slashpai) [reply pkg/operator/rules.go]: I went ahead with this approach since this was my initial thought as well :)

File: pkg/operator/rules.go [hunk 6]
```diff
@@ -25,9 +25,31 @@ import (
...
 	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
+	"github.com/prometheus-operator/prometheus-operator/pkg/informers"
+	"github.com/prometheus-operator/prometheus-operator/pkg/k8sutil"
+	namespacelabeler "github.com/prometheus-operator/prometheus-operator/pkg/namespace-labeler"
 	thanostypes "github.com/thanos-io/thanos/pkg/store/storepb"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
+type PrometheusRuleSelector struct {
+	objectType   string
```
Comment (slashpai) [inline pkg/operator/rules.go:36]: I see we still need this field for partial response strategy field

**Comment by slashpai** [comment]
I updated with changes suggested, need to remove a few units as well. Updating that as well

File: pkg/operator/rules.go [hunk 7]
```diff
@@ -25,9 +25,31 @@ import (
...
+	return &PrometheusRuleSelector{
+		objectType:   objectType,
+		ruleSelector: ruleSelector,
+		nsLabeler:    nsLabeler,
+		ruleInformer: ruleInformer,
+		logger:       logger,
+	}
+}
+
 func GenerateRulesConfiguration(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:53]: we don't need this to be public anymore?

File: pkg/operator/rules.go (hunk 6 above)
Comment (simonpasquier) [reply pkg/operator/rules.go:36]: We can make it something more obvious though

```suggestion
	ruleFormat   RuleConfigurationFormat
```

with

```golang
type RuleConfigurationFormat int

const (
    PrometheusFormat RuleConfigurationFormat = iota
    ThanosFormat
)
```

**Review by simonpasquier — COMMENTED** [review]
just a few nits :)

File: pkg/thanos/rules.go [hunk 8]
```diff
@@ -51,9 +51,34 @@ func (o *Operator) createOrUpdateRuleConfigMaps(ctx context.Context, t *monitori
...
+	// append the deprecated PrometheusRulesExcludedFromEnforce
+	for _, rule := range t.Spec.PrometheusRulesExcludedFromEnforce {
+		excludedFromEnforcement = append(excludedFromEnforcement,
+			monitoringv1.ObjectReference{
+				Namespace: rule.RuleNamespace,
+				Group:     monitoring.GroupName,
+				Resource:  monitoringv1.PrometheusRuleName,
+				Name:      rule.RuleName,
+			})
+	}
```
[the remark this answers is not in the document]
Comment (slashpai) [reply pkg/thanos/rules.go:64]: This would be true for Prometheus and false for Thanos right? 

```
nsLabeler := namespacelabeler.New(
		t.Spec.EnforcedNamespaceLabel,
		append(t.Spec.ExcludedFromEnforcement, monitoringv1.ToObjectReferences(t.Spec.PrometheusRulesExcludedFromEnforce)...)
		false,
	)
```

**Comment by slashpai** [comment]
@simonpasquier Addressed all comments except the nsLabeler (added comment in line)

File: pkg/operator/rules_test.go [hunk 9]
```diff
@@ -62,9 +66,88 @@ func shouldAcceptRuleWithValidPartialResponseStrategyValue(t *testing.T) {
...
 		},
 	}}
-	content, _ := GenerateRulesConfiguration(rules, log.NewLogfmtLogger(log.NewSyncWriter(os.Stdout)))
+	content, _ := generateRulesConfiguration(ThanosFormat, rules, log.NewLogfmtLogger(log.NewSyncWriter(os.Stdout)))
 	if !strings.Contains(content, "partial_response_strategy: warn") {
 		t.Fatalf("expected `partial_response_strategy` to be set in PrometheusRule as `warn`")
 
 	}
 }
+
```
Comment (slashpai) [inline pkg/operator/rules_test.go:75]: These are tests moved from Prometheus package

File: pkg/thanos/rules.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (simonpasquier) [reply pkg/thanos/rules.go:64]: yes correct, sorry for the confusion.

[the remark this answers is not in the document]
Comment (slashpai) [reply pkg/thanos/rules.go:64]: Are we good with the changes?

**Review by JoaoBraveCoding — APPROVED** [review]
Sweet refactoring 👍 Great job JP!

**Review by simonpasquier — COMMENTED** [review]
lgtm but you'll have to rebase on main :)

**Comment by slashpai** [comment]
> lgtm but you'll have to rebase on main :)

@simonpasquier rebased

**Comment by simonpasquier** [comment]
I realize that we don't have an e2e test verifying that the operator doesn't select invalid rules now. As the validating webhook config watches for all namespaces, an invalid rule can never reach the operator. I'd suggest to tweak the `namespaceSelector` field of the webhook configuration to exclude namespaces with a certain label:

```
namespaceSelector:
  matchExpressions:
  - key: excludeFromWebhook
    operator: NotIn
    values: ["true"]
```

https://github.com/prometheus-operator/prometheus-operator/blob/cb272a61310e7d163d47e8609cbcbad670d1b7df/test/framework/resources/prometheus-operator-validatingwebhook.yaml#L13

Then a rule created in a namespace with the `excludeFromWebhook: "true"` would skip the validation and we can check that the operator discards it.

File: test/e2e/rules_test.go [hunk 10]
```diff
@@ -312,3 +312,24 @@ func TestPrometheusRuleApply(t *testing.T) {
...
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	name := "invalidRule"
+	invalidAlert := "invalidAlert"
+
+	_, err = framework.MakeAndCreateInvalidRule(context.Background(), ns, name, invalidAlert)
+	if err == nil {
+		t.Fatal("Expected invalid prometheusrule to be rejected")
```
Comment (simonpasquier) [inline test/e2e/rules_test.go:333]: Hmm the rule should be accepted by the Kube API server if the namespace is excluded from the webhook?

**Comment by slashpai** [comment]
@simonpasquier  Rebased and updated the e2e test to check prometheus reconciliation status after invalid rule created

File: test/e2e/prometheus_test.go [hunk 11]
```diff
@@ -1592,6 +1592,67 @@ func testInvalidRulesAreRejected(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("expected invalid rule to be created in namespace %v", err)
+	}
+
+	prom := framework.MakeBasicPrometheus(ns, "basic-prometheus", "test-group", 1)
+	if _, err = framework.CreatePrometheusAndWaitUntilReady(context.Background(), ns, prom); err != nil {
+		t.Fatal("Creating prometheus failed: ", err)
+	}
+
+	var pollErr error
```
[the remark this answers is not in the document]
Comment (slashpai) [reply test/e2e/prometheus_test.go]: ya correct. I just needed updated prometheus object after it becomes ready and `f.WaitForPrometheusReady` doesn't return updated object. Should we update that method to return updated prometheus since that will contain status as well but that will need change on other tests as well to update the method call.

For now I am getting the object again in this test to check for reconcile status

**Comment by slashpai** [comment]
Just for more validation I tested this change manually as well checked the e2e test against main branch on which refactoring is not there. Prometheus fails to reconcile without this change. Also the metric `prometheus_operator_managed_resources{controller="prometheus",resource="PrometheusRule",state="rejected"} 1` is updated correctly

**Comment by slashpai** [comment]
@simonpasquier Can you take another look at this one, updated test :)

File: test/e2e/prometheus_test.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (slashpai) [reply test/e2e/prometheus_test.go]: my bad I didnt notice `WaitForResourceAvailable()` is called by `WaitForPrometheusReady()` which checks the reconciliation status. I have removed the extra check now

**Comment by simonpasquier** [comment]
Thanks!
