### PR TITLE
Fix `MatchType` is empty in AM matchers

### LINKED ISSUE #7569: AlertmanagerConfig: "matchers" field is using a deprecated syntax
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Description
I am getting the error on the Prometheus operator side creating the Alertmanager config with the official documentation:
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#alertmanagerconfig

```
jsonPayload: {
alertmanager: "kube-prometheus-stack-alertmanager"
caller: {3}
component: "alertmanager-controller"
level: "warn"
match: "map[application:proxy-dispenser-live]"
match_re: "map[]"
msg: "'matchers' field is using a deprecated syntax which will be removed in future versions"
namespace: "monitoring"
receiver: "default/proxy-dispenser-live/slack"
ts: "2025-05-29T03:11:29.239028388Z"
}
```

## Steps to Reproduce
Create the AlertmanagerConfig:
```
- apiVersion: monitoring.coreos.com/v1alpha1
  kind: AlertmanagerConfig
  metadata:
    annotations:
      meta.helm.sh/release-name: proxy-dispenser-live
      meta.helm.sh/release-namespace: default
    generation: 1
    labels:
      app.kubernetes.io/instance: proxy-dispenser-live
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: proxy-dispenser
      app.kubernetes.io/version: "1.0"
      helm.sh/chart: proxy-dispenser-0.1.0
    name: proxy-dispenser-live
    namespace: default
  spec:
    receivers:
    - name: slack
      slackConfigs:
      - channel: '#alerts_proxy_dispenser'
        sendResolved: true
    route:
      continue: false
      matchers:
      - name: application
        value: proxy-dispenser-live
      receiver: slack
```

## Expected Result
Everything is ok

## Actual Result
Getting warnings

### Prometheus Operator Version

```shell
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "24"
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2020-09-17T12:12:25Z"
  generation: 34
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 72.3.0
    chart: kube-prometheus-stack-72.3.0
    heritage: Helm
    mode: both
    provisioner: terraform
    release: kube-prometheus-stack
    stage: base
    team: infrastructure
  name: kube-prometheus-stack-operator
  namespace: monitoring
  resourceVersion: "2839336244"
  uid: 819f2fb4-9cb5-4cfe-89b7-a5d0b7176668
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-prometheus-stack-operator
      release: kube-prometheus-stack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-operator
        app.kubernetes.io/component: prometheus-operator
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 72.3.0
        chart: kube-prometheus-stack-72.3.0
        heritage: Helm
        mode: both
        provisioner: terraform
        release: kube-prometheus-stack
        stage: base
        team: infrastructure
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --kubelet-service=kube-system/kube-prometheus-stack-kubelet
        - --kubelet-endpoints=true
        - --kubelet-endpointslice=false
        - --log-format=json
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.82.0
        - --config-reloader-cpu-request=0
        - --config-reloader-cpu-limit=0
        - --config-reloader-memory-request=0
        - --config-reloader-memory-limit=0
        - --thanos-default-base-image=quay.io/thanos/thanos:v0.38.0
        - --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
        - --web.enable-tls=true
        - --web.cert-file=/cert/cert
        - --web.key-file=/cert/key
        - --web.listen-address=:10250
        - --web.tls-min-version=VersionTLS13
        env:
        - name: GOGC
          value: "30"
        image: quay.io/prometheus-operator/prometheus-operator:v0.82.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-prometheus-stack
        ports:
        - containerPort: 10250
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 100m
            memory: 400Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cert
          name: tls-secret
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: kube-prometheus-stack-operator
      serviceAccountName: kube-prometheus-stack-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-secret
        secret:
          defaultMode: 420
          secretName: kube-prometheus-stack-admission
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2025-04-23T13:00:13Z"
  compiler: gc
  gitCommit: 60a317eadfcb839692a68eab88b2096f4d708f4f
  gitTreeState: clean
  gitVersion: v1.33.0
  goVersion: go1.24.2
  major: "1"
  minor: "33"
  platform: darwin/arm64
kustomizeVersion: v5.6.0
serverVersion:
  buildDate: "2025-04-21T04:19:20Z"
  compiler: gc
  gitCommit: 1f3efa78f873bb758933b054acb4bdead738eafb
  gitTreeState: clean
  gitVersion: v1.32.3-gke.1927009
  goVersion: go1.23.8 X:boringcrypto
  major: "1"
  minor: "32"
  platform: linux/amd64
```

### Kubernetes Cluster Type

GKE

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml

```

### prometheus-operator log output

```shell
jsonPayload: {
alertmanager: "kube-prometheus-stack-alertmanager"
caller: {3}
component: "alertmanager-controller"
level: "warn"
match: "map[application:proxy-dispenser-live]"
match_re: "map[]"
msg: "'matchers' field is using a deprecated syntax which will be removed in future versions"
namespace: "monitoring"
receiver: "default/proxy-dispenser-live/slack"
ts: "2025-05-29T03:11:29.239028388Z"
}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dongjiang1989**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Close #7569

Fix When MatchType is empty and AM version >= v0.22,  match to Regex bug

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
When MatchType is empty and AM version >= v0.22,  match to Regex bug
```

### CODE REVIEW

**Comment by dongjiang1989** [comment]
cc @nicolastakashi PTAL, thanks

File: pkg/alertmanager/amcfg.go [hunk 1]
```diff
@@ -486,6 +488,15 @@ func (cb *ConfigBuilder) convertRoute(in *monitoringv1alpha1.Route, crKey types.
 			continue
 		}
 
+		if matchersV2Allowed {
```
Comment (simonpasquier) [inline pkg/alertmanager/amcfg.go]: since it looks very similar to what already exists in `convertInhibitRule()`, can we extract the code into a separate method?

**Review by simonpasquier — COMMENTED** [review]
one small nit otherwise LGTM, thanks!

File: pkg/alertmanager/amcfg.go (hunk 1 above)
Comment (dongjiang1989) [reply pkg/alertmanager/amcfg.go]: Thanks @simonpasquier 
Got it.
Fixed. Please re-check it

**Comment by dongjiang1989** [comment]
> one small nit otherwise LGTM, thanks!

Thanks @simonpasquier 
Fixed. Please re-check it
