### PR TITLE
pkg/prometheus: Ignore PartialResponseStrategy for Prometheus

### LINKED ISSUE #5124: Prometheus log reports field partial_response_strategy not found in type rulefmt.RuleGroup when sets this field in PrometheusRule
**What happened?**
Prometheus log reports field partial_response_strategy not found in type rulefmt.RuleGroup when sets this field in PrometheusRule. This was getting logged till removed this field or set it to `""`

```
ts=2022-10-27T11:43:29.048Z caller=manager.go:980 level=error component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules/prometheus-user-workload-rulefiles-0/ns1-example-alert-2f98a05b-dd27-4d1a-87bd-5ef74352cc3a.yaml: yaml: unmarshal errors:\n  line 3: field partial_response_strategy not found in type rulefmt.RuleGroup"
ts=2022-10-27T11:43:29.048Z caller=main.go:1227 level=error msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
ts=2022-10-27T11:43:29.048Z caller=main.go:945 level=error msg="Error reloading config" err="one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"
```

**Did you expect to see something different?**

Since this field is only applicable for Thanos. Operator should reject this field for Prometheus and allow it only for Thanos

**How to reproduce it (as minimally and precisely as possible)**:

Create a PrometheusRule object with `partial_response_strategy` set to a valid accepted value

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert
  namespace: ns1
spec:
  groups:
  - name: example
    partial_response_strategy: "abort"
    rules:
    - alert: VersionAlert
      expr: version{job="prometheus-example-app"} == 0
```

**Environment**

All

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

NA

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

NA

* Manifests:

```
insert manifests relevant to the issue
```

NA

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

NA

**Anything else we need to know?**:

As discussed in https://github.com/prometheus-operator/prometheus-operator/pull/4999#issuecomment-1280927196

### PR DESCRIPTION
**Pull request by slashpai**
partial_response_strategy field is only applicable for Thanos so if a user sets this by mistake in PrometheusRule object prometheus errors this field is not found in rule format.

This commit is to fix that and allow this field only for Thanos

Fixes #5124

Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Ignore PartialResponseStrategy for Prometheus
```

### CODE REVIEW

File: pkg/prometheus/rules.go [hunk 1]
```diff
@@ -332,20 +332,37 @@ func prometheusRuleConfigMapName(prometheusName string) string {
...
-func GenerateContent(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
+func GenerateContent(objectType string, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
 	content, err := yaml.Marshal(promRule)
 	if err != nil {
 		return "", errors.Wrap(err, "failed to marshal content")
 	}
+
 	errs := ValidateRule(promRule)
-	if len(errs) != 0 {
+	if errs != nil {
```
Comment (simonpasquier) [inline pkg/prometheus/rules.go:342]: Better to keep the original case IMHO as an empty slice might not be nil.

```suggestion
	if len(errs) != 0 {
```

File: pkg/prometheus/rules.go [hunk 2]
```diff
@@ -332,20 +332,37 @@ func prometheusRuleConfigMapName(prometheusName string) string {
 }
 
 // GenerateContent takes a PrometheusRuleSpec and generates the rule content
-func GenerateContent(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
+func GenerateContent(objectType string, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (simonpasquier) [inline pkg/prometheus/rules.go:335]: 2 functions would be more explicit IMHO. I'd also recommend moving the code to the pkg/operator package since it's shared between prometheus and thanos.

```suggestion
func GenerateRulesConfigurationForPrometheus(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
    // Unset partialResponseStrategy field.
    for _, for i := range promRule.Groups {
        ...
    }
    return generateRulesConfiguration(promRule, logger)
}

func GenerateRulesConfigurationForThanos(objectType string, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
    return generateRulesConfiguration(promRule, logger)
}

func generateRulesConfiguration(objectType string, promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
    // same as GenerateContent
}
```

Comment (slashpai) [reply pkg/prometheus/rules.go]: Thanks for that suggestion :) It looks much better :)

**Comment by slashpai** [comment]
@simonpasquier I have updated the PR with suggestions

File: pkg/operator/rules.go [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+		level.Debug(logger).Log("msg", m, "content", content)
+		for _, err := range errs {
+			level.Info(logger).Log("msg", m, "err", err)
+		}
+		return "", errors.New(m)
+	}
+	return string(content), nil
+}
+
+// ValidateRule takes PrometheusRuleSpec and validates it using the upstream prometheus rule validator
```
Comment (simonpasquier) [inline pkg/operator/rules.go:61]:
```suggestion
// ValidateRule takes PrometheusRuleSpec and validates it using the upstream prometheus rule validator.
```

File: pkg/operator/rules.go [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+		}
+		// TODO(slashpai): Remove this validation after v0.65 since this is handled at CRD level
+		if _, ok := thanostypes.PartialResponseStrategy_value[strings.ToUpper(group.PartialResponseStrategy)]; !ok {
+			return []error{
+				fmt.Errorf("invalid partial_response_strategy %s value", group.PartialResponseStrategy),
+			}
+		}
+
+		// reset this as the upstream prometheus rule validator
+		// is not aware of the partial_response_strategy field
```
Comment (simonpasquier) [inline pkg/operator/rules.go:75]:
```suggestion
		// is not aware of the partial_response_strategy field.
```

File: pkg/operator/rules.go [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+	"github.com/go-kit/log"
+	"github.com/go-kit/log/level"
+	"github.com/pkg/errors"
+	"github.com/prometheus/prometheus/model/rulefmt"
+
+	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
+	thanostypes "github.com/thanos-io/thanos/pkg/store/storepb"
+)
+
+func GenerateRulesConfigurationForPrometheus(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:31]: It's a bit inconsistent that the unit tests live in pkg/prometheus while the impementation is in pkg/operator. I believe that we could move `GenerateRulesConfigurationForPrometheus()` to the pkg/prometheus package (and rename it to `GenerateRulesConfiguration(...)`)

File: pkg/operator/rules.go [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+	// Unset partialResponseStrategy field.
+	for i := range promRule.Groups {
+		promRule.Groups[i].PartialResponseStrategy = ""
+	}
+
+	return generateRulesConfiguration(promRule, logger)
+}
+
+func GenerateRulesConfigurationForThanos(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:40]: in the same vein, `GenerateRulesConfigurationForThanos` could go away and pkg/thanos can call `operator.GenerateRulesConfiguration(...)` directly.

File: pkg/operator/rules.go [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+	return generateRulesConfiguration(promRule, logger)
+}
+
+func generateRulesConfiguration(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```
Comment (simonpasquier) [inline pkg/operator/rules.go:44]:
```suggestion
func GenerateRulesConfiguration(promRule monitoringv1.PrometheusRuleSpec, logger log.Logger) (string, error) {
```

File: pkg/thanos/rules_test.go [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+	"k8s.io/apimachinery/pkg/util/intstr"
+
+	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
+	"github.com/prometheus-operator/prometheus-operator/pkg/operator"
+)
+
+func TestMakeRulesConfigMapsThanos(t *testing.T) {
+	t.Run("shouldAcceptRuleWithValidPartialResponseStrategyValue", shouldAcceptRuleWithValidPartialResponseStrategyValue)
+	t.Run("shouldRejectRuleWithInvalidPartialResponseStrategyValue", shouldRejectRuleWithInvalidPartialResponseStrategyValue)
+	t.Run("shouldAcceptRuleWithPartialResponseStrategySet", shouldAcceptRuleWithPartialResponseStrategySet)
```
Comment (simonpasquier) [inline pkg/thanos/rules_test.go:32]: Quite similar to `shouldAcceptRuleWithValidPartialResponseStrategyValue` so I suggest to remove this test.

File: pkg/operator/rules.go (hunk 5 above)
Comment (slashpai) [reply pkg/operator/rules.go:31]: Sure can do that :). I created separated ones based on previous discussion https://github.com/prometheus-operator/prometheus-operator/pull/5125#discussion_r1008045422 since both Prometheus and Thanos  calls the method

Comment (slashpai) [reply pkg/operator/rules.go:31]: I think we would need `GenerateRulesConfigurationForPrometheus()` and `GenerateRulesConfigurationForThanos()` to differentiate who is calling `GenerateRulesConfiguration` that way we can say if `partialResponseStrategy` field is valid or not

**Comment by slashpai** [comment]
@simonpasquier I updated the PR with changes. Moved tests to respective package as well where the code exists

**Review by simonpasquier — APPROVED** [review]
thanks!
